### ISSUE TITLE
[Android] Error when set custom Surface for videoSurfaceOutput.

### ISSUE THREAD

**Issue by duy-maimanh** [google-ai-edge/mediapipe#2405]
I'm trying to get the output image into a Surface.
Original, we will set like that.

        it.holder.addCallback(object : SurfaceHolder.Callback {
            override fun surfaceChanged(
                holder: SurfaceHolder,
                format: Int,
                width: Int,
                height: Int
            ) {
                val viewSize = Size(width, height)
                val displaySize: Size? = cameraHelper?.computeDisplaySizeFromViewSize(viewSize)

                val isCameraRotated = cameraHelper!!.isCameraRotated

                converter?.setSurfaceTextureAndAttachToGLContext(
                    previewFrameTexture,
                    if (isCameraRotated) displaySize!!.height else displaySize!!.width,
                    if (isCameraRotated) displaySize.width else displaySize.height
                )
            }

            override fun surfaceDestroyed(holder: SurfaceHolder) {
                processor?.videoSurfaceOutput?.setSurface(null)
            }

            override fun surfaceCreated(holder: SurfaceHolder) {
                processor?.videoSurfaceOutput?.setSurface(holder.surface)
            }
        })
    }

But I don't want to display the output on the screen. So I created a surface to receive the output.

         val textures = IntArray(1)
         GLES30.glGenTextures(1, textures, 0)
         val result = textures[0]
         val surfaceTexture = SurfaceTexture(result)
         val customSurface = Surface(surfaceTexture)
         processor?.videoSurfaceOutput?.setSurface(customSurface)

I received an error as follows.

> 2021-08-11 17:18:10.031 11123-11280/jp.tech.computervisiondemo E/BufferQueueProducer: [SurfaceTexture-1-11123-2] dequeueBuffer: BufferQueue has been abandoned
2021-08-11 17:18:10.032 11123-11280/jp.tech.computervisiondemo I/Adreno: DequeueBuffer: dequeueBuffer failed
2021-08-11 17:18:10.032 11123-11280/jp.tech.computervisiondemo E/BufferQueueProducer: [SurfaceTexture-1-11123-2] dequeueBuffer: BufferQueue has been abandoned
2021-08-11 17:18:10.032 11123-11280/jp.tech.computervisiondemo I/Adreno: DequeueBuffer: dequeueBuffer failed
2021-08-11 17:18:10.056 11123-11220/jp.tech.computervisiondemo D/ExternalTextureConv: Created output texture: 144 width: 960 height: 1280
2021-08-11 17:18:10.069 11123-11220/jp.tech.computervisiondemo E/FrameProcessor: Mediapipe error: 
    com.google.mediapipe.framework.MediaPipeException: internal: Graph has errors: 
    Calculator::Process() for node "egl_surface_sink_output_video" failed: ; failed to swap buffersiapipe/gpu/gl_surface_sink_calculator.cc:136) 
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:360)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:442)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:350)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:295)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$IXJjtE68JMV2CMJNQcFYhTUqhj8.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)

Do you have any suggestions?

**Comment by zhoujingheng** [comment]
Hi@sgowroj  i just want Landmark only

**Comment by ninh-huynh** [comment]
> Hi @sgowroji Thanks for your answer. The main reason is that I want to get the surface to use for other purposes instead of using the surface of the surfaceView. Now I fixed. Generate texture with textureTarget = GLES11Ext.GL_TEXTURE_EXTERNAL_OES. and create surface like this: val outputSurfaceTexture = SurfaceTexture(�textureID, false)

Could you share your final solution for this issue? Currently, I want to set up videoSurfaceOutput to be able to work with GLSurfaceView by passing custom Surface like you, and then draw the texture in GLSurfaceView#Renderer#onDrawFrame. 
The app still rendering without any exception from logcat, but it does not render the preview correctly, just a weird color.

Here is my working code 
`

        var externalTextureRenderer: ExternalTextureRenderer? = null
        var outputSurfaceTexture: SurfaceTexture? = null

        // Initializes a new Gl surface view with a user-defined FaceMeshResultGlRenderer.
        glSurfaceView = GLSurfaceView(this).apply {
            setEGLContextClientVersion(eglManager!!.glMajorVersion)
            setEGLContextFactory(object : GLSurfaceView.EGLContextFactory {
                override fun createContext(
                    egl: EGL10,
                    display: EGLDisplay,
                    eglConfig: EGLConfig,
                ): EGLContext {
                    val contextAttrs = intArrayOf(
                        EglManager.EGL_CONTEXT_CLIENT_VERSION, eglManager!!.glMajorVersion, EGL10.EGL_NONE
                    )
                    return egl.eglCreateContext(display, eglConfig, eglManager!!.context, contextAttrs)
                }

                override fun destroyContext(
                    egl: EGL10,
                    display: EGLDisplay,
                    context: EGLContext
                ) {
                    if (!egl.eglDestroyContext(display, context)) {
                        throw RuntimeException("eglDestroyContext failed")
                    }
                }

            })

            setRenderer(object : GLSurfaceView.Renderer {
                override fun onSurfaceCreated(gl: GL10?, config: EGLConfig?) {
                    externalTextureRenderer = ExternalTextureRenderer()
                    externalTextureRenderer!!.setup()

                    val textures = intArrayOf(0)
                    GLES20.glGenTextures(1, textures, 0)
                    outputSurfaceTexture = SurfaceTexture(textures[0], false)
                    outputSurface = Surface(outputSurfaceTexture)
                    processor!!.getVideoSurfaceOutput()!!
                        .setSurface(outputSurface)
                }

                override fun onSurfaceChanged(gl: GL10?, width: Int, height: Int) {

                }

                override fun onDrawFrame(gl: GL10?) {
                    val surfaceTexture = outputSurfaceTexture
                    if (surfaceTexture != null) {
                        externalTextureRenderer!!.render(surfaceTexture)
                    }
                }
            })
        }
`

**Comment by ninh-huynh** [comment]
For anyone who is looking for the solution to, use the FrameProcessor#setConsumer to receive the TextureFrame (It has texture id associated with) and then draw it in GLSurfaceView. No need for set videoSurfaceOutput


```kotlin
        val glSurfaceViewRenderer = GlSurfaceViewRenderer()
        glSurfaceViewRenderer.setTextureTarget(GLES20.GL_TEXTURE_2D)

        frameProcessor.setConsumer {
            glSurfaceViewRenderer.setNextFrame(it)
            glSurfaceView!!.requestRender()
        }

        glSurfaceView = GLSurfaceView(this).apply {
            setEGLContextClientVersion(eglManager!!.glMajorVersion)
            setEGLContextFactory(object : GLSurfaceView.EGLContextFactory {
                override fun createContext(
                    egl: EGL10,
                    display: EGLDisplay,
                    eglConfig: EGLConfig,
                ): EGLContext {
                    val contextAttrs = intArrayOf(
                        EglManager.EGL_CONTEXT_CLIENT_VERSION, eglManager!!.glMajorVersion, EGL10.EGL_NONE
                    )
                    return egl.eglCreateContext(display, eglConfig, eglManager!!.context, contextAttrs)
                }

                override fun destroyContext(
                    egl: EGL10,
                    display: EGLDisplay,
                    context: EGLContext
                ) {
                    if (!egl.eglDestroyContext(display, context)) {
                        throw RuntimeException("eglDestroyContext failed")
                    }
                }

            })

            setRenderer(glSurfaceViewRenderer)
            renderMode = GLSurfaceView.RENDERMODE_WHEN_DIRTY
        }

```
