### ISSUE TITLE
Estimate the head orientation from my webcam through mediapipe 468 landmarks

### ISSUE THREAD

**Issue by showbit01** [google-ai-edge/mediapipe#2471]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):
- Programming Language and version ( e.g. C++, Python, Java):

**Describe the expected behavior:**

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by ablavatski** [comment]
[Face Geometry API](mediapipe/modules/face_geometry/README.md) should help you with that however @kostyaby could suggest a better solutions since he is the main author of face estimation ML pipeline.

**Comment by kostyaby** [comment]
Hey @showbit01,

As @ablavatski, [Face Geometry API] is indeed what can help for your use-case. MediaPipe JS API now provides this kind of support, please take a look:

- https://www.npmjs.com/package/@mediapipe/face_mesh
- https://www.jsdelivr.com/package/npm/@mediapipe/face_mesh
- [index.d.ts](https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1629159166/index.d.ts); what you are interested is the "FaceGeometry" part of the API
