### ISSUE TITLE
Couldn't find the requested file /face_detection_short.binarypb in @mediapipe/face_detection.

### ISSUE THREAD

**Issue by justinmeskan** [google-ai-edge/mediapipe#2635]
I am using the mesh decetion with no issues but when I setup the simple face detection I got these errors saying these files don't exist, here are the actual errors-
-Couldn't find the requested file /face_detection_short.binarypb in @mediapipe/face_detection.
-Couldn't find the requested file /face_detection_short_range.tflite in @mediapipe/face_detection.

Heres my code-

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils/control_utils.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/drawing_utils.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/face_detection.js" crossorigin="anonymous"></script>
</head>

<body>
<div class="container">
    <video src="./galleryView5.mov"
           id="video" width="0" height="0">
    </video>
    <canvas id="canvas" width="1280px" height="720px"></canvas><br>
</div>
</body>
</html>
<script type="module">
	var canvas = document.getElementById('canvas');
	var video  = document.getElementById('video');
	var ctx    = canvas.getContext('2d');
	var playStop = true

	function onResults(results) {
		// Draw the overlays.
		ctx.save();
		ctx.clearRect(0, 0, canvas.width, canvas.height);
		ctx.drawImage(
			results.image, 0, 0, canvas.width, canvas.height);
		if (results.detections.length > 0) {
			drawingUtils.drawRectangle(
				ctx, results.detections[0].boundingBox,
				{color: 'blue', lineWidth: 4, fillColor: '#00000000'});
			drawingUtils.drawLandmarks(ctx, results.detections[0].landmarks, {
				color: 'red',
				radius: 5,
			});
		}
		ctx.restore();
	}

	const faceDetection = new FaceDetection({locateFile: (file) => {
			return `https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.0/${file}`;
		}});
	faceDetection.setOptions({
		modelSelection: 0,
		minDetectionConfidence: 0.5
	});
	faceDetection.onResults(onResults);

	video.addEventListener('play', function () {
		var $this = this; //cache
		// $this.currentTime = 320 // good 3 person view
		// $this.currentTime = 520 // end
		faceDetection.onResults(onResults);
		async function loop(results) {
			if (!$this.paused && !$this.ended) {
				ctx.clearRect(0, 0, canvas.width, canvas.height);
				ctx.drawImage($this, 0, 0);
				await faceDetection.send({image: video}); // this needs to be a piece of the video not the whole thing a frame
				setTimeout(loop, 1000 / 30); // drawing at 30fps
			}
		}
		loop()
	})
	document.addEventListener('click', function () {
		if(playStop){

			video.play()
		} else {
			video.pause()
		}
		playStop = !playStop
	})
</script>

**Comment by justinmeskan** [comment]
Hi @sgowroji When i click the link i get a 404 error

**Comment by tyrmullen** [comment]
I didn't get the same error you did, but I was able to get your code running by fixing the option: `modelSelection: 0` to be `model: 'short'` instead.  Because the JS Solutions errors so opaque (and things like options so brittle), I recommend in the future starting by directly copying the setup from one of the existing demos, and then altering that to fit your use case.  Otherwise it feels like there are too many tiny setup things that can go wrong.  (Ideally we would fix this in the framework, of course, but our bandwidth is very limited at the moment).

**Comment by MaximeCheramy** [comment]
`model: 'short'` fixed my issue too. Could you please update the documentation accordingly? https://google.github.io/mediapipe/solutions/face_detection.html

Thanks!

**Comment by uctakeoff** [comment]
I was just having the same problem.
Sure enough, it worked with `model: 'short'`, but with `model: 'full'` I get an error.

```
        face_detection_solution_simd_wasm_bin.js:9 Uncaught (in promise) RuntimeError: Aborted(native code called abort())
        at abort (face_detection_solution_simd_wasm_bin.js:9:25546)
        at _abort (face_detection_solution_simd_wasm_bin.js:9:163790)
        at face_detection_solution_simd_wasm_bin.wasm:0x4b9cf3
        at face_detection_solution_simd_wasm_bin.wasm:0x4b9b98
        at face_detection_solution_simd_wasm_bin.wasm:0x4b9d68
        at face_detection_solution_simd_wasm_bin.wasm:0x178b3
        at face_detection_solution_simd_wasm_bin.wasm:0x1200b
        at SolutionWasm$send [as send] (eval at new_ (face_detection_solution_simd_wasm_bin.js:9:140739), <anonymous>:9:1)
        at oa.h (face_detection.js:75:76)
        at H (face_detection.js:14:296)
```

I got it to work by putting the callback method `locateFile` as follows There seems to be a bug in the process of determining the file name.

```js
        const faceDetection = new FaceDetection({locateFile: (file) => {
            console.log(`file=${file}`);
            switch (file) {
                case 'face_detection_short.binarypb': file = 'face_detection_full.binarypb'; break;
                case 'face_detection_short_range.tflite': file = 'face_detection_full_range.tflite'; break;
                default: break;
            }
            return `https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/${file}`;
        }});
```

**Comment by robotpapier** [comment]
back again, I think I solved it now.
This is what i added to my vite.config.js file

`build: {
		assetsInlineLimit: 0, // do not inline assets
		rollupOptions: {
			plugins: [
			],
		},
	},`

And I have no idea why it works :/
