### ISSUE TITLE
Distinguished technical bull. Is Mediappipe only available on Python? I want to use C++ on visual studio now. Can I use it? There is my environment has not been correctly configured, I hope you can help me. Thank you

### ISSUE THREAD

**Issue by BaiL939** [google-ai-edge/mediapipe#2644]
Distinguished technical bull. Is Mediappipe only available on Python? I want to use C++ on visual studio now. Can I use it? There is my environment has not been correctly configured, I hope you can help me. Thank you

**Comment by sgowroji** [comment]
Hi @BaiL939, We have already an issue with similar context which is in progress. Please have a look at it https://github.com/google/mediapipe/issues/1162
