### ISSUE TITLE
what‘s the output of the mediapipe pose model "pose_landmark_full.tflite"

### ISSUE THREAD

**Issue by Jerryzhangzhao** [google-ai-edge/mediapipe#2657]
Hi, I am working on pose estimation use mediapipe pose.
I am using the model "pose_landmark_full.tflite", and visualize the model with tensorflow.lite.tools.visualize as
![tflite_model](https://user-images.githubusercontent.com/10524773/137053830-231f1e64-4c15-490a-b0a6-9090af3d867c.png)
:
The picture shows that there are 5 outputs and "Identity_3" has the shape [1x64x64x39].
the [doc](https://ai.googleblog.com/2020/08/on-device-real-time-body-pose-tracking.html) of mediapipe says that the keypoint number is 33. So I was confused that why the output is [1x64x64x39], it seems that there are some extra channel there. I've read the blazePose paper and didn't find any clus. 
And one more question. what the value range of the input image, [0,1] / [-1,1] ?

**Comment by gioipv** [comment]
Thank you for your experiment. But I have a question about image pre-processing: do we need resize image with keeping the aspect ratio between the height and width of the images. ?
