### ISSUE TITLE
Failed to run the graph: CalculatorGraph with error : Op type not registered 'DecodeJpeg' in binary running on ...

### ISSUE THREAD

**Issue by aks200000** [google-ai-edge/mediapipe#2663]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (MacOS BigSur v 11.5.2):
- Compiler version (Apple clang version 12.0.5 (clang-1205.0.22.11)):
- Programming Language and version ( e.g.  Python 3.7.7, Java: 1.8.0_291):
- Installed using virtualenv? pip? Conda? (if python): conda 
- [MediaPipe version](v 0.8.8):
- Bazel version: 3.7.2
- XCode and Tulsi versions (if iOS): xcode-select version 2384.
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): opencv@3

**Describe the problem**:

Following the install documents , I checked out mediapipe repo  and followed step by step instructions to install bazel, opencv, ffmpeg etc. compiled mediapipe using bazel as below

bazel build -c opt --linkopt=-s \
            --define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true \
            mediapipe/examples/desktop/youtube8m:extract_yt8m_features

Tested media pipe installation by running Hello_Word example successfully.
Downloaded all the requisite files - inception-2015-12-05.tgz and other .PB files - in /tmp/mediapipe
Tried testing the feature extraction of a video file by first running the following cmd , which succeeded and produced a metadata.pb file in /tmp/mediapipe

python -m mediapipe.examples.desktop.youtube8m.generate_input_sequence_example \
            --path_to_input_video=/tmp/sampleVideos/userVideoTest1.mp4 \
            --clip_end_time_sec=300

But the next step to extract feature by the following cmd failed with the error mentioned in this issue title

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/youtube8m/extract_yt8m_features \
            --calculator_graph_config_file=mediapipe/graphs/youtube8m/feature_extraction.pbtxt \
            --input_side_packets=input_sequence_example=/tmp/mediapipe/metadata.pb  \
            --output_side_packets=output_sequence_example=/tmp/mediapipe/features.pb

The short version of the error from the logs is as below:

Failed to run the graph: CalculatorGraph::Run() failed in Run: 
Calculator::Open() for node "TensorFlowSessionFromFrozenGraphCalculator_1" failed: ; Create failed: Not found: Op type not registered 'DecodeJpeg' in binary running on 2030009788. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

described above

**Complete Logs:**
attached
[mediapipe.log](https://github.com/google/mediapipe/files/7343944/mediapipe.log)

**Comment by versusniubility** [comment]
same issue, as I checked the tensorflow website, the DecodeJpeg is from tensorflow 2.0, is this the problem?

**Comment by aks200000** [comment]
I looked at #2569 and have this question in this regard.

Can you be more specific about what needs to be changed in WORKSPACE file to pull in a stable version of tensorflow ?
In latest version of mediapipe's WORKSPACE file, I see this tag and value

_TENSORFLOW_GIT_COMMIT = "52a2905cbc21034766c08041933053178c5d10e3"

Are you suggesting changing this GIT Commit hash to something else pointing to a STABLE tensorflow version and recompile ?

If yes, can you please suggest which hash value to use , instead of just saying STABLE version ?
