### ISSUE TITLE
How can I perform face warpings using face mesh?

### ISSUE THREAD

**Issue by zzmicer** [google-ai-edge/mediapipe#2665]
### Hello! I'm trying to perform smth like auto-smiling(see attach.)  
Is there any way to warp/move facial keypoints and texture around them(real-time)?

- Solution: **FaceMesh**
- Programming Language and version: **C++**

### Example: 

![image](https://user-images.githubusercontent.com/41323462/137347029-10f49a7d-7d36-40c3-b22c-cb1469769b87.png)

**Comment by zzmicer** [comment]
Hello, @kostyaby!
Did you get a chance to go through my issue? :)

**Comment by kostyaby** [comment]
Hey @zzmicer,

Apologies for the late reply; has been on a vacation for the last 2 weeks.

Unfortunately, I don't feel like your rough plan has enough specificity for me to comment whether it can work out or not. Warping face images is generally tricky (much trickier than warping AR textures along the detected face mesh lines or attaching 3D AR objects to a face), so be ready to deal with lots of uncanny results with any approach you choose

If I had to solve smth this problem myself, I'd probably try going 2D first. I'd probably focus on a curve defined by 3 key landmarks: both lip edge landmarks + the middle of the mouth landmark. Then, I'd pre-define some canonical "smile" curve parameters and try to move my key landmarks on a given image so the parameters are matched. Of course, moving just the key landmarks would make the result uncanny straight away, so I'd consider employing some kind of "soft" landmark moving operator (i.e. when I move a 2D landmark A by (dX, dY), then I also move all 2D landmarks in the closest neighborhood by ~0.25-0.75 * (dX, dY); maybe, I should also move all 2D landmarks in the next closest neighborhood by ~0.1-0.4 * (dX, dY) and so on - hard to tell specifics, those need to be experimented with)

Such an approach would work nicely if you wanted people on your images to blink or to have enlarged eyes, in those cases the curve parameterization is even simplier. I think it'd be a decent start for your "smiley face" project too

After the 2D face mesh topology has been transformed into a "smiley" one, just do smth like [OpenCV affine transformations](https://docs.opencv.org/4.5.3/d4/d61/tutorial_warp_affine.html) triangle-per-triangle according to the face mesh topology

**Comment by zzmicer** [comment]
Hello again, @kostyaby!
I've met another challenge related to this issue. I am trying to run my liquify filter on an ios device.

Should I rewrite the whole OpenCV logic to OpenGL? Or I just need to convert my modified opencv image buffer(ImageFrame) to GpuBuffer?

**Comment by kostyaby** [comment]
Hey @zzmicer,

If you want processing to be on iOS GPU then it has to be re-written from OpenCV to OpenGL ES / Metal. If you are fine with the processing to be left on CPU but you need it on GPU for the next pipeline stages, then simply converting ImageFrame -> GpuBuffer would suffice

**Comment by zzmicer** [comment]
@kostyaby Thank you for clarification!
