### ISSUE TITLE
How to use the videoinput.start()?

### ISSUE THREAD

**Issue by tigerya214** [google-ai-edge/mediapipe#2699]
### Question:

I want to add the url in the mediapipe hands, how could it use the videoInput.start()?
(I found my code is error)

### Code:
     // The runnable to start camera after the gl surface view is attached.
    // For video input source, videoInput.start() will be called when the video uri is available.
    if (inputSource == InputSource.CAMERA) {
      glSurfaceView.post(this::startCamera);
    }else if (inputSource == InputSource.esp32_stream){
      glSurfaceView.post(videoInput.start("http://10.10.100.4:81/stream"));
    }

**Comment by sgowroji** [comment]
Hi @xiaogong331, You can reuse the same implementation by adding one more loadUrl() method. Where you will be rendering the webview using the above streaming url.  You should be adding a <WebView> element  in xml file with no visibility initially. And enable the visibility of the <webview> only before when you want to loadUrl.
