### ISSUE TITLE
iOS Framework Crash on dealloc, in waitUntilDoneWithError

### ISSUE THREAD

**Issue by Ankish** [google-ai-edge/mediapipe#2730]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): iOS 14
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone11
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
- Programming Language and version ( e.g. C++, Python, Java): Swift / Objective-C
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.8
- Bazel version (if compiling from source): 4.2.1
- Solution ( e.g. FaceMesh, Pose, Holistic ): Pose
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
- Xcode & Tulsi version (if issue is related to building for iOS):Xcode 13, 0.20210318.88

**Describe the current behavior:**
Created Full Body Pose framework with the above media pipe version.
Framework and example code to generate the framework is attached in the repo :
https://github.com/Ankish/Full_Body_Pose

When the dealloc on the graph  is called it crashes with:
Example[27472:3196778] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'waitUntilDoneWithError: should not be called on the main thread'

**Describe the expected behavior:**

**Standalone code to reproduce the issue:**
Check with the attached git repo:
https://github.com/Ankish/Full_Body_Pose
OnStart Button will launch the Pose controller, tap on close to dismiss, it crashes on dealloc. 

**Other info / Complete Logs :**
 Similar reported earlier : https://github.com/google/mediapipe/issues/651

**Comment by BTLDXX-x** [comment]
@Ankish , how did you after modified the `dealloc ` function? thanks!
