### ISSUE TITLE
How to show all landmarks in one color

### ISSUE THREAD

**Issue by baberjunaid** [google-ai-edge/mediapipe#2984]
The code provided on [pose landmarks](https://google.github.io/mediapipe/solutions/pose) I want to show all landmarks in one color, i.e., Green. Now after doing some predictions on **results** variable, I want to draw again the landmarks in RED. So what should be change in this snippet

```
mp_drawing.draw_landmarks(
        image,
        results.pose_landmarks,
        mp_holistic.POSE_CONNECTIONS,
        landmark_drawing_spec=mp_drawing_styles
        .get_default_pose_landmarks_style())
```

**Comment by sgowroji** [comment]
Hi @baberjunaid, You can do the changes to the color in https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/drawing_utils.py of your code.

**Comment by sgowroji** [comment]
Below are the default Drawing specs for color.  You can change the color with python implementation as per your business requirement!

# (48, 255, 48) For Green color
def get_default_pose_landmarks_style() -> Mapping[int, DrawingSpec]:
  """Returns the default pose landmarks drawing style.

  Returns:
      A mapping from each pose landmark to its default drawing spec.
  """
  pose_landmark_style = {}
  left_spec = DrawingSpec(
      color=(48, 255, 48), thickness=_THICKNESS_POSE_LANDMARKS)
  right_spec = DrawingSpec(
      color=(48, 255, 48), thickness=_THICKNESS_POSE_LANDMARKS)
