### ISSUE TITLE
build android aar failed in mac apple clip

### ISSUE THREAD

**Issue by siwgong** [google-ai-edge/mediapipe#3860]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): macos 12.4
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): Apple clang version 13.1.6 (clang-1316.0.21.2.5)
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
- Installed using virtualenv? pip? Conda? (if python): conda python 3.9.12
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.11
- Bazel version: 5.2.0
- XCode and Tulsi versions (if iOS): 
- Android SDK and NDK versions (if android): sdk: 30.0.0 ndk: 18.1.5063045
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): mediapipe_face_detection
- OpenCV version (if running on desktop): 4.6.0

**Describe the problem**:

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

when i build face detection AAR:
```bash
bazel build -c opt --strip=ALWAYS \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    --legacy_whole_archive=0 \
    --features=-legacy_whole_archive \
    --copt=-fvisibility=hidden \
    --copt=-ffunction-sections \
    --copt=-fdata-sections \
    --copt=-fstack-protector \
    --copt=-Oz \
    --copt=-fomit-frame-pointer \
    --copt=-DABSL_MIN_LOG_LEVEL=2 \
    --linkopt=-Wl,--gc-sections,--strip-all \
    //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar
```

the error log:
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "691a29db9c336349e48e04c5c2f4873f2890af5cbfa6e51f4de87fefe6169294"
DEBUG: Repository rules_cc instantiated at:
  /Users/gongsiwei/opt/coding/mediapipe/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_gongsiwei/976df888e1db78db74ae61a4f686d025/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
ERROR: /Users/gongsiwei/opt/coding/mediapipe/mediapipe/gpu/BUILD:396:13: in objc_library rule //mediapipe/gpu:pixel_buffer_pool_util: Expected action_config for 'objc++-compile' to be configured
ERROR: /Users/gongsiwei/opt/coding/mediapipe/mediapipe/gpu/BUILD:396:13: in objc_library rule //mediapipe/gpu:pixel_buffer_pool_util:
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/objc/objc_library.bzl", line 127, column 124, in _objc_library_impl
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 316, column 50, in _register_compile_and_archive_actions
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 394, column 66, in _cc_compile_and_link
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 193, column 29, in _compile
Error in compile: Expected action_config for 'objc++-compile' to be configured
ERROR: /Users/gongsiwei/opt/coding/mediapipe/mediapipe/gpu/BUILD:396:13: Analysis of target '//mediapipe/gpu:pixel_buffer_pool_util' failed
WARNING: /Users/gongsiwei/opt/coding/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /Users/gongsiwei/opt/coding/mediapipe/mediapipe/framework/tool/BUILD:185:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar' failed; build aborted:
INFO: Elapsed time: 0.156s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @remotejdk11_macos_aarch64; fetching

**Comment by kuaashish** [comment]
Hi @siwgong,
Could you please let us know the Mac processor type for example M2, M1 or Intel etc. Thank you!

**Comment by siwgong** [comment]
I use Apple m2 processor

**Comment by kuaashish** [comment]
Hi @siwgong,
Currently, MediaPipe does not support the Apple Silicon chip such as M1 and M2. We still do not have native Python wheels and can be run Python under Rosetta. The team is actively working towards supporting it However does not have the more details on this. Thank you!

**Comment by ayushgdev** [comment]
Hello @siwgong 
We are revisiting older issues. Would you please check in the latest version of MediaPipe and let us know if the issue still persists for you?
