### ISSUE TITLE
Any way to "free" FaceLandmarker's "temporal cache" during runningMode VIDEO?

### ISSUE THREAD

**Issue by delta42** [google-ai-edge/mediapipe#4693]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 10 / Chrome

### MediaPipe Tasks SDK version

0.10.3

### Task name (e.g. Image classification, Gesture recognition etc.)

FaceLandmarker

### Programming Language and version (e.g. C++, Python, Java)

JavaScript

### Describe the actual behavior

```shell
I am successfully using the FaceLandmarker in CPU mode and runningMode VIDEO to process webcam video.

I also sometimes need to perform Face Landmark Detection on a static image.

I have found through experimentation that if I process video and then a static image, sometimes the static image processing does not give accurate results. When I use runningMode IMAGE, I do not have this problem, but I find video processing to be a bit slower.

Not knowing what is happening, I assumed that FaceLandmarker may contain some temporal information about the previous positions of the face, and somehow use this when provided a static image.
Is this is indeed true, is there some smart way to "reset" this? When the first thing I do is load a static image, it's always accurate. It only starts giving problems when I first process video and then a static image. When I process the static image a few times in a row, it finally gives the correct result.
```

### Describe the expected behaviour

```shell
It would be nice if the temporal info could be reset.

I understand I could create TWO FaceLandmarkers, one for IMAGE and one for VIDEO, but I'm already having a hard time with initialization delays.
```

### Standalone code/steps you may have used to try to get what you need

```shell
Create a FaceLandmarker with these options:


const options = {
                        baseOptions: {
                            modelAssetPath: `https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task`,
                            delegate: 'CPU'
                        },
                        outputFaceBlendshapes: false,
                        runningMode: 'VIDEO',
                        numFaces: 1
                    };
```

Run it against a video passing it an HTMLVideoElement, then run it against a static image from an HTMLImageElement.

The results may be way off, and take several iterations of re-processing the same static image until it zeroes in on the actual Face Landmarks.
```


### Other info / Complete Logs

_No response_

**Comment by schmidt-sebastian** [comment]
Are you re-setting the running mode when switching between video and image? This should reset all internal state.

If you are only using running Mode video you need to ensure that there is a sufficient time gap between time stamps if you want to force a re-initialization of the entire processing pipeline.
