### ISSUE TITLE
Documentation for building pose-tracking iOS app using mediapipe library with swift

### ISSUE THREAD

**Issue by diyoraharshitN** [google-ai-edge/mediapipe#4895]
### Description of issue (what needs changing)

Hi Team, I couldn't find any guidelines/documentation for building pose-tracking iOS app using mediapipe library with swift

### Clear description

I am looking for Documentation for building pose-tracking iOS app using mediapipe library with swift.

### Usage example

https://developers.google.com/mediapipe/framework/getting_started/ios

**Comment by kuaashish** [comment]
Hi @diyoraharshitN,

At the moment, we don't have the pose landmarker available on the iOS platform, and there's no official documentation for its use in Swift. However, we do have [iOS documentation](https://github.com/google/mediapipe/blob/master/docs/getting_started/ios.md) for legacy pose tracking, and the iOS target is mentioned [here](https://github.com/google/mediapipe/blob/master/docs/solutions/pose.md#main-example). It's important to note that we are not offering support for legacy solutions, as our primary focus is on the new Task APIs. However, We are actively working to provide iOS-Swift support for other Task APIs as well.


Thank you

**Comment by diyoraharshitN** [comment]
Kindly look into this link it's not working
http://mediapipe/examples/ios/posetrackinggpu/BUILD

**Comment by dprichards-carespace** [comment]
> Hi @diyoraharshitN,
> 
> At the moment, we don't have the pose landmarker available on the iOS platform, and there's no official documentation for its use in Swift. However, we do have [iOS documentation](https://github.com/google/mediapipe/blob/master/docs/getting_started/ios.md) for legacy pose tracking, and the iOS target is mentioned [here](https://github.com/google/mediapipe/blob/master/docs/solutions/pose.md#main-example). It's important to note that we are not offering support for legacy solutions, as our primary focus is on the new Task APIs. However, We are actively working to provide iOS-Swift support for other Task APIs as well.
> 
> Thank you

Do you have any updated timeline on this documentation?

**Comment by dprichards-carespace** [comment]
We want to use pose landmarker on the iOS platform, and there's no official documentation for its use in Swift. Do you have any updated timeline for this documentation?

**Comment by schmidt-sebastian** [comment]
@ktonthat

**Comment by diyoraharshitN** [comment]
Hi @kuaashish,

Thank you for the update about example.
Do you have any updated timeline on documentation?

**Comment by diyoraharshitN** [comment]
Hi @kuaashish 

i have searched in the example but didn't find any seperetion for Left Body landmarks and Right Body landmarks points.
where in web version in the node_modules @mediapipe>holistic>index.d.ts there is const declared for Left side landmark for pose as POSE_LANDMARKS_LEFT and for Right side landmark for pose as POSE_LANDMARKS_RIGHT.

is there any way to separate Left and Right landmarks from the MPPNormalizedLandmark array that we get as result array from the scan?

Thank you
Harshit

**Comment by schmidt-sebastian** [comment]
cc @priankakariatyml

**Comment by diyoraharshitN** [comment]
Hi @kuaashish

I have found that there are 4 points 24 and 26 (right knee and right hip), 25 and 27(left foot and left knee) are missing from the ios Version of [example](https://github.com/googlesamples/mediapipe/tree/main/examples/pose_landmarker/ios) in mediapipe.

Thank you

**Comment by diyoraharshitN** [comment]
> Hi @kuaashish
> 
> i have searched in the example but didn't find any seperetion for Left Body landmarks and Right Body landmarks points. where in web version in the node_modules @mediapipe>holistic>index.d.ts there is const declared for Left side landmark for pose as POSE_LANDMARKS_LEFT and for Right side landmark for pose as POSE_LANDMARKS_RIGHT.
> 
> is there any way to separate Left and Right landmarks from the MPPNormalizedLandmark array that we get as result array from the scan?
> 
> Thank you Harshit

Hi @kuaashish @priankakariatyml 

This is gentle reminder regarding clarification regarding the Ride side and Left side landmark points.

Thanks 
Harshit

**Comment by diyoraharshitN** [comment]
> Hi @kuaashish
> 
> I have found that there are 4 points 24 and 26 (right knee and right hip), 25 and 27(left foot and left knee) are missing from the ios Version of [example](https://github.com/googlesamples/mediapipe/tree/main/examples/pose_landmarker/ios) in mediapipe.
> 
> Thank you

This issue is resolve by using connection. [Click Here](https://github.com/googlesamples/mediapipe/pull/347#issuecomment-2084643826)

**Comment by kuaashish** [comment]
Hi @diyoraharshitN,

Thank you for confirming. Can we now proceed with closing the issue and marking it as resolved?

**Comment by diyoraharshitN** [comment]
> Hi @diyoraharshitN,
> 
> Thank you for confirming. Can we now proceed with closing the issue and marking it as resolved?

Hi @kuaashish 

1. Documentation is still not there for mediapipe iOS Pose landmark detection [Click Here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker).

2. There is no seperation for Left Body Points and Right Body Points.I have already comment in this issue only [Click Here](https://github.com/google/mediapipe/issues/4895#issuecomment-2051796753)

**Comment by diyoraharshitN** [comment]
Hi,

This is gentle reminder for the issue i have raised regarding

Documentation is still not there for mediapipe iOS Pose landmark detection [Click Here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker).

There is no seperation for Left Body Points and Right Body Points.I have already comment in this issue only https://github.com/google/mediapipe/issues/4895#issuecomment-2051796753

**Comment by diyoraharshitN** [comment]
Hi @kuaashish @schmidt-sebastian,

any update regarding documentation and about these [Comment](https://github.com/google-ai-edge/mediapipe/issues/4895#issuecomment-2051796753)

**Comment by kuaashish** [comment]
Hi @diyoraharshitN,

Apologies for the delayed response. Currently, there is no update on the documentation. We are sharing this issue with our team again and marking it as a feature request to ensure it remains a priority. However, we cannot provide a timeline for this at the moment.

Thank you!!

**Comment by diyoraharshit** [comment]
Hi @priankakariatyml 

i have searched in the example but didn't find any seperetion for Left Body landmarks and Right Body landmarks points.
where in web version in the node_modules @mediapipe>holistic>index.d.ts there is const declared for Left side landmark for pose as POSE_LANDMARKS_LEFT and for Right side landmark for pose as POSE_LANDMARKS_RIGHT.

is there any way to separate Left and Right landmarks from the MPPNormalizedLandmark array that we get as result array from the scan?

Thank you
Harshit

**Comment by kuaashish** [comment]
Hi @diyoraharshit,

Documentation for implementing our Pose Landmarker in iOS is now [available](https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker/ios). Could you please try it and let us know if you encounter any further issues?

Thank you!!
