### ISSUE TITLE
Media pipe doesnt detect the camera

### ISSUE THREAD

**Issue by BoGuanchez** [google-ai-edge/mediapipe#5083]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

MacOs M1

### Task name (e.g. Image classification, Gesture recognition etc.)

Camera 

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

doesnt work

### Describe the expected behaviour

detect the camera

### Standalone code/steps you may have used to try to get what you need

```shell
I just download the mediapipe plugin to use it at touchdesigner, so I open the main project MediaPipe TouchDesigner.toe then I Select my main camera and it doesn't show any image, but when i use a videodevice_in it automatically use my main camera.
Therefore almost every subsequent node show me some kind of error
Im using a macbook air M1, so, the main camera is a facetime camera.
```

**Comment by kuaashish** [comment]
Hi @BoGuanchez,

Certainly! Can you outline the steps you're following and mention the documentation you are referring to? Also, sharing the reproducible standalone code you are using would help us to better understand and address the issue.

Thank you!!

**Comment by BoGuanchez** [comment]
I just opened the .toe file, and selected webcam at the videodevice in

<img width="1190" alt="Screenshot 2024-01-22 at 10 39 30" src="https://github.com/google/mediapipe/assets/157034472/85468015-99c8-4f1a-ada9-4e1a61695bfc">
<img width="861" alt="Screenshot 2024-01-22 at 10 40 16" src="https://github.com/google/mediapipe/assets/157034472/ec12109e-b40b-42c1-9657-e2f908d8d0a7">
<img width="1267" alt="Screenshot 2024-01-22 at 10 40 36" src="https://github.com/google/mediapipe/assets/157034472/b733aadb-ab5a-4cec-a741-50533482e9cd">
<img width="1202" alt="Screenshot 2024-01-22 at 10 44 37" src="https://github.com/google/mediapipe/assets/157034472/4fed6d55-6674-4d96-a9dd-ad4931707612">

**Comment by BoGuanchez** [comment]
The .tox files doesnt drag and drop either @kuaashish 
https://github.com/google/mediapipe/assets/157034472/98529151-8ded-4b68-847b-9fb24cec3ff0

**Comment by rafaroeder** [comment]
hello! did you solve this? I was working perfect last week and then when reopening the project, the camera is not recognized.

**Comment by kuaashish** [comment]
Hi @BoGuanchez, @rafaroeder,

Could you kindly provide the comprehensive steps outlined in our documentation or share the standalone code? Additionally, please specify pertinent details such as the MediaPipe version and Python version utilized, aiding us in reproducing and comprehending the issue on our end.

Thank you!!

**Comment by BoGuanchez** [comment]
When the camera doesnt work I just erase the mediapipe component and drop it again, im not sure why this still happening

**Comment by kuaashish** [comment]
Hi @BoGuanchez,

Could you please confirm whether the issue has been resolved on your end, or if you still require assistance from our end?

Thank you!!

**Comment by ashanta-1807** [comment]
@kuaashish @BoGuanchez was this issue solved? I'm having the same issue. Tried syphon/spout route too. Tried installing OBS camera too. Still not working. 

After opening the mediapipe file for the first time, and n number of times later.

Kindly help
 
<img width="2056" alt="Image" src="https://github.com/user-attachments/assets/2e0b1bf3-3a42-4859-8adc-b0755135b6d3" />

**Comment by rafaroeder** [comment]
Ive found this to have very simple solutions (because it happens sometimes) which is basically updating drivers of cameras, making sure that cameras are not being used by other softwares on the back, maybe opening or downloading again the td patch. Good luck!

**Comment by BSMTHXX** [comment]
Having tried both SpoutCam and OBS Studio and recieving the same error prompt I used the Streamlabs Virtual Camera with SpoutCam as source and this worked.
