### ISSUE TITLE
DOC: Difference between landmarks from FaceMesh and FaceLandmarker

### ISSUE THREAD

**Issue by twoertwein** [google-ai-edge/mediapipe#5129]
### Description of issue (what needs changing)

Document performance differences between facial landmark models.

### Clear description

`FaceMesh` return landmarks, which can optionally be refined (`refine_landmarks`). It is not clear how those two landmarks compare to the landmarks extracted by `FaceLandmarker`. The landmarks returned by all three alternatives are different: have there been comparisons in terms of the accuracy? I would prefer using the `FaceLandmarker` as it also returns Blendshapes.

**Comment by kuaashish** [comment]
Hi @twoertwein,

I apologize for the delayed response. Could you please confirm if this issue has been resolved on your end, or if you still require assistance from us?

Thank you!!
