### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by diogommartins** [google-ai-edge/mediapipe#5259]
### MediaPipe Solution (you are using)

Python

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

Python 3.12 users are unable to install mediapipe

### Will this change the current API? How?

No

### Who will benefit with this feature?

All python 3.12 users

### Please specify the use cases for this feature

Using mediapipe in python 3.12 applications

**Comment by schmidt-sebastian** [comment]
@ayushgdev started working on this.

**Comment by yoyojacky** [comment]
![image](https://github.com/google/mediapipe/assets/6893075/e2c597a4-3de7-411f-927e-f2ebafd5fbc4)
I have the same issure, thanks ayushgdev's hard work!!!!

**Comment by kuaashish** [comment]
Hi @yoyojacky,

We are already working on this. Hopefully, everything will be okay. Support will be available in the upcoming release, which is scheduled in the coming weeks.

**Comment by yoyojacky** [comment]
> Support will be available in the upcoming release, which is scheduled in the coming weeks.



> Hi @yoyojacky,
> 
> We are already working on this. Hopefully, everything will be okay. Support will be available in the upcoming release, which is scheduled in the coming weeks.

ok, thanks for your hardwork, have a nice day!

**Comment by schmidt-sebastian** [comment]
We have added 3.12 wheels.
