### ISSUE TITLE
convert ImageFrame  to Image 

### ISSUE THREAD

**Issue by ly0303521** [google-ai-edge/mediapipe#5307]
In vision task object detect , the type of input is Image, like this
`absl::StatusOr<ObjectDetectorResult> ObjectDetector::Detect(
    mediapipe::Image image,
    std::optional<core::ImageProcessingOptions> image_processing_options)`
But when I create a node based on ObjectDetector, in the graph, the input is ImageFrame,  how can I conver ImageFrame to Image

**Comment by kuaashish** [comment]
Hi @ly0303521,

I apologize for the delayed response. Could you please confirm if this issue has been resolved on your end, or if you still require assistance from us?

Thank you!!
