### ISSUE TITLE
difference in results for landmarks and world_landmarks

### ISSUE THREAD

**Issue by swafe** [google-ai-edge/mediapipe#5325]
I run the python example in colab and provide this image [https://beyogi.com/learn-yoga/poses/warrior-ii-pose/] as input. It is a typical yoga pose. When I compare the results of landmarks and world_landmarks I get this:

XY CoordinateSystem is in the top left corner of the image, y positive down
print(landmark12) #shoulder joint
NormalizedLandmark(x=0.43, y=0.23, z=-0.04,
print(landmark14) #elbow joint
NormalizedLandmark(x=0.31, y=0.22, z=-0.10, 

XY CoordinateSystem is in the center of the hips
print(world_landmark12) #shoulder joint
Landmark(x=-0.18, y=-0.52, z=-0.01, 
print(world_landmark14) #elbow joint
Landmark(x=-0.42, y=-0.47, z=-0.04, 

when I compare the y values for landmark results the elbow joint (y=0.22) is higher than the shoulder joint (y=0.23) (y-axis goes from image top to down)
for world_landmarks  elbow joint (y=-0.47) is lower than the shoulder joint (y=-0.52) (y-axis goes from hips down)

Can you reproduce this results or am I missing something?

I need the worldlandmarks because the z values seems to be better and I want the euler angles between the bones to create a animation of a 3D skeleton avatar

**Comment by swafe** [comment]
To simplify the question. Do the results for landmarks and world_landmarks differ in XY plane or should they be qualitative identical

**Comment by matanox** [comment]
Generally, so called "landmarks" and "world landmarks" in mediapipe are entirely different things ― one is the camera/image viewport coordinates of the landmarks with a defunct z value, and the other is a 3D representation of the tracked object's landmarks (hand, skeleton, etc.) which is detached from the position of the object in the image, and having its axes origin relative to some point in itself. 

Obviously this naming convention doesn't help, so try to just accept it.

the 3D representation can be only used in terms of the ratios of lengths between landmarks, as the model does not predict your hand or skeleton size. 

I hope this helps. But you sure need to go back to research how each of the two landmark sets helps your application or not.

**Comment by kuaashish** [comment]
Hi @matanox,

I apologize for the delayed response. Could you please confirm if this issue has been resolved on your end, or if you still require assistance from us?

Thank you!!

**Comment by matanox** [comment]
They are just saying that they don't understand the semantics of the landmarks. You should probably refer them to the related documentation, if my explanation above doesn't help.

**Comment by kuaashish** [comment]
HI @matanox,

Thank you for your response. The explanation looks good. However, we do not have a more detailed one. @swafe, please let us know if you are satisfied with this answer or if you need further assistance.
