### ISSUE TITLE
No clear apks for quick testing

### ISSUE THREAD

**Issue by StarShine1A** [google-ai-edge/mediapipe#5338]
This template is for miscellaneous issues not covered by the other issue categories

For documentation and code such as
 https://developers.google.com/mediapipe/solutions/vision/image_generator/android 
And
https://developers.google.com/mediapipe/solutions/genai/llm_inference/android

there is no clear apks issued for download to quickly test them, just build instructions.

**Comment by kuaashish** [comment]
Hi @StarShine1A,


Hi @StarShine1A,

We already have a demo available for the Image Generator at this link: https://github.com/googlesamples/mediapipe/tree/main/examples/image_generation/android, and for LLM Inference, it's here: https://github.com/googlesamples/mediapipe/tree/main/examples/llm_inference/android. I believe it would be beneficial to include these demos in our documentation. I will notify the team about this suggestion. Thank you for bringing it to our attention.

**Comment by S3od22** [comment]
@


في خميس، 2 مايو، 2024 في 4:46 ص، كتب github-actions[bot] <
***@***.***>:

**Comment by kuaashish** [comment]
Hi @ktonthat,

Do you have any suggestions? If we can make this demo APK available on respective documentations for quick testing.

Thank you!!

**Comment by schmidt-sebastian** [comment]
On top of what @kuaashish suggested, we also allow anyone to test our Web inference via https://mediapipe-studio.webapps.google.com/home. You can play with Gemma and other model variants there. For more thorough testing, please see the GitHub samples repo linked above.
