### ISSUE TITLE
Build fails for Coral - Docker gcc too old for XNNPACK?

### ISSUE THREAD

**Issue by tonystratum** [google-ai-edge/mediapipe#5347]
### OS Platform and Distribution

debian buster (Docker)

### Compiler version

gcc8.3 (docker)

### Programming Language and version

c++

### MediaPipe version

0.10.11

### Bazel version

as per .bazelversion

### Android AAR (if android)

None

### Describe the problem

A bug happened!

### Complete Logs

```shell
ERROR: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/XNNPACK/BUILD.bazel:1519:19: Compiling src/amalgam/gen/neoni8mm.c failed: (Exit 1): aarch64-linux-gnu-gcc failed: error executing command (from target @XNNPACK//:neoni8mm_prod_microkernels) /usr/bin/aarch64-linux-gnu-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-march=armv8-a' -g0 -O3 -DNDEBUG ... (remaining 39 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
cc1: error: invalid feature modifier in '-march=armv8.2-a+i8mm+fp16'
Target //mediapipe/examples/coral:object_detection_tpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 149.181s, Critical Path: 11.07s
INFO: 499 processes: 263 internal, 236 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by FunnyWii** [comment]
Have you solved it yet?

I met same problem... I think this problem comes from bazel instead of mediapipe

**Comment by FunnyWii** [comment]
I Solved this problem via upgrading gcc&g++ from 9 to 10.

**Comment by kuaashish** [comment]
Hi @tonystratum,

Can you try out the suggestion mentioned by @FunnyWii, And please let us know if this still an issue? 


Thank you!!

**Comment by tonystratum** [comment]
@kuaashish certainly will try! @FunnyWii have you upgreaded the compiler  within docker build environment? If so, how? Thanks

**Comment by tonystratum** [comment]
@FunnyWii please, could You share the steps for upgrading the toolchain?

**Comment by FunnyWii** [comment]
> @FunnyWii please, could You share the steps for upgrading the toolchain?

sry for the late response, I update gcc via `sudo apt install gcc-10`

**Comment by tonystratum** [comment]
@FunnyWii Yeah no worries, thanks! @kuaashish I just wanted to know if Coral TPU is still supported at this point. The Coral's Mendel Linux is based on Debian Buster, and the toolchain there (gcc-9) does not compile the fresh XNNPACK (what @FunnyWii is actually saying). We would need to update toolchain on both the Mendel linux and the docker build environment [here](https://github.com/google/mediapipe/tree/master/mediapipe/examples/coral)

**Comment by kuaashish** [comment]
Hi @FunnyWii,

Currently, the new Task API supports Edge devices such as the Raspberry Pi 4, as mentioned on the referenced page. For legacy solutions, we supported the Coral TPU, If this is the case, we will not be able to assist you, as support for the legacy solution has completely ended.

Thank you!!
