### ISSUE TITLE
No attribute 'GenerateCpuTfLite'

### ISSUE THREAD

**Issue by zkh2016** [google-ai-edge/mediapipe#5355]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

mac os 

### Programming Language and version

python

### Solution

llm

### Describe the actual behavior

Get an error

### Describe the expected behaviour

Expecting to convert the model successfully.

### Standalone code/steps you may have used to try to get what you need

```shell
Hello, after compiling and installing the Python package from the source code, I encountered the following error when trying to convert my own model. Is there any additional option that can be added during compilation to solve this problem?


File "python3.9/site-packages/mediapipe/tasks/python/genai/converter/llm_converter.py", line 163,  in combined_weight_bins_to_tflite
    model_ckpt_util.GenerateCpuTfLite(
AttributeError: module 'mediapipe.python._framework_bindings.model_ckpt_util' has no attribute 'GenerateCpuTfLite'
```
```


### Other info / Complete Logs

_No response_

**Comment by zkh2016** [comment]
I added --copt=ENABLE_ODML_CONVERTER in setup.py but it didn't work.

**Comment by zkh2016** [comment]
@ayushgdev Unable to find the odml package for local compilation. How can I pull the odml package?

**Comment by kuaashish** [comment]
Hi @zkh2016,

We believe, We have not tested this scenario yet. Could you please share the complete steps you're following from the documentation?

Thank you!!

**Comment by zkh2016** [comment]
Firstly, compile and install the source code through `python3 setup.py install -- link opencv`, and then follow this [tutorial](https://developers.google.com/mediapipe/solutions/genai/llm_inference/android#convert-model) to convert the model. The error message `has no attribute' GenerateCpuTfLite ` was prompted. Therefore, try to directly place the `ODML` package in `media pipe/Python/pybind/BUILD` into deps, and when compiling, the prompt `The repository '@ ODML' could not be resolved`
So, how to compile the source code and use it correctly?

**Comment by kuaashish** [comment]
Hi @zkh2016,  

After internal discussion, we have concluded that this scenario cannot be supported. This functionality is designed and built specifically for internal use and is not intended for the wider user base. As a result, we likely won't be able to resolve this issue for your specific use case.

Thank you!!

**Comment by zkh2016** [comment]
> Hi @zkh2016,
> 
> After internal discussion, we have concluded that this scenario cannot be supported. This functionality is designed and built specifically for internal use and is not intended for the wider user base. As a result, we likely won't be able to resolve this issue for your specific use case.
> 
> Thank you!!

Thank you for your answer. My goal is actually to use MediaPipe to run the Minicpm model. Can you help me adapt it? Or what should I do to get this model running with MediaPipe.

**Comment by kuaashish** [comment]
Hi @zkh2016,

We want to inform you that currently, this is not possible. We have already brought it to the attention of the team, and it is on our roadmap. Rest assured, Our team is actively working on this, and it will be available soon.

Thank you!!
