### ISSUE TITLE
LLM inference task questions (GPU implementation, KV cache)

### ISSUE THREAD

**Issue by tc-wolf** [google-ai-edge/mediapipe#5363]
I'm reviewing Mediapipe as a potential solution for non-Android embedded GPU inference (using an Adreno GPU) and wanted to ask some basic questions:

* Is the implementation for GPU inference with the LLM task included in this repo?  I only see `mediapipe/tasks/cc/genai/inference/c/llm_inference_engine_cpu.cc` for CPU inference. I can see that `mediapipe/tasks/cc/genai/inference/calculators/llm_gpu_calculator.proto` defines GPU inference options, but I don't find the interface for that anywhere.

* Is it possible to use a KV cache with inference with mediapipe for the LLM inference task?  I have a use case that benefits from storing a KV cache for prompt + prefixes in a RAG use case.

**Comment by kuaashish** [comment]
Hi @tc-wolf,

Regarding your first query, our llm inference task API currently does not support GPU usage. We are actively working to make it compatible with GPU, as indicated in this issue https://github.com/google/mediapipe/issues/5305 marked as a feature request. We will be focusing on implementing this feature soon.

Regarding your second query, we do not have any specific pointers at the moment. However, please allow us some time to discuss with our team, and we will inform you once any updates become available.

Thank you!!

**Comment by kuaashish** [comment]
Hi @tc-wolf,

Regarding your other question, we are excited to announce upcoming features for the LLM side of MediaPipe! These include support for multiple models, KV cache, quantization support and many more within the framework. While we can not disclose all details just yet, but yeah it will be available soon.

Thank you!!

**Comment by kuaashish** [comment]
Update: 

Apologies for the oversight. Please note that GPU support is not currently available through our C API. But, you can leverage GPU capabilities via our Maven package.
