### ISSUE TITLE
ValueError: Task runner is currently not running.

### ISSUE THREAD

**Issue by mcdonasd1212** [google-ai-edge/mediapipe#5365]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Ubuntu 22.04.4 LTS   

### MediaPipe Tasks SDK version

0.10.11

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose Landmark Detection

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

Task runner is not currently running when 
```shell
frame_timestamp_ms = mp.Timestamp.from_seconds(timestamps).value
mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image)

results = pose.detect_for_video(mp_image, frame_timestamp_ms)
```

### Describe the expected behavior

```shell
results = pose.detect_for_video(mp_image, frame_timestamp_ms)
```
This command crashes and returns the ValueError: Task runner is currently not running

### Standalone code/steps you may have used to try to get what you need
The legacy solution works:
```shell
 self.mp_pose = mp.solutions.pose
  self.pose_detector = self.mp_pose.Pose(static_image_mode=False, min_detection_confidence=0.5,
                                          min_tracking_confidence=0.5)
```
The current version does not:
```shell
options = PoseLandmarkerOptions(
    base_options=BaseOptions(model_asset_path=model_path),
    running_mode=VisionRunningMode.VIDEO)

with PoseLandmarker.create_from_options(options) as pose_replay:
        pose_replay
```
### Other info / Complete Logs

```shell
pose <mediapipe.tasks.python.vision.pose_landmarker.PoseLandmarker object at 0x7f992c2b08d0>

  File "/lib/python3.11/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 119, in _process_video_data
    return self._runner.process(inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Task runner is currently not running.
```

**Comment by mcdonasd1212** [comment]
Update,  I do not get the error when I use the legacy solution.
`
 self.mp_pose = mp.solutions.pose
  self.pose_detector = self.mp_pose.Pose(static_image_mode=False, min_detection_confidence=0.5,
                                          min_tracking_confidence=0.5)
`

**Comment by mcdonasd1212** [comment]
@schmidt-sebastian   it seems like there should be an easy answer,  any advise?

**Comment by mcdonasd1212** [comment]
Update fixed issue by Threading 

```
with PoseLandmarker.create_from_options(options) as pose_replay:
        pose_replay
```

Why did I have to thread for the new Mediapipe Pose but not the legacy version?

**Comment by kuaashish** [comment]
Hi @mcdonasd1212,

Apologies for the delayed response. Could you kindly share more details, including the standalone code you are using and the Python version, to help us reproduce the issue and gain a better understanding?

Thank you!!
