### ISSUE TITLE
Disable/customise augmentation for the object_detector task

### ISSUE THREAD

**Issue by DoctorDinosaur** [google-ai-edge/mediapipe#5367]
### MediaPipe Solution (you are using)

Object Detection (Model Maker)

### Programming language

Python

### Are you willing to contribute it

No

### Describe the feature and the current behaviour/state

Currently, while the Image Classification task has "do_data_augmentation", the Object Detection Task does not. The object detection task should be provided this option. 

It would also be useful if both could allow for customisation. TF-Vision [exposes](https://www.tensorflow.org/api_docs/python/tfm/vision/configs/maskrcnn/Parser) aug_scale_min, aug_scale_max, aug_rand_hflip, aug_rand_vflip, and aug_type; where aug_type can take a tfm.vision.configs.common.Augmentation (i.e. AutoAugment or RandAugment) 

### Please specify the use cases for this feature

My dataset includes "right arrow" and "left arrow". [Random Flipping is enforced](https://github.com/google/mediapipe/blob/0b18e25e0281590ddcfd859fe6739e51732b3fcb/mediapipe/model_maker/python/vision/object_detector/preprocessor.py#L104) and cannot be disabled, without subclassing the object detection class. This means the classes cannot be trained.

**Comment by kuaashish** [comment]
Hi @joezoug,

Do we have a plan to incorporate this feature into the Object Detection model maker?

Thank you!!

**Comment by joezoug** [comment]
Hi @DoctorDinosaur,

Thanks for the suggestion. Unfortunately the team doesn't have bandwidth to make this change in the near future. Can you try subclassing/overriding the class to disable data augmentation?
