### ISSUE TITLE
SplitTensorVectorCalculator

### ISSUE THREAD

**Issue by Karangautam870** [google-ai-edge/mediapipe#5368]
ConstantSidePacketCalculator: Number of output side packets has to be same as number of packets configured in options.
ImageToTensorCalculator:Output tensor range is required.
SplitTensorVectorCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions
how to solve this issue

**Comment by kuaashish** [comment]
HI @Karangautam870,

Apologies for the delay in response. Could you please let us know if you still need support from our end, or if this is no longer an issue?

Thank you!!

**Comment by Karangautam870** [comment]
Yes, everything is fine.

**Comment by kuaashish** [comment]
Hi @Karangautam870,

Thank you for confirming. We are now closing this issue and marking it as resolved internally.
