### ISSUE TITLE
This simple code while running causing me so much problem

### ISSUE THREAD

**Issue by Karangautam870** [google-ai-edge/mediapipe#5369]
import mediapipe as mp
import cv2 as cv
import time

cap = cv.VideoCapture(0)

mphands = mp.solutions.hands
hands = mphands.Hands()

while True:
    success,img = cap.read()
    imgRGB = cv.cvtColor(img,cv.COLOR_BGR2RGB)
    results = hands.process(imgRGB)
    cv.imshow("Image",img)

    cv.waitKey(0)
 
i am trying to run this code but it is showing me this error
RuntimeError: ValidatedGraphConfig Initialization failed.
ImageToTensorCalculator: ; RET_CHECK failure (mediapipe/calculators/tensor/image_to_tensor_calculator.cc:144) ValidateOptionOutputDims(options) returned INTERNAL: ; RET_CHECK failure (./mediapipe/calculators/tensor/image_to_tensor_utils.h:136) options.has_output_tensor_float_range() || options.has_output_tensor_int_range() || options.has_output_tensor_uint_range()Output tensor range is required. 
ConstantSidePacketCalculator: ; RET_CHECK failure (mediapipe/calculators/core/constant_side_packet_calculator.cc:64) (cc->OutputSidePackets().NumEntries(kPacketTag))==(options.packet_size())Number of output side packets has to be same as number of packets configured in options.
ConstantSidePacketCalculator: ; RET_CHECK failure (mediapipe/calculators/core/constant_side_packet_calculator.cc:64) (cc->OutputSidePackets().NumEntries(kPacketTag))==(options.packet_size())Number of output side packets has to be same as number of packets configured in options.
ImageToTensorCalculator: ; RET_CHECK failure (mediapipe/calculators/tensor/image_to_tensor_calculator.cc:144) ValidateOptionOutputDims(options) returned INTERNAL: ; RET_CHECK failure (./mediapipe/calculators/tensor/image_to_tensor_utils.h:136) options.has_output_tensor_float_range() || options.has_output_tensor_int_range() || options.has_output_tensor_uint_range()Output tensor range is required. 
ConstantSidePacketCalculator: ; RET_CHECK failure (mediapipe/calculators/core/constant_side_packet_calculator.cc:64) (cc->OutputSidePackets().NumEntries(kPacketTag))==(options.packet_size())Number of output side packets has to be same as number of packets configured in options.
ConstantSidePacketCalculator: ; RET_CHECK failure (mediapipe/calculators/core/constant_side_packet_calculator.cc:64) (cc->OutputSidePackets().NumEntries(kPacketTag))==(options.packet_size())Number of output side packets has to be same as number of packets configured in options.
SplitTensorVectorCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
please help what should i do

**Comment by kuaashish** [comment]
Hi @Karangautam870,

After reviewing the code snippet you provided, it appears that you are using an legacy version of MediaPipe Hand Solution. We have recently launched enhanced MediaPipe Tasks APIs, which provide increased stability and functionality compared to the legacy version.

We strongly advise migrating to these updated APIs for Hand landmarks, as we no longer support legacy solutions. You can find the documentation for the Hand Landmarker [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker) and implementation guide for Python [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/python).

Unfortunately, aside from this, we won't be able to assist you much further.

Thank you!!

**Comment by kuaashish** [comment]
Hi @Karangautam870,

As suggested [above](https://github.com/google-ai-edge/mediapipe/issues/5369#issuecomment-2090528041), please migrate to our new Task API. If you encounter any further issues, let us know. Note that we will no longer support the legacy solution, Unfortunately, We will be not able to help you out on this.

Thank you!!

**Comment by Karangautam870** [comment]
> Hi @Karangautam870,
> 
> As suggested [above](https://github.com/google-ai-edge/mediapipe/issues/5369#issuecomment-2090528041), please migrate to our new Task API. If you encounter any further issues, let us know. Note that we will no longer support the legacy solution, Unfortunately, We will be not able to help you out on this.
> 
> Thank you!!

How to migrate like give me some links or steps to do this
