### ISSUE TITLE
Holistic not included in BUILD for iOS

### ISSUE THREAD

**Issue by amokto** [google-ai-edge/mediapipe#5380]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

iOS

### MediaPipe Tasks SDK version

0.10.13

### Task name (e.g. Image classification, Gesture recognition etc.)

Holistic

### Programming Language and version (e.g. C++, Python, Java)

Swift

### Describe the actual behavior

Holistic is not included in 0.10.13

### Describe the expected behaviour

Holistic should be included in 0.10.13

### Standalone code/steps you may have used to try to get what you need

```shell
Holistic does not seem to be included in 0.10.13 BUILD
https://github.com/google/mediapipe/blob/6e604b686ec185381a7dcdd3666a8f7db1220e2c/mediapipe/tasks/ios/BUILD

Unless I misinterpreted the changelog / release notes it should be available in 0.10.13 for iOS?
```

**Comment by schmidt-sebastian** [comment]
@priankakariatyml Can you take a look?

**Comment by amokto** [comment]
I noticed that there is an active pull request that addresses this: https://github.com/google-ai-edge/mediapipe/pull/5423

I hope this fix can be included in the next release. Once integrated, feel free to close this issue. Thanks!

**Comment by kuaashish** [comment]
Hi @amokto,

Based on your report, we have brought this issue to our team's attention. A PR for the fix has been created and is currently awaiting review. It will be included in the upcoming release once it is merged.

Thank you!!

**Comment by amokto** [comment]
Awesome, thanks a lot @kuaashish I see the PR is approved now. 
Are you able to give an estimate when you think the next release will be? ie. would it be a couple weeks or a month? 
Thanks again.

**Comment by kuaashish** [comment]
Hi @amokto,

We can not provide an exact release date, but if everything goes well on our end, we planned to release it within the upcoming 1-2 weeks.

Thank you!!
