### ISSUE TITLE
How can I use the cartoon face?

### ISSUE THREAD

**Issue by 327635328** [google-ai-edge/mediapipe#5386]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

linux

### MediaPipe Tasks SDK version

0.10.11

### Task name (e.g. Image classification, Gesture recognition etc.)

Face Landmark Detection

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

I don't know how to turn a face into a cartoon

### Describe the expected behaviour

show the Cartoon face

### Standalone code/steps you may have used to try to get what you need

```shell
I have successfully implemented Face Landmark Detection, which enables me to obtain all the points of the face. I can see that the face can be transformed into a cartoon bear face in the demo. May I ask how it is achieved? I did not find a code example, can you guide the implementation process, thank you
```

### Other info / Complete Logs

```shell
cv2.VideoCapture(0)
use vision.FaceLandmarker model_asset_path='face_landmarker.task' 
for i in range(len(face_landmarks)):
    pos_x = int(face_landmarks[i].x * width)
    pos_y = int(face_landmarks[i].y * height)

i success to get the points
```

**Comment by kuaashish** [comment]
Hi @327635328,

Apologies for the delayed response. Based on our internal discussion, the avatar model is currently available only in the web version, which you can find here https://mediapipe-studio.webapps.google.com/studio/demo/face_landmarker. This version is not open source, so customization is not possible. Additionally, we have no current plans to provide an avatar demo in Python.

However, we encourage you to raise a [feature request](https://github.com/google-ai-edge/mediapipe/issues/new?assignees=&labels=type%3Afeature&projects=&template=14-feature-request-issue-template.yaml) with detailed information on how this feature would benefit the community and its potential use cases. This feedback will help us consider its implementation in the future. 

Thank you.
