### ISSUE TITLE
Object detection model can't be used in C++

### ISSUE THREAD

**Issue by ly0303521** [google-ai-edge/mediapipe#5389]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

ubuntu20

### Python Version

3.11

### MediaPipe Model Maker version

0.2.1.3

### Task name (e.g. Image classification, Gesture recognition etc.)

Object detection

### Describe the actual behavior

model maker train is successful, but failed in C++ inference

### Describe the expected behaviour

the trained model can inference in C++

### Standalone code/steps you may have used to try to get what you need

```shell
In the begining, I use mediapipe follow the example "mediapipe/graphs/object_detection", its inferenced in C++, the model is "ssdlite_object_detection.tflite". 
Now, I tried retrain the object detection model, follow "https://developers.google.com/mediapipe/solutions/customization/object_detector", I found the models are 
MOBILENET_V2
MOBILENET_V2_I320
MOBILENET_MULTI_AVG
MOBILENET_MULTI_AVG_I384,
these are different from "ssdlite_object_detection.tflite".
I choosed "MOBILENET_V2" to try, training is successful, but I found MOBILENET_V2 model can't replace ssdlite_object_detection
```

**Comment by ly0303521** [comment]
#5308 more details in this issue I raised 1 month ago

**Comment by schmidt-sebastian** [comment]
Have you tried the model in MediaPipe Studio?

https://mediapipe-studio.webapps.google.com/studio/demo/object_detector

**Comment by ly0303521** [comment]
@schmidt-sebastian the model in MediaPipe Studio is EfficientDet-lite0, the model in model maker are 
MOBILENET_V2
MOBILENET_V2_I320
MOBILENET_MULTI_AVG
MOBILENET_MULTI_AVG_I384,
I just test these four models, If I want to use model maker about "object detection", I just can choose one of these above four Mobilenet models, right?

**Comment by ly0303521** [comment]
> Have you tried the model in MediaPipe Studio?
> 
> https://mediapipe-studio.webapps.google.com/studio/demo/object_detector

In "mediapipe/graphs/object_detection/object_detection_desktop_live.pbtxt" , I repalece "ssdlite_object_detection.tflite" with "efficientdet_lite0.tflite", error appeared: "Check failed: raw_box_tensor->dims->data[1] == num_boxes_ (19206 vs. 2034)", I think it is the difference between of model structure, so the postprocess is also different. In a word, in the C++ desktop example, we can't just repalece the object detection model with efficientdet model and mobilenet, so I think model maker about object detection is not useful in C++ example.

**Comment by architjaiswal** [comment]
I am still confused on how to convert the model such that it gets the same 4 outputs I was initially giving. I also saved the model using `model.export_model(model.export_model(model_name=model_out, quantization_config=quantization_config)`

Can someone tell me how to convert the trained model to obtain the 4 output (locations, classes, scores, detections)?

I was trying to run inference in C++ using the following code but it failed due to output mismatch:
````cpp
    // https://www.tensorflow.org/lite/models/object_detection/overview#starter_model
    TfLiteTensor *output_locations =
        interpreter->tensor(interpreter->outputs()[0]);
    TfLiteTensor *output_classes =
        interpreter->tensor(interpreter->outputs()[1]);
    TfLiteTensor *output_scores =
        interpreter->tensor(interpreter->outputs()[2]);
    TfLiteTensor *output_detections =
        interpreter->tensor(interpreter->outputs()[3]);
````
