### ISSUE TITLE
Snap camera kit SDK with Mediapipe Sdk

### ISSUE THREAD

**Issue by xcelor** [google-ai-edge/mediapipe#5391]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

android

### MediaPipe version

0.10.0

### Solution

Mediapipe can't access camera while using with camera kit sdk

### Programming Language and version

Kotiln

### Describe the actual behavior

Mediapipe stops detecting gesture when snap lens open 

### Describe the expected behaviour

Both the sdk should use camera access at a same time

**Comment by kuaashish** [comment]
Hi @xcelor,

Apologies for the delayed response. We have not tested this scenario and for now we can not provide support for it. If you believe this should be a feature, please submit a new feature request using the provided [template](https://github.com/google-ai-edge/mediapipe/issues/new?assignees=&labels=type%3Afeature&projects=&template=14-feature-request-issue-template.yaml), including all necessary details, and request you to close this issue. Once raised, We will review the request internally, and if there is sufficient demand, we may implement this feature in the future.

Thank you!!
