### ISSUE TITLE
Did the Face landmark detection can tell us whether the face is swollen and unsymmetric？

### ISSUE THREAD

**Issue by joveth1** [google-ai-edge/mediapipe#5393]
### MediaPipe Solution (you are using)

Face landmark detection 

### Programming language

android

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

I'm testing this project. The examples run up successfully. I want to know is the results can tell whether the face is swollen and unsymmetric

### Will this change the current API? How?

no

### Who will benefit with this feature?

Medical practitioners

### Please specify the use cases for this feature

Showcasing the patient's injury situation

**Comment by kuaashish** [comment]
Hi @joveth1,

We believe this is out of scope section of MediaPipe face landmarker, which is primarily designed for entertainment and assistive technologies. It is not intended for making critical human life decisions or medical purposes.

For a more comprehensive understanding, please refer to our [model card](https://storage.googleapis.com/mediapipe-assets/MediaPipe%20BlazeFace%20Model%20Card%20(Short%20Range).pdf).

Thank you!!!
