### ISSUE TITLE
PoseLandmarker segmentationMask doesn't work in web

### ISSUE THREAD

**Issue by achatham** [google-ai-edge/mediapipe#5395]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

web

### Browser and version if the issue happens on browser

124.0.6367.119 (Official Build) (64-bit) (cohort: Control) 

### Programming Language and version

typescript

### MediaPipe version

tasks-vision 0.10.13

### Solution

PoseLandmarker

### Describe the actual behavior

SegmentationMask WebGLTexture not renderable

### Describe the expected behaviour

segmentationMasks[0] should render

### Standalone code/steps you may have used to try to get what you need

```shell
When using PoseLandmarker, I haven't been able to render `result.segmentationMasks[0].getAsWebGLTexture()`. I suspect there may be a bug, as I can render the results of ImageSegmenter with similar code.

I have a standalone demo at https://codepen.io/achatham/pen/BaearyK?editors=1010. It's implemented so that it can switch between ImageSegmenter (which works) and PoseLandmarker (which does not), with all of the rest of the code the same.

With PoseLandmarker, I get the console error: `Feedback loop formed between Framebuffer and active Texture.`

`result.getAsUint8Array()` et al also don't work, or produce zeros. But I'm most interested in getting the texture.

I'm able to retrieve and render the pose detections fine.
```

**Comment by schmidt-sebastian** [comment]
We will take a look.

**Comment by schmidt-sebastian** [comment]
Fix is pending review internally.
