### ISSUE TITLE
PyPI package updated without release notes, changelog, or Github release available

### ISSUE THREAD

**Issue by cchadowitz** [google-ai-edge/mediapipe#5399]
Because I use Github's Dependabot, I get notified when there is a new Mediapipe version available to install from PyPI. However, often I can't find any documentation (release notes, changelog, tag, etc) on Github to give me any idea of what the update contains or addresses. There's also no clear information as to when the release will show up on Github, so I'm left waiting to upgrade without knowing if there's a security or some other kind of serious issue resolved in the newest version.

In fact, the only reference I can find to the latest (0.10.14) version is [this comment](https://github.com/google/mediapipe/issues/5396#issuecomment-2106641680).

It would be extremely helpful to have some kind of release documentation available when a new PyPI version is released. Thanks!

**Comment by kuaashish** [comment]
Hi @cchadowitz,

Apologies for the delay in releasing version 0.10.14 on all platforms including Github as well. You can now view the [release notes](https://github.com/google/mediapipe/releases/tag/v0.10.14) on Github.

Thank you!!

**Comment by cchadowitz** [comment]
Thank you, much appreciated!

**Comment by Riztazz** [comment]
I have the same quest, seems version .18 has been released recently https://github.com/google-ai-edge/mediapipe/issues/5710#issuecomment-2456563472
Github is at version .15, additionally does that mean that GH repo is behind with fixes/commits or just release wasn't prepared for it?

**Comment by Riztazz** [comment]
I have the same quest, seems version .18 has been released recently https://github.com/google-ai-edge/mediapipe/issues/5710#issuecomment-2456563472
Github is at version .15, additionally does that mean that GH repo is behind with fixes/commits or just release wasn't prepared for it? @kuaashish

**Comment by kuaashish** [comment]
Hi @cchadowitz,

Apologies for the delay. The release notes have now been published and are available here [Release Notes v0.10.18](https://github.com/google-ai-edge/mediapipe/releases/tag/v0.10.18).

Thank you!!

**Comment by schmidt-sebastian** [comment]
We are working on streamlining our release process, but since we have a fair number of binary releases, our builds can sometimes take multiple days. The last step in our release process is publishing the GItHub release notes. While we will continue to try to limit the window between publishing the fist and the last release artifact, there will always be a window. As of now, this is working as intended.
