### ISSUE TITLE
AttributeError: module 'mediapipe.python.solutions.hands' has no attribute 'hands'

### ISSUE THREAD

**Issue by c61221** [google-ai-edge/mediapipe#5410]
I had using Spider to write python program

Has anyone had this error when importing the mediapipe library?  AttributeError: partially initialized module 'mediapipe' has no attribute 'hands'

### Standalone code/steps you may have used to try to get what you need###
import cv2
import mediapipe as mp
cap = cv2.VideoCapture(0)
mpHands = mp.solutions.hands
hands = mpHands.hands()
while True:
    ret, img = cap.read()
    if ret:
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        results = hands.process(imgRGB)
        print(results.mulit_hand_landmarks)
        cv2.imshow('img', img)             
    if cv2.waitKey(10) == ord('q'):
          break
cap.release()
cv2.destroyAllWindows()
```

**Comment by c61221** [comment]
software version
Python 3.11.9、Spyder 5.5.4
Windows 10

**Comment by kuaashish** [comment]
Hi @c61221,

After reviewing the code snippet you provided, it appears that you are using an legacy version of MediaPipe Hand Solution. We have recently launched enhanced MediaPipe Tasks APIs, which provide increased stability and functionality compared to the legacy version, and for legacy hand solution support has been completely ended. 

We strongly advise migrating to these updated APIs for Hand landmarks, as we no longer support legacy solutions. You can find the documentation for the Hand Landmarker [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker) and implementation guide for Python [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/python).

Unfortunately, aside from this, we won't be able to assist you much further.

Thank you!!
