### ISSUE TITLE
Why there are only _cpu.binarytxt file exist in my module folder after python -m pip install mediapipe

### ISSUE THREAD

**Issue by Terrywang2001** [google-ai-edge/mediapipe#5412]
### OS Platform and Distribution

Ubuntu 20.04

### Programming Language and version

Python 3.9

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

0.10.14

### Android AAR (if android)

None

### Describe the problem

python -m pip install mediapipe

### Complete Logs

I want to use the face_landmarker model on GPU. But after I installed mediapipe, it occurs to me that in /modules/face_landmark folder, the only binarytxt file is face_landmark_front_cpu.binarypb, but shouldn't there be a face_landmark_front_gpu.binarypb file if I want to use solution on GPU? If so, how can I get such file. 

Under this circumstance, I followed all the instruction from Face Landmarker Example Code: https://colab.research.google.com/github/googlesamples/mediapipe/blob/main/examples/face_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Face_Landmarker.ipynb. I copied all the necessary code and change the based_option to be the following: base_options = python.BaseOptions(model_asset_path='/absolute/path/face_landmarker.task', delegate=mp.tasks.BaseOptions.Delegate.GPU). But after running this it shows the following error:ValueError: The model is not a valid Flatbuffer buffer. How can I fix this?

**Comment by Terrywang2001** [comment]
The following is my complete code: 
import numpy as np
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

from typing import Tuple, Union
import math
import cv2
import numpy as np

MARGIN = 10  # pixels
ROW_SIZE = 10  # pixels
FONT_SIZE = 1
FONT_THICKNESS = 1
TEXT_COLOR = (255, 0, 0)  # red


def _normalized_to_pixel_coordinates(
    normalized_x: float, normalized_y: float, image_width: int,
    image_height: int) -> Union[None, Tuple[int, int]]:
  """Converts normalized value pair to pixel coordinates."""

  # Checks if the float value is between 0 and 1.
  def is_valid_normalized_value(value: float) -> bool:
    return (value > 0 or math.isclose(0, value)) and (value < 1 or
                                                      math.isclose(1, value))

  if not (is_valid_normalized_value(normalized_x) and
          is_valid_normalized_value(normalized_y)):
    # TODO: Draw coordinates even if it's outside of the image bounds.
    return None
  x_px = min(math.floor(normalized_x * image_width), image_width - 1)
  y_px = min(math.floor(normalized_y * image_height), image_height - 1)
  return x_px, y_px


def visualize(
    image,
    detection_result
) -> np.ndarray:
  """Draws bounding boxes and keypoints on the input image and return it.
  Args:
    image: The input RGB image.
    detection_result: The list of all "Detection" entities to be visualize.
  Returns:
    Image with bounding boxes.
  """
  annotated_image = image.copy()
  height, width, _ = image.shape

  for detection in detection_result.detections:
    # Draw bounding_box
    bbox = detection.bounding_box
    start_point = bbox.origin_x, bbox.origin_y
    end_point = bbox.origin_x + bbox.width, bbox.origin_y + bbox.height
    cv2.rectangle(annotated_image, start_point, end_point, TEXT_COLOR, 3)

    # Draw keypoints
    for keypoint in detection.keypoints:
      keypoint_px = _normalized_to_pixel_coordinates(keypoint.x, keypoint.y,
                                                     width, height)
      color, thickness, radius = (0, 255, 0), 2, 2
      cv2.circle(annotated_image, keypoint_px, thickness, color, radius)

    # Draw label and score
    category = detection.categories[0]
    category_name = category.category_name
    category_name = '' if category_name is None else category_name
    probability = round(category.score, 2)
    result_text = category_name + ' (' + str(probability) + ')'
    text_location = (MARGIN + bbox.origin_x,
                     MARGIN + ROW_SIZE + bbox.origin_y)
    cv2.putText(annotated_image, result_text, text_location, cv2.FONT_HERSHEY_PLAIN,
                FONT_SIZE, TEXT_COLOR, FONT_THICKNESS)

  return annotated_image

# STEP 2: Create an FaceDetector object.
base_options = python.BaseOptions(model_asset_path='/absolute/path/face_landmarker.task', delegate=mp.tasks.BaseOptions.Delegate.GPU)
options = vision.FaceDetectorOptions(base_options=base_options)
detector = vision.FaceDetector.create_from_options(options)

# STEP 3: Load the input image.
image = mp.Image.create_from_file('360_F_319108213_MoLZZt5WTXq6NpdG1FbCbyCtDStlSVBf.jpg')

# STEP 4: Detect faces in the input image.
detection_result = detector.detect(image)

# STEP 5: Process the detection result. In this case, visualize it.
image_copy = np.copy(image.numpy_view())
annotated_image = visualize(image_copy, detection_result)
rgb_annotated_image = cv2.cvtColor(annotated_image, cv2.COLOR_BGR2RGB)
cv2.imshow(rgb_annotated_image)

**Comment by kuaashish** [comment]
Hi @Terrywang2001,

It must support the GPU in Ubuntu, To better understand and address the issue, please provide the following:

- The version of MediaPipe you are using.
- The complete standalone code you are using.
- The full error logs.

Thank you!!

**Comment by Terrywang2001** [comment]
the following is the screenshot of mediapipe/modules/face_landmark folder right after I run "python -m pip install mediapipe":
![2024-05-17 15-16-33 的屏幕截图](https://github.com/google-ai-edge/mediapipe/assets/92125429/720004b8-cfe2-43ba-aad3-f4088549f923)
I don't know why there's no gpu.binarypb file inside this folder, and the same happened for all the folders in the module folder.
![2024-05-17 17-15-14 的屏幕截图](https://github.com/google-ai-edge/mediapipe/assets/92125429/c43ead64-814b-4d0e-8534-f8908f5dde96).
But the gpu folder still exists.
![2024-05-17 17-17-39 的屏幕截图](https://github.com/google-ai-edge/mediapipe/assets/92125429/fd471a02-3f64-4c2d-90de-39b04cb5d1f0)
About the ValueError: The model is not a valid Flatbuffer buffer. I don't know why but it just resolved lol.

**Comment by Terrywang2001** [comment]
So the only code I used is 'python -m pip install mediapipe'. I installed this through my terminal, and when the download finished, only the cpu.binarytxt appeared, but not gpu.binarytxt.

**Comment by kuaashish** [comment]
Hi @Terrywang2001,

Could you please test this code using a GPU as the delegate? It works fine for me, and I would appreciate knowing if it works for you as well.

**Visualization utilities**

```
from mediapipe import solutions
from mediapipe.framework.formats import landmark_pb2
import numpy as np
import matplotlib.pyplot as plt


def draw_landmarks_on_image(rgb_image, detection_result):
  face_landmarks_list = detection_result.face_landmarks
  annotated_image = np.copy(rgb_image)

  # Loop through the detected faces to visualize.
  for idx in range(len(face_landmarks_list)):
    face_landmarks = face_landmarks_list[idx]

    # Draw the face landmarks.
    face_landmarks_proto = landmark_pb2.NormalizedLandmarkList()
    face_landmarks_proto.landmark.extend([
      landmark_pb2.NormalizedLandmark(x=landmark.x, y=landmark.y, z=landmark.z) for landmark in face_landmarks
    ])

    solutions.drawing_utils.draw_landmarks(
        image=annotated_image,
        landmark_list=face_landmarks_proto,
        connections=mp.solutions.face_mesh.FACEMESH_TESSELATION,
        landmark_drawing_spec=None,
        connection_drawing_spec=mp.solutions.drawing_styles
        .get_default_face_mesh_tesselation_style())
    solutions.drawing_utils.draw_landmarks(
        image=annotated_image,
        landmark_list=face_landmarks_proto,
        connections=mp.solutions.face_mesh.FACEMESH_CONTOURS,
        landmark_drawing_spec=None,
        connection_drawing_spec=mp.solutions.drawing_styles
        .get_default_face_mesh_contours_style())
    solutions.drawing_utils.draw_landmarks(
        image=annotated_image,
        landmark_list=face_landmarks_proto,
        connections=mp.solutions.face_mesh.FACEMESH_IRISES,
          landmark_drawing_spec=None,
          connection_drawing_spec=mp.solutions.drawing_styles
          .get_default_face_mesh_iris_connections_style())

  return annotated_image

def plot_face_blendshapes_bar_graph(face_blendshapes):
  # Extract the face blendshapes category names and scores.
  face_blendshapes_names = [face_blendshapes_category.category_name for face_blendshapes_category in face_blendshapes]
  face_blendshapes_scores = [face_blendshapes_category.score for face_blendshapes_category in face_blendshapes]
  # The blendshapes are ordered in decreasing score value.
  face_blendshapes_ranks = range(len(face_blendshapes_names))

  fig, ax = plt.subplots(figsize=(12, 12))
  bar = ax.barh(face_blendshapes_ranks, face_blendshapes_scores, label=[str(x) for x in face_blendshapes_ranks])
  ax.set_yticks(face_blendshapes_ranks, face_blendshapes_names)
  ax.invert_yaxis()

  # Label each bar with values
  for score, patch in zip(face_blendshapes_scores, bar.patches):
    plt.text(patch.get_x() + patch.get_width(), patch.get_y(), f"{score:.4f}", va="top")

  ax.set_xlabel('Score')
  ax.set_title("Face Blendshapes")
  plt.tight_layout()
  plt.show()

```

**Running inference and visualizing the results**


```
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import cv2

# STEP 2: Create an FaceLandmarker object.
base_options = python.BaseOptions(model_asset_path='/Users/kuaashish/Downloads/face_landmarker.task', delegate=mp.tasks.BaseOptions.Delegate.GPU)
options = vision.FaceLandmarkerOptions(base_options=base_options,
                                       output_face_blendshapes=True,
                                       output_facial_transformation_matrixes=True,
                                       num_faces=1)
detector = vision.FaceLandmarker.create_from_options(options)

# STEP 3: Load the input image.
image = mp.Image.create_from_file("/Users/kuaashish/Downloads/color_sketch.jpg")

# STEP 4: Detect face landmarks from the input image.
detection_result = detector.detect(image)

# STEP 5: Process the detection result. In this case, visualize it.
annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)
cv2.imshow("Annotated_Image",cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))
```

Please adjust the task file path according to your OS and update the input image path accordingly.

Thank you!!

**Comment by Terrywang2001** [comment]
![图片](https://github.com/google-ai-edge/mediapipe/assets/92125429/78e4d920-923e-4a63-85f0-20331685b6ad)
It works.

**Comment by Terrywang2001** [comment]
But still only cpu.binarytxt file exists.
recent:///d2581fa89ec054b27440152e66545567

**Comment by kuaashish** [comment]
Hi @Terrywang2001,

We are currently unaware of this file. Could you please provide the specific use case for this file? Understanding your requirements will help us address the issue more effectively. If your query pertains to running the face landmarker on GPU, it is functioning correctly based on my tests and your comments.

Thank you!!

**Comment by Terrywang2001** [comment]
Oh it's because I want to use the prebuilt solution. So in the file "face_detection.py", at the beginning of the file, there are two lines: _SHORT_RANGE_GRAPH_FILE_PATH = 'mediapipe/modules/face_detection/face_detection_short_range_cpu.binarypb'
_FULL_RANGE_GRAPH_FILE_PATH = 'mediapipe/modules/face_detection/face_detection_full_range_cpu.binarypb'. And in it's init def, there's a line about the binary graph path: binary_graph_path = _FULL_RANGE_GRAPH_FILE_PATH if model_selection == 1 else _SHORT_RANGE_GRAPH_FILE_PATH. So I want to use GPU for the solution, and I thought there should be some file like face_detection_gpu.binarytxt.

**Comment by kuaashish** [comment]
Hi @Terrywang2001,

It appears you are still using our legacy face detection model instead of the new one, so there is no option to switch between the short-range and full-range models. We recommend using our new Task Face Landmarker API as example provided above. If you are missing a specific file, it may be because you need to build from source to obtain the gpu.binarypb file. You can try using a command similar to the one below:


`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 //mediapipe/examples/desktop/face_detection:face_detection_gpu`

Thank you!!
