### ISSUE TITLE
Rendered videos lagging on MacOS, getting this: INFO: Created TensorFlow Lite XNNPACK delegate for CPU

### ISSUE THREAD

**Issue by Vishruth23** [google-ai-edge/mediapipe#5417]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

MacOS

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose Estimation

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

Rendered video extremely laggy, huge drop in FPS, I'm getting this: INFO: Created TensorFlow Lite XNNPACK delegate for CPU

### Describe the expected behaviour

Rendered video should be smooth

### Standalone code/steps you may have used to try to get what you need

```shell
import cv2
import mediapipe as mp
import time

cap = cv2.VideoCapture("PE-testcase2.mp4") # or VideoCapture(0)
mpPose = mp.solutions.pose
mpDraw = mp.solutions.drawing_utils

while True:
    success, image = cap.read()
    # cv2.imshow("Image", image)

    if not success:
        print("Ignoring empty camera frame.")
        continue

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

    with mpPose.Pose(model_complexity=1, min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:

        imgRGB = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        imgRGB.flags.writeable = False

        results = pose.process(imgRGB)

        imgRGB.flags.writeable = True
        imgRGB = cv2.cvtColor(imgRGB, cv2.COLOR_RGB2BGR)

        if results.pose_landmarks:
            mpDraw.draw_landmarks(imgRGB, results.pose_landmarks, mpPose.POSE_CONNECTIONS)
        
        cv2.imshow("Image", imgRGB)



cap.release()
cv2.destroyAllWindows()
```

**Comment by kuaashish** [comment]
Hi @Vishruth23,

After reviewing the provided standalone code, it appears that you are currently using the outdated pose solution, which is no longer maintained, and we have ceased support for it. This functionality has been integrated into the new Pose Landmarker Task API, detailed [here](https://developers.google.com/mediapipe/solutions/guide#legacy).

We encourage you to explore the features of our updated Pose Landmarker Task API and suggest replacing the legacy Pose with the new Pose Landmarker. The new solution offers improved performance and additional functionality compared to the legacy pose solution. You can find the guide for the new Pose Landmarker [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker), along with specific instructions for implementation in the Python platform provided [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python). Additionally, a corresponding example Colab notebook is available for reference [here](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/pose_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Pose_Landmarker.ipynb).

Please report any observed behavior, ensuring to check if similar issues persist in the upgraded task API. Unfortunately, beyond this, there is limited action we can take to address the specific issue you are facing.

Thank you!!
