### ISSUE TITLE
Unable to find mediapipe/framework/calculator.pb.h file

### ISSUE THREAD

**Issue by Terrywang2001** [google-ai-edge/mediapipe#5419]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Ubuntu 20.04

### Programming Language and version

C++

### Solution

Tool: text_to_binary_graph

### Describe the actual behavior

I couldn't find mediapipe/framework/calculator.pb.h file everywhere

### Describe the expected behaviour

there should be a mediapipe/framework/calculator.pb.h file somewhere in mediapipe folder

### Standalone code/steps you may have used to try to get what you need

```shell
When I try to use the tool text_to_binary_graph to create face_landmark_front_gpu.binarypb from face_landmark_front_gpu.pbtxt, the file calculator.pb.h is just missing. So where can I find that file or create that file?
```

**Comment by kuaashish** [comment]
Hi @Terrywang2001,

Could you please provide the exact steps you are following from our documentation to help us understand and reproduce the issue?

Thank you!!

**Comment by Terrywang2001** [comment]
So I've downloaded the whole mediapipe repo. Then I opened it using vscode. I opened and ran text_to_binary_graph.cc, but from '#include "mediapipe/framework/calculator.pb.h"', it just told me 'unable to open the source file', and I searched the name: 'calculator.pb.h' throughout the mediapipe folder, but I just can't find it.

**Comment by kuaashish** [comment]
Hi @Terrywang2001,

Please let us know if you still need assistance with this issue or if it has been resolved on your end. It appears similar to the issue discussed in https://github.com/google-ai-edge/mediapipe/issues/5412, which has been closed without an active response.

Thank you!!
