### ISSUE TITLE
How can I get the 6dof pose of the hand?

### ISSUE THREAD

**Issue by hahamini** [google-ai-edge/mediapipe#5424]
Since a canonical model is provided for facial landmark recognition, a 6dof pose can be obtained through the detected landmarks and the PnP algorithm.

However, I cannot find a standard model for the hand in the hand landmark detection task.  

Instead, hand_world_landmark is provided in this task, but it lacks a definition of world coordinates.  

**I want to get the 6dof pose of the hand in the camera coordinate.**  

What should I do?

**Comment by kuaashish** [comment]
Hi @hahamini,

We could not clearly understand the issue. Could you please provide more details?

Thank you!!
