### ISSUE TITLE
How I can use GPU mediapipe python

### ISSUE THREAD

**Issue by FunnyWii** [google-ai-edge/mediapipe#5426]
### OS Platform and Distribution

20.04

### Programming Language and version

Python

### Android AAR (if android)

None

### Describe the problem

How I can use GPU mediapipe python? 

### Complete Logs

```shell
I can run mediapipe via pip install in Python env.

But it can be seen the `INFO: Created TensorFlow Lite XNNPACK delegate for CPU.`

How can I utilize my GPU? My platform is Jetson AGX Orin.

Any instruction?

Thanks.
```

**Comment by kuaashish** [comment]
HI @FunnyWii,

Currently, GPU support is available only on regular Linux and macOS (both Intel and Silicon). We do not support GPU on Jetson AGX Orin and other platforms. 

To use the GPU on supported platforms, install the latest version of the MediaPipe package (0.10.14) with the command:

`pip install mediapipe`

Then, specify the GPU as the delegate in your code, as shown below for example Gesture Recognizer: 

`base_options = python.BaseOptions(model_asset_path='gesture_recognizer.task', delegate=python.BaseOptions.Delegate.GPU)`

This ensures the example runs on the GPU.

Thank you!!

**Comment by FunnyWii** [comment]
> HI @FunnyWii,
> 
> Currently, GPU support is available only on regular Linux and macOS (both Intel and Silicon). We do not support GPU on Jetson AGX Orin and other platforms.
> 
> To use the GPU on supported platforms, install the latest version of the MediaPipe package (0.10.14) with the command:
> 
> `pip install mediapipe`
> 
> Then, specify the GPU as the delegate in your code, as shown below for example Gesture Recognizer:
> 
> `base_options = python.BaseOptions(model_asset_path='gesture_recognizer.task', delegate=python.BaseOptions.Delegate.GPU)`
> 
> This ensures the example runs on the GPU.
> 
> Thank you!!

Thanks for your reply.

Currently I've changed the platform into x86 Ubuntu.

```
import cv2
import mediapipe as mp
import Utils
import time
import socket

mp_holistic = mp.solutions.holistic
holistic = mp_holistic.Holistic()
mp_drawing = mp.solutions.drawing_utils

while cap.isOpened():
    success, image = cap.read()
    if not success:
        break
    start_time = time.time()


    image = cv2.resize(image, (1280, 720), interpolation=cv2.INTER_AREA)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image.flags.writeable = False
    results = holistic.process(image)

    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

  if results.pose_landmarks:
        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS)
    if results.left_hand_landmarks:
        mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS)
    if results.right_hand_landmarks:
        mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS)
```

My codes is shown below, but I don't know where to add the code you mentioned:`base_options = python.BaseOptions(model_asset_path='gesture_recognizer.task', delegate=python.BaseOptions.Delegate.GPU)`

**Comment by kuaashish** [comment]
Hi @FunnyWii,

The standalone code you shared uses the legacy holistic solution, which does not support GPU via pip. Support for legacy solutions has ended as they are now part of our new Task API. You can find the documentation [here](https://ai.google.dev/edge/mediapipe/solutions/guide).

The holistic solution is now part of the Holistic Landmarker Task API. However, there is a known [issue](https://github.com/google-ai-edge/mediapipe/issues/5181) with GPU support for the new Holistic Landmarker Task API, so GPU can not be used with it. GPU support is available for other Task APIs. For more details on how to use GPU with Python, see this [thread](https://github.com/google-ai-edge/mediapipe/issues/4988).

Thank you!!

**Comment by FunnyWii** [comment]
> Hi @FunnyWii,
> 
> The standalone code you shared uses the legacy holistic solution, which does not support GPU via pip. Support for legacy solutions has ended as they are now part of our new Task API. You can find the documentation [here](https://ai.google.dev/edge/mediapipe/solutions/guide).
> 
> The holistic solution is now part of the Holistic Landmarker Task API. However, there is a known [issue](https://github.com/google-ai-edge/mediapipe/issues/5181) with GPU support for the new Holistic Landmarker Task API, so GPU can not be used with it. GPU support is available for other Task APIs. For more details on how to use GPU with Python, see this [thread](https://github.com/google-ai-edge/mediapipe/issues/4988).
> 
> Thank you!!

https://colab.research.google.com/github/googlesamples/mediapipe/blob/main/examples/pose_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Pose_Landmarker.ipynb#scrollTo=OMjuVQiDYJKF
https://colab.research.google.com/github/googlesamples/mediapipe/blob/main/examples/hand_landmarker/python/hand_landmarker.ipynb

Thank you!

I see the new solution for both Hand & Pose landmarker.

As the Holistic detection can't work with GPU, can I combine above codes in colab into one `.py` file  and input a same image to conduct the both Hand & Pose landmarker using GPU?

**Comment by kuaashish** [comment]
Hi @FunnyWii,

We have not tested this scenario and are unsure if it will work. We recommend using the CPU version of the Holistic Landmarker for now. We will inform you once we receive any updates about a fix.

Thank you!!

**Comment by silverline-art** [comment]
?? python.BaseOptions.Delegate.GPU
sorry but i cant find it anywhere  (U-U)
