### ISSUE TITLE
DIfference in Android and Python face landmarker documentation

### ISSUE THREAD

**Issue by philiprkk** [google-ai-edge/mediapipe#5427]
### Clear description

Why does the Python documentation for live stream mode say: 

"When running in the live stream mode, the Face Landmarker task returns immediately and doesn’t block the current thread. It will invoke the result listener with the detection result every time it finishes processing an input frame. If the detection function is called when the Face Landmarker task is busy processing another frame, the task will ignore the new input frame."

But the Android version only says: 

"When running in the live stream mode, the Face Landmarker task returns immediately and doesn’t block the current thread. It will invoke the result listener with the detection result every time it finishes processing an input frame."
 
Does the Android version not ignore frames when the solver is currently processing? It does seem that way sometimes in my experience.

### Correct links

https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker/android https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker/python

**Comment by kuaashish** [comment]
Hi @philiprkk,

We believe this behavior applies across all platforms. You can see an example [input](https://github.com/google-ai-edge/mediapipe/issues/5180#issuecomment-1972842611) from our team. However, please allow us some time to discuss with the team and confirm once.

Thank you!!

**Comment by kuaashish** [comment]
Hi @philiprkk,

We have received confirmation from the team that this behavior is expected. The first frame is ignored in Android, similar to Python and JavaScript, indicating it occurs across all platforms.

Thank you!!
