### ISSUE TITLE
How can I render a image avatar using face landmarker detection result?

### ISSUE THREAD

**Issue by ly15927086342** [google-ai-edge/mediapipe#5436]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Mac M1

### MediaPipe version

0.10.12

### Solution

face landmarker detection

### Programming Language and version

web

### Describe the actual behavior

Now I'm using @mediapipe/tasks-vision DrawingUtils to render grid as the codepen example.

### Describe the expected behaviour

I wonder other render effect, such as a cartoon avatar.

### Standalone code/steps you may have used to try to get what you need

```shell
I notice the official page "https://mediapipe-studio.webapps.google.com/studio/demo/face_landmarker" has provide a choice about "display mode", is there any example code to teach me how to set it in my own codes.
I hope more interesting use about face landmarker detection model.
Hoping for your reply!
```

**Comment by kuaashish** [comment]
Hi @ly15927086342,

Currently, customization of our Avatar render effect is not possible, as this feature is not open-sourced. Additionally, we do not have examples available on other platforms. If you are interested in this feature, we recommend raising a new feature [request](https://github.com/google-ai-edge/mediapipe/issues/new/choose) with all the relevant details. Based on the discussion and demand, we may implement this in the future.

Thank you!!
