### ISSUE TITLE
how to get procrustes_landmark_basis and canonical_mesh in face_geometry

### ISSUE THREAD

**Issue by ly0303521** [google-ai-edge/mediapipe#5445]
Hello, mediapipe is really a gread job and very useful. 
I'm confused about  how to how to get procrustes_landmark_basis and canonical_mesh in face_geometry ?
Do you get them by experiment ?

**Comment by kuaashish** [comment]
Hi @1278057578,

We are revisiting to older issues, Could you please let us know if you are still seeking a resolution for this issue, or if it has been resolved on your end?

Thank you!!
