### ISSUE TITLE
How to use Delegate for CPU and GPU

### ISSUE THREAD

**Issue by nskaiser** [google-ai-edge/mediapipe#5447]
Hello, I am looking for documentation or a better understanding on how the delegate works for GPU and CPU.  e.g.

  gestureRecognizer = await GestureRecognizer.createFromOptions(vision, {
    baseOptions: {
      modelAssetPath:
        "https://storage.googleapis.com/mediapipe-models/gesture_recognizer/gesture_recognizer/float16/1/gesture_recognizer.task",
      delegate: "GPU"
    },
  });

What I am noticing is that on some machines (all with a GPU) if you use delgate of CPU the models load very quickly. If you use GPU, it takes around 30 seconds (using face, hands, pose) to load the models.  But once loaded, CPU is slightly reduced and GPU is engaged.

If you don't pass a delegate, it seems to always default to CPU (tested on Macs w/ M2 and M3 processors).

What is the expected behavior of not passing a delegate? Should it use the best option? Would be great to have more info here and understand why load time can be so slow when forcing GPU.

Thanks.

**Comment by kuaashish** [comment]
Hi @nskaiser,

Both the CPU and GPU are used for the GPU delegate. To check if the GPU is being used, compare the model's performance. Models that use the GPU should be significantly faster. For more details, visit https://github.com/google/mediapipe/issues/4711.

Thank you!!

**Comment by nskaiser** [comment]
Thanks. Can you explain more on what this actually does?  And what happens if I don't pass any delegate? I'm trying to better understand this.  I'd say from my experience using GPU makes the model run faster, but it also makes it load much slower.  I saw #4711 but it didn't answer these questions either. Thanks.

**Comment by kuaashish** [comment]
Hi @nskaiser,

By default, the system will use the CPU version. If the system supports a GPU and it is available, the GPU will be used instead. 

Regarding your second query, could you please provide more details or raise a new issue with complete information? Please close the current issue and that will make it easier for community members to search and address the issue.

Thank you!!

**Comment by nskaiser** [comment]
Thanks, I will do that!  But one last question to just confirm here... Let's say I am on a PC with an available GPU.  If I pass delegate=GPU , that should technically be the same as if not passing a delegate at all because the system will see I have a GPU available and try that.  Is that correct?       
Conversely, what if I pass delegate=GPU but a user w/ an unavailable GPU is running the app? Will the system detect this and revert to CPU?
So what is best practice here if you just want best performance across all systems, GPU or not.  To not pass a delegate?
Thanks again.

**Comment by kuaashish** [comment]
Hi @nskaiser,

Yes, you are correct. The performance will be the same regardless of whether you pass the delegate or not. If a GPU is available, it will be used by default, so there should be no concern.

Thank you!!
