### ISSUE TITLE
vision_wasm_internal.wasm loads fast on first attempt, but taking more time on next refresh.

### ISSUE THREAD

**Issue by NandanModtech** [google-ai-edge/mediapipe#5448]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 11

### MediaPipe Tasks SDK version

mediapipe/tasks-vision@0.10.14

### Task name (e.g. Image classification, Gesture recognition etc.)

Face Landmarker & Hand Landmarker

### Programming Language and version (e.g. C++, Python, Java)

Javascript

### Describe the actual behavior

wasm file taking more time load on second refresh.

### Describe the expected behaviour

wasm file should load quickly.

### Standalone code/steps you may have used to try to get what you need

```shell
None
```

**Comment by NandanModtech** [comment]
![image](https://github.com/google-ai-edge/mediapipe/assets/158842030/cd95291c-862a-4dec-9dae-9918940f886d)
You can check in above image.

**Comment by kuaashish** [comment]
Hi @NandanModtech,

I apologize for the delayed response. Could you please confirm if this issue has been resolved on your end, or if you still require assistance from us?

Thank you!!
