### ISSUE TITLE
Mediapipe lagging behind OpenCV video stream severely on Linux

### ISSUE THREAD

**Issue by Crazypersonalph** [google-ai-edge/mediapipe#5453]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Arch Linux

### Programming Language and version

Python

### MediaPipe version

Latest

### Solution

Pose

### Describe the actual behavior

Mediapipe lags behind OpenCV up to 7 seconds behind on capable hardware

### Describe the expected behaviour

Mediapipe stays constistenly with OpenCV

### Standalone code/steps you may have used to try to get what you need

```shell
https://github.com/Crazypersonalph/nerftracker.git
```

**Comment by Crazypersonalph** [comment]
I should add it was lagging behind with Cython

**Comment by matanox** [comment]
Can you provide reproducing code?

**Comment by kuaashish** [comment]
Hi @Crazypersonalph,

Could you please provide the code to reproduce the issue so that we can better understand it from our end?

Thank you!!

**Comment by ueihghnurthnirt** [comment]
Got same energy when install same system from windows to Linux.But for me,with USB Camera,speed is unchanged. only get lagging behind when do it with ".mp4" video or rtsp.

**Comment by ueihghnurthnirt** [comment]
> Got same energy when install same system from windows to Linux.But for me,with USB Camera,speed is unchanged. only get lagging behind when do it with ".mp4" video or rtsp.

Problem seem to be related to opencv reading frame speed. Affecting not also rtsp but even in .mp4 file or .avi. should check hardware then network then opencv.

**Comment by kuaashish** [comment]
Hi @Crazypersonalph,

Sorry for the delay in responding. Could you please let us know if this issue is still ongoing or if it has been resolved on your end?

Thank you!!

**Comment by Crazypersonalph** [comment]
Sorry about the absence of responses,
I am not actively working on the project concerning mediation anymore, so I do not think this issue applies to me anymore.

Kind Regards
