### ISSUE TITLE
How to elevate the extracted 2D coordinates to 3D?

### ISSUE THREAD

**Issue by caochengchen** [google-ai-edge/mediapipe#5456]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

How to elevate the extracted 2D coordinates to 3D?

### MediaPipe Tasks SDK version

How to elevate the extracted 2D coordinates to 3D?

### Task name (e.g. Image classification, Gesture recognition etc.)

How to elevate the extracted 2D coordinates to 3D?

### Programming Language and version (e.g. C++, Python, Java)

How to elevate the extracted 2D coordinates to 3D?

### Describe the actual behavior

How to elevate the extracted 2D coordinates to 3D?

### Describe the expected behaviour

How to elevate the extracted 2D coordinates to 3D?

### Standalone code/steps you may have used to try to get what you need

```shell
How to elevate the extracted 2D coordinates to 3D?
```

**Comment by waterself** [comment]
can you let me know about your OS, language(python), solution(ex. pose landmark)?

**Comment by caochengchen** [comment]
> can you let me know about your OS, language(python), solution(ex. pose landmark)?你能告诉我你的操作系统、语言（python）、解决方案（例如姿势地标）吗？

I use the Python programming language and the Windows operating system. Of course, I can also use the Linux operating system

**Comment by waterself** [comment]
@caochengchen thanks for your reply. 
for example, pose landmark.

Fisrt,how to get detect result,  checkout link
https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker/python?_gl=1*1lvu6k6*_up*MQ..*_ga*NTQwNzE2NzcxLjE3MTc0NzA2MDU.*_ga_P1DBVKWT6V*MTcxNzQ3MDYwNS4xLjAuMTcxNzQ3MDYwNS4wLjAuMTU4MDE1NzA5NA..#image_2 

pose landmark detect result contained
pose landmark, world pose landmark, segmentation mask.
checkout this linkhttps://ai.google.dev/edge/api/mediapipe/python/mp/tasks/vision/PoseLandmarkerResult?_gl=1*24yvac*_up*MQ..*_ga*MTczODE3MDIwLjE3MTc0NzA4ODU.*_ga_P1DBVKWT6V*MTcxNzQ3MDg4NS4xLjAuMTcxNzQ3MDg4NS4wLjAuMjEwNzI5MDU3OA.. 

both landmark has x, y, z coordinate.
