### ISSUE TITLE
Hand Tracking index 

### ISSUE THREAD

**Issue by linahourieh** [google-ai-edge/mediapipe#5458]
### MediaPipe Solution (you are using)

task 

### Programming language

Python

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

I would like to ask if Mediapipe offers a feature in the output object, that indicates the tracking of a specific hand, for example: frame 1, tracking_index : 0, hand: left.......frame 40: no hands detected...frame 76, tracking_index : 0, hand: Right

### Who will benefit with this feature?

People who will need to tracking info not just landmarks

### Please specify the use cases for this feature

for example, i have a video of 2 people performing hand tasks, i would like to track index associated with a certain hand

**Comment by kuaashish** [comment]
Hi @linahourieh,

Could you please provide more details about this feature so we can highlight the request with our team?

Thank you!!
