### ISSUE TITLE
Installation with pip or according to documentation?

### ISSUE THREAD

**Issue by ChristianNSchmitz** [google-ai-edge/mediapipe#5463]
### Clear description

Dear developers, sorry for a beginners question. We would like to use mediapipe on a Ubuntu system and used to "pip install mediapipe" for the installation of the legacy version.  However, recently the mediapipe team updated the installation documentation with different compiling steps (https://ai.google.dev/edge/mediapipe/framework/getting_started/python_framework). Are both approaches still valid or would you recommend one over the other?

**Comment by kuaashish** [comment]
Hi @ChristianNSchmitz,

We recommend using MediaPipe through the Pip package. The documentation you referred to (https://ai.google.dev/edge/mediapipe/framework/getting_started/python_framework) is older one. While both approaches are still valid, we cannot guarantee the alternative method as it requires additional dependencies, making the build more complex compared to using Pip.

For now, please install the package via Pip. Additionally, we now support Python 3.12 in the recent release, so the supported Python versions range from 3.9 to 3.12. You can find this information in our updated documentation [here](https://ai.google.dev/edge/mediapipe/solutions/setup_python#supported_platforms_and_versions).

Thank you!!
