### ISSUE TITLE
face mesh problems

### ISSUE THREAD

**Issue by xiaohaipeng** [google-ai-edge/mediapipe#5465]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

linux

### MediaPipe Tasks SDK version

0.10.14

### Task name (e.g. Image classification, Gesture recognition etc.)

face mesh

### Programming Language and version (e.g. C++, Python, Java)

python

### Describe the actual behavior

for infer faster

### Describe the expected behaviour

batch infer or multiprocessing

### Standalone code/steps you may have used to try to get what you need

```shell
hi,i am using mp_facemesh.FaceMesh.process() for  infer.though it is very fast,about 0.005s for one infer,but i want it faster.i tried two ways:

1) i want to use mediapipe/modules/face_landmark/face_landmark.tflite for batch infer,but found the .tflite dont support batchsize >1. can you provide one tflite model to support dynamic batchsize

2）i want to use multiprocessing.pool to speed,but found ,
 when in every thread, init one new object of mediapipe.solutions.face_mesh ,and face_mesh.close() to release ,i found the speed decrease.

please help me to check it,thank you
```

**Comment by kuaashish** [comment]
Hi @xiaohaipeng,

It appears that you are currently using the legacy facemesh solution. We would like to inform you that the face mesh functionality is now part of the Face Landmarker Task API, as outlined in the [documentation](https://developers.google.com/mediapipe/solutions/guide#legacy). This API serves as a superset of the facemesh solution and offers easier adoption across all platforms with ongoing maintenance.

However, support for the legacy face mesh solution has been completely discontinued for all upgraded solutions as well, as detailed in the same [page](https://developers.google.com/mediapipe/solutions/guide#legacy). While the GitHub source codes and NPM packages for the legacy solution will remain available, But we will not be providing support for them.

We recommend exploring our new Face Landmarker and referring to the overview documentation available on the [page](https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker). For implementation on Python, please follow the Python Setup guide provided [here](https://ai.google.dev/edge/mediapipe/solutions/setup_python) and Colab example you can find [here](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/face_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Face_Landmarker.ipynb)

Also, We kindly request you to report any similar behavior if observed in the upgraded solution.

Thank you!!
