### ISSUE TITLE
face detaction and sprated image's in particular personal user 

### ISSUE THREAD

**Issue by DhruvGagani24** [google-ai-edge/mediapipe#5467]
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1717738546.795958   23537 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1717738546.923366   23583 gl_context.cc:357] GL version: 3.0 (OpenGL ES 3.0 Mesa 23.2.1-1ubuntu3.1~22.04.2), renderer: D3D12 (Intel(R) UHD Graphics)
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1717738546.944614   23575 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

**Comment by kuaashish** [comment]
Hi @DhruvGagani24,

Could you please provide more details, including the complete standalone code you are using, along with the following information:

- OS information
- Python version
- MediaPipe version

You can use [this ](https://github.com/google-ai-edge/mediapipe/issues/new?assignees=&labels=type%3Asupport&projects=&template=12-studio-issue-template.yaml)template to provide these details, This will help us diagnose the issue more effectively.

Thank you!!

**Comment by DhruvGagani24** [comment]
Hi @kuaashish 

os version => 22.04 LTS
Python Version => 3.11.12
MediaPipe version => 0.10.14
