### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by MassPig** [google-ai-edge/mediapipe#5469]
Hello,

I would like to use Figure 4 from https://github.com/google-ai-edge/mediapipe/blob/master/docs/solutions/pose.md in my Bachelor thesis. Is this possible w.r.t. copyright?

Thanks

**Comment by kuaashish** [comment]
Hi @MassPig,

We believe that using the figures should not result in any copyright issues. For more information, please refer to our [license](https://github.com/google-ai-edge/mediapipe/blob/master/LICENSE) terms and conditions.

Thank you!!
