### ISSUE TITLE
Does any model supports multi language support in text embedding?

### ISSUE THREAD

**Issue by raghavbansal27** [google-ai-edge/mediapipe#5473]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Win 11

### Task name (e.g. Image classification, Gesture recognition etc.)

Text Embedding

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

Universal Sentence Encoder model supports only english

### Describe the expected behaviour

Some mediapipe tflite model must support multi language

### Standalone code/steps you may have used to try to get what you need

```shell
https://ai.google.dev/edge/mediapipe/solutions/text/text_embedder#models

this text embedder model supports only english, is there any multilingual text embedder model available which supports chinese, japanese, korean also.
```

**Comment by kuaashish** [comment]
Hi @raghavbansal27,

Could you please verify once, We believe the Universal Sentence Encoder supports multiple languages such as English, Spanish, French, German, Italian, Dutch, Portuguese, Chinese (Simplified and Traditional), Japanese, Korean, Arabic, and Russian? Additionally, could you try out our MediaPipe [demo](https://mediapipe-studio.webapps.google.com/studio/demo/text_embedder) to confirm?

Thank you!!

**Comment by raghavbansal27** [comment]
@kuaashish Please check the below example-

Chinese (Simplified)- 今天是美好的一天  
English- Today is a beautiful day
Korean- 화창한 날입니다

Chinese (Simplified)- 我有很多工作要做  
English- i have a lot of work to do
Korean- 나는 할 일이 많다

Chinese- Embedding cosine similarity: 1
English- Embedding cosine similarity: 0.8597
Korean- Embedding cosine similarity: 0.9965

For languages other than English, it always ouputs cosine similarity ~1

**Comment by kuaashish** [comment]
Hi @raghavbansal27,

We believe the bert_embedder provides similar cosine similarity for other languages as well. We have created a gist for [English](https://colab.sandbox.google.com/gist/kuaashish/25b6b20703bdde112ee2168aeee379bf/text_embedder.ipynb), [Chinese](https://colab.sandbox.google.com/gist/kuaashish/f49e05a0966c072d54e38df8c2495662/text_embedder.ipynb), and [Korean](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/text_embedder/python/text_embedder.ipynb#scrollTo=Yn0qjHhVVlc_) using the same words you provided. You can see that this model appears to be more accurate.

Thank you!!

**Comment by raghavbansal27** [comment]
Thank you so much! @kuaashish 


Have a good day! :)

**Comment by kuaashish** [comment]
Hi @raghavbansal27,

Can you confirm if this issue requires no further support? If so, we will mark the issue as resolved and close the status.

Thank you!!

**Comment by raghavbansal27** [comment]
Hi @kuaashish,
I have to compare multiple sentences at once, is there any way to fasten the process using mediapipe?

**Comment by kuaashish** [comment]
Hi @raghavbansal27,

I have checked with the team, and currently, it appears that using cores and workers is not feasible from our end. Unfortunately, we are unable to assist with this issue.

Thank you!!
