### ISSUE TITLE
Mediapipe LLM Inference for LoRa Fine-Tuned Gemma-2b-en Model with Keras 

### ISSUE THREAD

**Issue by rahul-exp** [google-ai-edge/mediapipe#5474]
I have fine-tuned Gemma-2b-en model with Keras. I want to test the model on-device with Mediapipe LLM Inference. What's the procedure of doing the same? I read that the Keras model downloaded from Kaggle and fine tuned doesn't need conversion like the Hugging Face model, but wanted to understand how the merging and TFLite conversion of this model and subsequent inference steps look like.

**Comment by kuaashish** [comment]
Hi @rahul-exp,

If you are customizing the model, please follow the [steps](https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference#lora) mentioned in the LLM overview page to run the model. Try this out and let us know your feedback.

Thank you!!

**Comment by rahul-exp** [comment]
Hi @kuaashish ,

Thanks for responding. But these steps are applicable only for model LoRA fine-tuned hugging face models. How about the the LoRA fine-tuned models using keras nlp. What is the procedure for conversion and inference of these models? It would be really helpful if you could throw some light on this.

Thanks in advance!

**Comment by kuaashish** [comment]
Hi @rahul-exp,

Currently, we have limited bandwidth and can not assist with this request. As we have not worked with Keras NLP, we recommend you explore this on your own. Unfortunately, we are unable to help at this time.

Thank you!!
