### ISSUE TITLE
[Question] is image segmentation support available for IOS ?

### ISSUE THREAD

**Issue by santoshgistto** [google-ai-edge/mediapipe#5477]
is image segmentation support available for IOS ?

**Comment by kuaashish** [comment]
Hi @santoshgistto,

You can find the example available [here](https://github.com/google-ai-edge/mediapipe-samples/tree/main/examples/image_segmentation/ios). Although it is not yet included in our documentation, please use the example provided. Follow the iOS setup guide at [MediaPipe iOS Setup Guide](https://ai.google.dev/edge/mediapipe/solutions/setup_ios) first. Then, follow the procedure similar to other iOS task APIs, such as the Hand Landmarker [Hand Landmarker iOS](https://ai.google.dev/edge/mediapipe/solutions/vision/hand_landmarker/ios), and let us know if you require any further support from our end.

Thank you!!

**Comment by kuaashish** [comment]
Hi @santoshgistto,

We use the same model architecture for all our Task APIs across all platforms (iOS, Android, Python, JavaScript, and C++), ensuring consistency for Android as well.

Thank you!!

**Comment by fatiherdogan01** [comment]
Interactive Image Segmentation is not supported in v0.10.14 for iOS, right? 
Do you have any plans regarding this?
