### ISSUE TITLE
cant pip install mediapipe in python 3.7 

### ISSUE THREAD

**Issue by sancia1** [google-ai-edge/mediapipe#5478]
### OS Platform and Distribution

windows

### Programming Language and version

python3.7.4

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

any version of mediapipe

### Android AAR (if android)

None

### Describe the problem

A bug happened!

### Complete Logs

```shell
I even tried this py -m pip install mediapipe

please give a detailed solution SOMEONE !
```

**Comment by kuaashish** [comment]
Hi @sancia1,

You are using an unsupported version of Python, which is preventing the installation of MediaPipe. Please update to a supported version between 3.9 and 3.12, as outlined in our documentation. Should you continue to experience any issues, please let us know.

Thank you!!

**Comment by kuaashish** [comment]
Hi @sancia1,

Could you please provide an update on the status of the above? If the issue is resolved, we can close and mark it accordingly.

Thank you!!

**Comment by sancia1** [comment]
Please give me some time il get back to you today with updates on the issue

**Comment by sancia1** [comment]
Actually I'm not able to add python 3.10 path in env variables due to some admin access issue since its my office laptop, so they will take time to do it, Thank you so much for your patience @kuaashish
