### ISSUE TITLE
unable to find stub files

### ISSUE THREAD

**Issue by hermanumrao** [google-ai-edge/mediapipe#5483]
### MediaPipe Solution (you are using)

Version: 0.10.14

### Programming language

Python

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

Currently I am unable to find stubfiles for this library anywhere, So I wanted to request for stub files with this library

### Will this change the current API? How?

no It won't
![Screenshot from 2024-06-13 23-05-36](https://github.com/google-ai-edge/mediapipe/assets/63940157/070ba538-4c50-46e7-bf67-c125b02416e6)

### Who will benefit with this feature?

clients who are developing projects using mediapipe

### Please specify the use cases for this feature

Easier to use with LSP for autocompletion

**Comment by hermanumrao** [comment]
> Hi @hermanumrao,
> 
> I apologize for the delay in response. After reviewing the provided standalone code, it appears that you are currently using the outdated Pose solution, which is no longer maintained, and we have ceased support for it. This functionality has been integrated into the new Pose Landmarker Task API, detailed [here](https://developers.google.com/mediapipe/solutions/guide#legacy).
> 
> We encourage you to explore the features of our updated Pose Landmarker Task API and suggest replacing the legacy Pose with the new Pose Landmarker. The new solution offers improved performance and additional functionality compared to the legacy Pose solution. You can find the guide for the new Pose Landmarker [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker), along with specific instructions for implementation in the Python platform provided [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python). Additionally, a corresponding example Colab notebook is available for reference [here](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/pose_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Pose_Landmarker.ipynb).
> 
> Please report any observed behavior, ensuring to check if similar issues persist in the upgraded task API. Unfortunately, beyond this, there is limited action we can take to address the specific issue you are facing.
> 
> Thank you!!

sry for the delay from my end too I got busy with smtg,

anyways, the "pose" part you mention in this comment is not the issue
its just that my autocompletion doesn't work because stub files are missing for mediapipe

**Comment by fabiomanz** [comment]
Hi @kuaashish,

sorry for the ping, but I too have the problem that this library seems to not have stub files needed for static type checking.

Can you please reopen the issue, as it is not resolved yet? 

Is there the possibility, that this library adds stub files for static type checking?

**Comment by hermanumrao** [comment]
> Hi @kuaashish,
> 
> sorry for the ping, but I too have the problem that this library seems to not have stub files needed for static type checking.
> 
> Can you please reopen the issue, as it is not resolved yet? 
> 
> Is there the possibility, that this library adds stub files for static type checking? 

Yea that's why I ended up abandoning mediapipe for my project 😔😭

**Comment by flippinroo2** [comment]
I also have this same issue. I am working with mediapipe and my code is filled with "..." is not a known attribute of module. I understand not having types on something brand new, but this is a must have for most production grade libraries.

**Comment by hermanumrao** [comment]
> I also have this same issue. I am working with mediapipe and my code is filled with "..." is not a known attribute of module. I understand not having types on something brand new, but this is a must have for most production grade libraries.

just use some yolo powered version
