### ISSUE TITLE
Number of parameters

### ISSUE THREAD

**Issue by yjmd2222** [google-ai-edge/mediapipe#5488]
What is the number of parameters (weights, biases)? Specifically Pose landmark detectors.

**Comment by kuaashish** [comment]
Hi @yjmd2222,

Could you please let us know the potential use case of model parameter in your scenario? This will help us understand the issue better and provide you with the appropriate update.

Thank you!!

**Comment by yjmd2222** [comment]
Hi.
I say it's just plain information for:
- simple knowledge
- understanding the models along with the architecture (if this is also provided)
- comparison among different models

that can be used in:
- satisfaction of knowing :)
- model enhancement
- writings

etc.

Personally, I'm doing a small writing on pose estimation/activity recognition where I intend to include a model comparison.

**Comment by kuaashish** [comment]
Hi @yjmd2222,

We believe we can not provide this information as based on my knowledge it is not available internally. For additional details about model, please refer to the model card for the pose landmarker available [here](https://storage.googleapis.com/mediapipe-assets/Model%20Card%20BlazePose%20GHUM%203D.pdf). 

Thank you!!

**Comment by yjmd2222** [comment]
OK.
