### ISSUE TITLE
How to get keypoints data ? 請問如何在MainActivity.java中取得keypoints的數值

### ISSUE THREAD

**Issue by 1278057578** [google-ai-edge/mediapipe#5496]
### MediaPipe Solution (you are using)

BlazePoseNcnn

### Programming language

Android java

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

我在Android Studio上執行了了這個項目https://github.com/FeiGeChuanShu/ncnn_Android_BlazePose.git
請問要怎麼獲得keypoints的數據來進行姿勢判斷，例如在MainActivity.java中取得右肩膀的x,y軸

I executed this project on Android Studio https://github.com/FeiGeChuanShu/ncnn_Android_BlazePose.git
How to obtain key point data for posture judgment? For example, obtain the x, y axis of the right arm in MainActivity.java.

### Please specify the use cases for this feature

我在Android Studio上執行了了這個項目https://github.com/FeiGeChuanShu/ncnn_Android_BlazePose.git
請問要怎麼獲得keypoints的數據來進行姿勢判斷，例如在MainActivity.java中取得右肩膀的x,y軸

I executed this project on Android Studio https://github.com/FeiGeChuanShu/ncnn_Android_BlazePose.git
How to obtain key point data for posture judgment? For example, obtain the x, y axis of the right arm in MainActivity.java.

**Comment by kuaashish** [comment]
Hi @1278057578,

We are revisiting to older issues, Could you please let us know if you are still seeking a resolution for this issue, or if it has been resolved on your end?

Thank you!!
