### ISSUE TITLE
Missing error message 

### ISSUE THREAD

**Issue by username-azerty** [google-ai-edge/mediapipe#5499]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Windows 64bit 

### Programming Language and version

Python 3.9

### MediaPipe version

0.10.14 (and other 0.10.*)

### Solution

FaceLandmarker

### Describe the actual behavior

modify stderr in the Windows Power Shell console

### Describe the expected behaviour

display error message in the console

### Standalone code/steps you may have used to try to get what you need

For :
```python 
print("======")
import mediapipe as md 
raise Exception('STDERR')
```
Ouput :
```shell
$ python .\mediapipe_test.py
======
$ 
```

Fix found :
```python 
print("======")
import sys 
sys.stderr = sys.stdout
import mediapipe as md 
raise Exception('STDERR')
```
Ouput :
```shell
$ python .\mediapipe_test.py
======
Traceback (most recent call last):
  File "C:\*\mediapipe_test.py", line 2, in <module>
    raise Exception('STDERR')
Exception: STDERR
$ 
```

### Other info / Complete Logs

only with Python 3.9 on conda 24.5.0

**Comment by kuaashish** [comment]
Hi @username-azerty,

We believe this issue is specific to Python 3.9.* and known to us(Issue #4958) Could you please confirm this? Additionally, could you check with other supported versions (3.10, 3.11, and 3.12) and let us know if the issue occurs there as well?

Thank you!!
