### ISSUE TITLE
Mediapipe API security and term of use needs clarification

### ISSUE THREAD

**Issue by HeidiHe** [google-ai-edge/mediapipe#5501]
Recently there is a [new FTC policy on Biometric data collection](https://www.ftc.gov/system/files/ftc_gov/pdf/p225402biometricpolicystatement.pdf). The only term of use for mediapipe API I could find it [here](https://ai.google.dev/edge/mediapipe/legal/tos), which was updated on 2021. 

- Does it still apply to the new policy?
- The Mediapipe API term of use talks mostly about Andriod api, what about other forms such as web api?

**Comment by kuaashish** [comment]
Hi @HeidiHe,

Our engineering team cannot answer this question directly. MediaPipe is licensed under Apache License 2.0. Please refer to the description at https://github.com/google-ai-edge/mediapipe/blob/master/LICENSE for more information. I hope this helps.

Thank you!!
