### ISSUE TITLE
Convert the face_landmark.tflite file in your solution back to face_landmark.pb (protobuf file). 

### ISSUE THREAD

**Issue by arahanthjain160386** [google-ai-edge/mediapipe#5502]
I am trying to convert the "face_landmark.tflite" file in your solution back to face_landmark.pb (protobuf file). I am working with C# code and unable to find any wrapper frameworks which make use of .tflite files for face landmark detection. Tensorflow.NET does not support an interpreter to load the .tflite models. But it supports loading models in .pb or "savedModel" format.
Can you please let me know if you have the original tensorFlow model in 'SavedModel of .pb format? I can use this with TensorFlow.net.
I tried converting the .pbtxt file back to .pb file but since converting a MediaPipe graph configuration file to a TensorFlow model file (.pb) is not directly feasible due to the different purposes and structures of the two, i am stuck at this juncture. Please let me know if you have the face_landmark.tflite in .pb or SAVED_MODEL format.

Also, is any one of the pre-trained model of TensorFlow (link provided below) used for face_landMark.tflite model generation? Please suggest.
https://github.com/tensorflow/models/tree/master/research/slim#Pretrained

**Comment by kuaashish** [comment]
Hi @1278057578,

We are revisiting to older issues, Could you please let us know if you are still seeking a resolution for this issue, or if it has been resolved on your end?

Thank you!!
