### ISSUE TITLE
Mediapipe Install on NVIDIA Jetson Orin Nano Error: Invalid requirement: 'mediapipe==dev'

### ISSUE THREAD

**Issue by paulsadofsky** [google-ai-edge/mediapipe#5506]
### OS Platform and Distribution

Ubuntu 22.04

### Programming Language and version

Python 3.8 / 3.10

### Installed using virtualenv? pip? Conda?(if python)

Built from source, generating Python wheel and attempt to pip install wheel

### MediaPipe version

0.8.11

### Bazel version

Bazelisk v1.8.1

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.9.0

### Describe the problem

I attempted to build the Mediapipe package for ARM64 Linux by following the following walkthrough (https://www.forecr.io/blogs/ai-algorithms/how-to-download-build-mediapipe-on-nvidia-jetson-xavier-nx), which worked on Jetpack 5.1.3. This, however, only let me use the CPU as delegate with TFLite and I wanted to try on Jetpack 6.0.2. The wheels compile but the installation of the wheel fails with this very short error.

### Complete Logs

```shell
idealab@ubuntu:~/mediapipe/dist$ python3 -m pip install mediapipe-dev-cp38-cp38-linux_aarch64.whl
ERROR: Invalid requirement: 'mediapipe==dev': Expected end or semicolon (after name and no valid version specifier)
    mediapipe==dev
             ^
```

**Comment by kuaashish** [comment]
Hi @paulsadofsky,

Regrettably, We currently do not offer official support for the Nvidia Jetson Development Kit, encompassing both CPU and GPU functionalities. The sole endorsed edge device is the Raspberry Pi 64-bit, as outlined in our [documentation](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions).

For now, you may leverage the community-developed plugin accessible at https://github.com/anion0278/mediapipe-jetson, which includes GPU support as well and reasonably up-to-date. It's important to note that the implementation is based on version 0.8.9. 

Thank you!!

**Comment by sarcom2** [comment]
Hello can you find a way to make it work? @paulsadofsky

**Comment by paulsadofsky** [comment]
> Hello can you find a way to make it work? [@paulsadofsky](https://github.com/paulsadofsky)

Hello! What I ended up discovering is that there is an open-source build for mediapipe that you can find online that works on ARM linux [here](https://github.com/anion0278/mediapipe-jetson), but it only supports CUDA 10.2, which you need Jetpack 4.6 for. The problem there is that the Jetson Orin Nano does not support down to Jetpack 4.x, it only goes down to Jetpack 5.x.

Ultimately, I returned my Jetson Orin Nano and bought a Jetson Nano instead, flashed it with Jetpack 4.6, and installed mediapipe with that repo. Even then, I had issues with getting mediapipe to target the GPU as it kept on only using the CPU to run. Performance wasn't bad, I was able to keep up 30 FPS, but it surely is not a viable solution if you have other things running on your jetson simultaneously. Honestly, my advice would be to ditch the Jetson platform entirely if you want to use Mediapipe. Sucks because the hardware is more than capable to run it, but it's just not official supported which sucks.

Feel free to reach out to me at sadofskypaul@gmail.com if you have any other questions! I went through hell and back with this platform.

**Comment by TokiLi** [comment]
@paulsadofsky Hello, may I ask which version of MediaPipe you are using? I noticed that the release notes for MediaPipe version 0.10.26 state that "0.10.26.1 includes also the support for ARM v7 CPUs (32-bit)". Does this mean it can support the Jetson Orin series?

**Comment by paulsadofsky** [comment]
@TokiLi I don't remember which version I was using at the time as this was quite a while ago that I had worked on this, but it's great to see that they're expanding ARM support! The problem is that the Jetson Orin Nano operates with a Linux OS and has an Arm Cortex-A78AE processor which is 64-bit, not 32-bit as the release notes show. So I unfortunately don't think that it'll work on the Orin series still. Until they publish an official aarch64 Linux package, it will be near impossible to get it to function properly on the Jetsons.

I'll paste here an email response that I had gave to someone who was experiencing the same dilemma as I was:

...

If I'll be totally honest with you, I would ditch the Jetson platforms (if possible) if you are set on using Mediapipe. The biggest problem is that Mediapipe was not built for ARM64 Linux, which all Jetson boards use. If you really would like to use the Jetson platforms still, I have seen some Docker shells that are capable of running object detection algorithms such as this one here:

https://www.forecr.io/blogs/ai-algorithms/how-to-run-tensorflow-object-detection-with-docker-on-jetson-modules?srsltid=AfmBOoo-x9f8OXx2Vdpw5-kZkEwPj948i3YMlCvlSOjxSd-1pHvslOZ8

Unfortunately, Mediapipe and OpenCV are going to be the best off-the-shelf pose tracking that you could get, and rebuilding it from source to work with the Jetson Orins is going to be a months-long nightmare, frankly. As I mentioned in the GitHub discussion, someone has already done that work for the original Jetson Nano. However, that was built for Jetpack 4.x, which is packaged with Cuda 10.2. Unfortunately, all of the Orin-series Jetsons support a minimum version of Jetpack 5.x, which is Cuda 11+. Therefore, this rebuilt Mediapipe won't work. Even when I did end up deploying that rebuilt Mediapipe package on the Jetson Nano, I could only get it to target the CPU for hardware, which ended up resulting in piss-poor performance and entirely defeated the purpose of using a Jetson in the first place.

Ultimately, I would suggest finding another small form factor GPU-based computing platform with an x86 processor so you can run Mediapipe as it was originally designed for. If you can't return your Orin or need it for some other reason, then I'd look into some of those Docker shells and alternatives for pose tracking. But again, I've worked with these Jetsons plenty of times and have found myself frustrated and got virtually nowhere using them.

Hope this helps, feel free to reach out with any more questions you have and best of luck!
