### ISSUE TITLE
Mediapipe Iris without facemesh?

### ISSUE THREAD

**Issue by balavenkataraman123** [google-ai-edge/mediapipe#5515]
I want to use Mediapipe Iris tracking, but I have a different method to crop out the area around the eye. In the documentation of Mediapipe Iris, it says that the position around the eye is cropped out using facemesh.

Since my use case does not involve a full picture of the face, I can't run the face mesh model first. 

is there any way to run Mediapipe Iris without facemesh?

**Comment by kuaashish** [comment]
Hi @balavenkataraman123,

Unfortunately, we have completely ended support for the legacy solutions, including iris. You can find this information in our [documentation](https://ai.google.dev/edge/mediapipe/solutions/guide#legacy). We are sorry, but you will need to find your own solution for your use case. Our primary focus is on improving our Task APIs, and we won't be able to assist further with this issue.

Thank you!!
