### ISSUE TITLE
how to get confidence values of each keypoints for hand? 

### ISSUE THREAD

**Issue by JasOleander** [google-ai-edge/mediapipe#5546]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Ubuntu 22.04

### Task name (e.g. Image classification, Gesture recognition etc.)

hand pixel coordinates and its confidence

### Programming Language and version (e.g. C++, Python, Java)

python

### Describe the actual behavior

using hand_landmarks, there is no confidence of each keypoints but only score for all keypoints. 

### Describe the expected behaviour

I want to get each confidence for each keypoints to define occlusions.

### Standalone code/steps you may have used to try to get what you need

```shell
And can get pixel cooridnates by multiplying image width and height?
```

**Comment by ayushgdev** [comment]
Hello @JasOleander  
HandLandmarker do not output any confidence score for each keypoint as the underlying models do not output such information. The model output can be found in the model card present in the [models section of HandLandmarker](https://ai.google.dev/edge/mediapipe/solutions/vision/hand_landmarker#models) or refer [here](https://storage.googleapis.com/mediapipe-assets/Model%20Card%20Hand%20Tracking%20(Lite_Full)%20with%20Fairness%20Oct%202021.pdf).
Also, the [API documentation](https://ai.google.dev/edge/api/mediapipe/python/mp/tasks/vision/HandLandmarkerResult) for HandLandmarkerResult can help to find related information.
