### ISSUE TITLE
When running with the GPU model, the OpenCL library cannot be opened on this device.

### ISSUE THREAD

**Issue by tjdtn0219** [google-ai-edge/mediapipe#5551]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

ARM64 Android14("UpsideDownCake)

### MediaPipe Tasks SDK version

34

### Task name (e.g. Image classification, Gesture recognition etc.)

LLM

### Programming Language and version (e.g. C++, Python, Java)

Kotlin

### Describe the actual behavior

I cloned the examples/llm_inference/android example and tested it without any changes, following the guidelines. However, it works correctly when using `gemma2b-cpu.bin`, but an error occurs when using `gemma2b-gpu.bin`. I downloaded `gemma2b-gpu.bin` in `int4` format from Kaggle. When I run the Android application, there are no errors in the logcat, but when I launch the app, the emulator screen displays an error message saying, 
`MediaPipeException: internal: Failed to initialize session: %s Can not open OpenCL library on this device.`
I would appreciate it if you could let me know if this is an issue with the emulator.

### Describe the expected behaviour

Nothing Exception.

### Standalone code/steps you may have used to try to get what you need

```shell
MediaPipeException: internal: Failed to initialize session: %s Can not open OpenCL library on this device.
```

**Comment by kuaashish** [comment]
Hi @tjdtn0219,

The issue appears to be with the emulator. Our GenAI tasks, including Image Generator and LLM Inference, currently support only real physical devices. Please test the same scenario on a modern, high-quality physical device and let us know if the issue persists.

Thank you!!
