### ISSUE TITLE
Holistic does not work for python on Linux, MacOs nor on Windows for mediapipe 0.10.14 or the new alpha 0.10.15

### ISSUE THREAD

**Issue by ChristianNSchmitz** [google-ai-edge/mediapipe#5552]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Linux Ubuntu 22.04, MacOs Sonoma, Windows 10

### MediaPipe Tasks SDK version

mediapipe 0.10.14, mediapipe-nightly 0.10.15 alpha

### Task name (e.g. Image classification, Gesture recognition etc.)

Holistic

### Programming Language and version (e.g. C++, Python, Java)

Python 

### Describe the actual behavior

The code crashes both for CPU and GPU delegate

### Describe the expected behaviour

Run smoothly

### Standalone code/steps you may have used to try to get what you need

```shell
Dear developers,
we are very thankful for this important work on mediapipe and would like to apply this pipeline in a research context. However, the new mediapipe version for python (as well as the alpha version 0.10.15) with the new holistic model seemingly does not work on any operating system. We used the code reported in #5531 and tested it both for CPU and GPU usage and it resulted in the same error as in #5531 for all the operating system tested and both mediapipe version. 
As we would highly appreciate using this tool for our work, do you know of any trick to make it work?
Thank you very much for your help!
Best
Christian
```

**Comment by kuaashish** [comment]
Hi @ChristianNSchmitz,

This issue is known to us, and we believe it is specific to the GPU, not the CPU. Please let us know if there is anything incorrect in our analysis. If the GPU usage is indeed the issue, kindly follow up on #5181 and close this one, as we are already tracking it there.

Thank you!!
