### ISSUE TITLE
LLM inference - Openai Chat Api or Llama compatible chat params

### ISSUE THREAD

**Issue by raymon-io** [google-ai-edge/mediapipe#5558]
### Describe the feature and the current behaviour/state

Does GenAi Llm inference support [openai chat api](https://platform.openai.com/docs/api-reference/chat/create) or support taking parameters similar to Llama models? If not then I am requesting implementing the api similar to Openai Chat completion.

### Please specify the use cases for this feature

For example having a stop param to stop the generation of the llm inference would be great. And Llama compatible chat format can be useful to integrate with other frameworks such as Langchain.

### Any Other info

There is a mention of Llama in a comment in [llm.h](https://github.com/google-ai-edge/mediapipe/blob/ebf54edc96dc30d48f39485b50eb61bcdd87043b/mediapipe/tasks/cc/genai/inference/utils/xnn_utils/llm.h#L49) although I am not sure what this is about.

**Comment by schmidt-sebastian** [comment]
Hello, Llama is supported by the our API, but you will have to follow the steps outlined in https://github.com/google-ai-edge/ai-edge-torch to convert Llama into a format that we can use on device. This conversion will allow you to specify any stop tokens the model may use.

The settings that we support for our inference API are outlined here: https://ai.google.dev/edge/api/mediapipe/java/com/google/mediapipe/tasks/genai/llminference/LlmInference.LlmInferenceOptions.Builder

**Comment by natanfudge** [comment]
You can run Llama, but can you use a chat API? How do you actually specify to the model that the context is composed of chat messages with certain roles and contents? There is no API to input a List<ChatMessage> to the model and have those messages be applied to the chat template that is specific to the model.

 How do Google implement a chat interface for their applications, do they just hope that the llm understands that the string "user: xyz \n assistant: abc" means what we think it means?
