### ISSUE TITLE
Link to mediapipe javascript demo is dead

### ISSUE THREAD

**Issue by mgarbade** [google-ai-edge/mediapipe#5561]
The links in this table are dead. Could anyone renew them?

https://github.com/google-ai-edge/mediapipe/blame/0ed6e57b90275f6f8d291193c276b70f07385d70/docs/getting_started/javascript.md#L33

**Comment by kuaashish** [comment]
Hi @mgarbade,

The documentation you are referring to is from the legacy MediaPipe solution, which has now been upgraded to the new Task API. We have ended support for the legacy solution, and relevant links may no longer be functional. you can find out the same information here https://ai.google.dev/edge/mediapipe/solutions/guide#legacy. 

For the most up-to-date information, please refer to our current documentation page here https://ai.google.dev/edge/mediapipe/solutions/setup_web. We request that you adopt our new Task API for JavaScript. You can find the JavaScript setup steps on our page and the corresponding implementation examples, such as the JS guide for object detection, here https://ai.google.dev/edge/mediapipe/solutions/vision/object_detector/web_js.

Thank you!!
