### ISSUE TITLE
How to use FaceDetector full range on gpu？

### ISSUE THREAD

**Issue by RichardQin1** [google-ai-edge/mediapipe#5573]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

linux ubuntu22.04

### MediaPipe Tasks SDK version

0.10.11

### Task name (e.g. Image classification, Gesture recognition etc.)

FaceDetector

### Programming Language and version (e.g. C++, Python, Java)

python

### Describe the actual behavior

full range on gpu

### Describe the expected behaviour

full range on gpu

### Standalone code/steps you may have used to try to get what you need

```shell
old version python use code：

import cv2
import mediapipe as mp

mp_face_detection = mp.solutions.face_detection
face_detection = mp_face_detection.FaceDetection(min_detection_confidence=0.5, model_selection=1)
mp_drawing = mp.solutions.drawing_utils
cap = cv2.VideoCapture(video_path)
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    results = face_detection.process(frame_rgb)
```
new code:
```
import cv2
import mediapipe as mp
import numpy as np
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

BaseOptions = mp.tasks.BaseOptions
FaceDetector = mp.tasks.vision.FaceDetector
FaceDetectorOptions = mp.tasks.vision.FaceDetectorOptions
VisionRunningMode = mp.tasks.vision.RunningMode
mp_drawing = mp.solutions.drawing_utils
options = FaceDetectorOptions(
    base_options=BaseOptions(model_asset_path='blaze_face_short_range.tflite',
                             delegate=python.BaseOptions.Delegate.GPU),
    running_mode=VisionRunningMode.VIDEO)
cap = cv2.VideoCapture(video_path)
with FaceDetector.create_from_options(options) as detector:
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=np.asarray(frame))
        face_detector_result = detector.detect_for_video(mp_image, int(t_time))
```
```

**Comment by kuaashish** [comment]
Hi @RichardQin1,

The new code supports GPU, as indicated by the GPU option in the BaseOptions class in the provided standalone code here. Please run it in GPU mode and let me know if you encounter any errors. If you do, kindly share the complete error log.

Thank you!!

**Comment by RichardQin1** [comment]
> Hi @RichardQin1,
> 
> The new code supports GPU, as indicated by the GPU option in the BaseOptions class in the provided standalone code here. Please run it in GPU mode and let me know if you encounter any errors. If you do, kindly share the complete error log.
> 
> Thank you!!

i want use full range on gpu. now new code use is short range.  I don't know how to use full range.

**Comment by RichardQin1** [comment]
> ```shell
>  model_selection=1
> ```

old code  model_selection=1. and new code how to use score to select.

**Comment by kuaashish** [comment]
Hi @RichardQin1,

Unfortunately, you will not be able to use the full-range model at this time, as it is still unavailable and untested. You can find more information on the Face Detection overview page [here](https://ai.google.dev/edge/mediapipe/solutions/vision/face_detector#models). Additionally, if you are using the full-range model from our legacy face detection, we can not guarantee compatibility with our new Face Detection API or GPU support.

Thank you!!

**Comment by RichardQin1** [comment]
> Hi @RichardQin1,
> 
> Unfortunately, you will not be able to use the full-range model at this time, as it is still unavailable and untested. You can find more information on the Face Detection overview page [here](https://ai.google.dev/edge/mediapipe/solutions/vision/face_detector#models). Additionally, if you are using the full-range model from our legacy face detection, we can not guarantee compatibility with our new Face Detection API or GPU support.
> 
> Thank you!!

OK, fun. I will close this issue. 
May I ask when we plan to release it ?

**Comment by kuaashish** [comment]
Hi @RichardQin1,

Unfortunately, we do not have the necessary information at this time and can not commit to a timeline. However, I will inform you as soon as it becomes available.

Thank you!!

**Comment by abuomar1** [comment]
Hello

I am currently using the Blazeface short_range.tflite model with com.google.mediapipe:tasks-vision:0.10.20 and it works without issue. When I try to swap the short_range for full_range (sparse or dense) tflite files ([found here](https://github.com/google-ai-edge/mediapipe/blob/master/docs/solutions/models.md)), I get run-time errors during image processing:

`RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_detections_calculator.cc:365) (raw_box_tensor->shape().dims[1])==(num_boxes_)`

Do you know how to resolve this / is there a version of mediapipe I can use that is compatible with full range?
