### ISSUE TITLE
Customize the category of the track

### ISSUE THREAD

**Issue by tisaud** [google-ai-edge/mediapipe#5581]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android 11

### MediaPipe version

V0.10.0

### Bazel version

\

### Solution

BoxTracking

### Programming Language and version

C++

### Describe the actual behavior

Too many categories of objects are currently tracked

### Describe the expected behaviour

You want to be able to customize the categories you track, such as tracking only person

### Standalone code/steps you may have used to try to get what you need

```shell
\
```

### Other info / Complete Logs

```shell
\
```

**Comment by kuaashish** [comment]
Hi @tisaud,

We regret to inform you that we have fully discontinued support for box tracking solutions. While we will no longer provide any support, the libraries and documentation will remain available in our [GitHub repository](https://github.com/google-ai-edge/mediapipe) and through services like [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). You can continue to use these legacy solutions in your applications, but please note that we will not be able to offer any further support.

Thank you!!
