### ISSUE TITLE
Inconsistent MediaPipe Tasks Vision version on Maven repository

### ISSUE THREAD

**Issue by ArdeoDeo** [google-ai-edge/mediapipe#5588]
On maven repository of MediaPipe Tasks Vision there is one legacy version with id: 0.20230731.
This version number is misleading as it suggests that it is the highest and therefore the newest version.

This is inconsistent with the current numbering system 0.10.x:
![obraz_2024-08-27_124502959](https://github.com/user-attachments/assets/b21e059e-c4a8-499e-926c-cba088c3984b)

Inspection tools in IDE are also affected by this:
![obraz_2024-08-27_124931417](https://github.com/user-attachments/assets/db7c46b2-2dff-431e-aadb-a46c01d2ad98)

Link to Maven repository: https://mvnrepository.com/artifact/com.google.mediapipe/tasks-vision

Could you please rename or remove that version from Maven repository?

**Comment by kuaashish** [comment]
Hi @ArdeoDeo,

We believe the version you are referring to is the nightly build, which will be replaced once a new version is available. The release is scheduled soon, and we expect that version to be removed. If it isn't, we will highlight the issue with our team.

Thank you!!

**Comment by ArdeoDeo** [comment]
Hi, just letting you know that the issue remains unresolved after v0.10.15.

**Comment by schmidt-sebastian** [comment]
Unfortunately, we published this version a while back with an incorrect version number. It does not look like we can resolve this issue until we bump our main release version.
