### ISSUE TITLE
Support for GEMMA-2-2B-it Model

### ISSUE THREAD

**Issue by jfduma** [google-ai-edge/mediapipe#5594]
### MediaPipe Solution (you are using)

Version: 0.10.14

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

It seems that Mediapipe currently does not support the GEMMA-2-2B-it model. Is there a plan to support it? When can we expect it to be completed?

### Please specify the use cases for this feature

convert gemma-2-2b-it for mediapipe

**Comment by kuaashish** [comment]
Hi @jfduma,

Thank you for submitting this feature request. We believe it aligns with our current roadmap, and we are working on its implementation. However, we can not commit to a specific availability timeline at this moment. We will share your request with our team and notify you once it's supported.

**Comment by jfduma** [comment]
Thank you for the update. I look forward to hearing more when it's available.

Best,
jfduma

**Comment by kuaashish** [comment]
Hi @jfduma,

Our LLM Task API now supports the Gemma 2-2B models now. You can find more information on our [documentation page](https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference#gemma-2_2b). Additionally, you can follow this [example](https://colab.sandbox.google.com/drive/19h3SZBiWuGqqtddHbF5MzOFGbPahXPIv?usp=sharing) to convert the models to TFLite.

Thank you!!

**Comment by tyrmullen** [comment]
Note that the conversion process mentioned in the documentation above will only work for CPU backends, which I believe limits its usage to Android and iOS APIs. While unfortunately this is not mentioned in the paragraph linked to above, the relevant disclaimer can be found on the LLM Inference overview page:
```
Note: Models mapped using AI Edge Torch can only run on the CPU backend and are therefore limited to Android and iOS.
```

**So running Gemma-2-2B as described above uses a different conversion process which will only work on Android using the CPU backend (and maybe iOS using the CPU backend).**

**Comment by tyrmullen** [comment]
Gemma-2-2B should now also be runnable on GPU with the latest (0.10.16) release on *web*. We have not published a pre-converted model, nor released detailed documentation for it yet, but the usual conversion process (from .safetensors) should work there now.  So to summarize the current state of support:
- Android or iOS: use new conversion process (AI EdgeTorch); runs on CPU
- Web: use old conversion process (follow old Gemma 1.1 instructions, but use name "GEMMA2_2B"); runs on GPU
