### ISSUE TITLE
如何将mediapipe手部关键点检测的模型导出为.tflite格式

### ISSUE THREAD

**Issue by Criminal-9527** [google-ai-edge/mediapipe#5598]
如何将mediapipe手部关键点检测的模型导出为.tflite格式，我们想尝试在边缘设备上使用这个模型。还有就是可以手动量化这个模型吗，我们的设备性能貌似不太强

**Comment by kuaashish** [comment]
Hi @Criminal-9527,

Could you please clarify your query in standard English? We are having difficulty understanding the issue, If possible from your end. 

Thank you!!
