### ISSUE TITLE
inconsistent face landmarker detection result

### ISSUE THREAD

**Issue by gubinfdu** [google-ai-edge/mediapipe#5599]
I tried two methods to detect face landmarkers, but got different results. Would you please check this issue?

Method 1:
```python
face_mesh = mp.solutions.face_mesh.FaceMesh(
    max_num_faces=1,
    refine_landmarks=True,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)
landmarks = face_mesh.process(img).multi_face_landmarks[0].landmark
``` 

Method 2:
Got face_landmarks_detector.tflite model from here:
https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker?hl=zh-cn
```python
interpreter = tf.lite.Interpreter(model_path=path)
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
input_index = input_details[0]['index']
interpreter.set_tensor(input_index, img_resize)
interpreter.invoke()
landmarks = interpreter.get_tensor(473)
```

Tried to plot facial contour and found some distortion in second method. I need to use this tflite model, and would  you please help to solve this problem?

**Comment by kuaashish** [comment]
Hi @gubinfdu,

It appears that you are currently using the legacy facemesh solution. We would like to inform you that the face mesh functionality is now part of the Face Landmarker Task API, as outlined in the [documentation](https://developers.google.com/mediapipe/solutions/guide#legacy). This API serves as a superset of the facemesh solution and offers easier adoption across all platforms with ongoing maintenance.

However, support for the legacy face mesh solution has been completely discontinued for all upgraded solutions as well, as detailed in the same [page](https://developers.google.com/mediapipe/solutions/guide#legacy). While the GitHub source codes and NPM packages for the legacy solution will remain available, But we will not be providing support for them.

We recommend exploring our new Face Landmarker and referring to the overview documentation available on the [page](https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker). For implementation on Python, please follow the Python Setup guide provided [here](https://ai.google.dev/edge/mediapipe/solutions/setup_python) and Colab example you can find [here](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/face_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Face_Landmarker.ipynb)

Also, We kindly request you to report any similar behavior if observed in the upgraded solution.

Thank you!!

**Comment by S3od22** [comment]
سعودددًًs3.@“..


في اثنين، 2 سبتمبر، 2024 في 6:10 ص، كتب gubinfdu ***@***.***>:

**Comment by S3od22** [comment]
سعودددًًs3.@“..
ً


في اثنين، 2 سبتمبر، 2024 في 10:03 ص، كتب سعود العسيري ***@***.***
