### ISSUE TITLE
Whether Mediapipe supports the overall detection of multiple people

### ISSUE THREAD

**Issue by jhlibra** [google-ai-edge/mediapipe#5607]
### MediaPipe Solution (you are using)

 Holistic Markerer

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

Only one person can be identified in this example

### Please specify the use cases for this feature

 Holistic

### Any Other info

 Holistic whether to support multiple user identification

**Comment by ayushgdev** [comment]
Hello @jhlibra 

MediaPipe holsitic landmarker does not support detection of multiple persons in a scene as of now. We are marking this as a feature request and will share it with our team. However, we cannot provide a timeline or confirm if it will be supported, as it will depend on further demand and discussions.
