### ISSUE TITLE
Running on a TV box with poor performance

### ISSUE THREAD

**Issue by InitialFStudio** [google-ai-edge/mediapipe#5608]
Running on my phone, everything is normal and the performance is good, but when I install it on my TV box, it runs very slowly and the performance is poor. 
![20240905-093305](https://github.com/user-attachments/assets/b0a3f267-681b-4f50-aaa7-03b7034ee32f)
I use the Android library of Unity3D and Mediapipe. The model I use is pose_landmarker_lite.task. Without starting AI, the frame rate of the application can reach 60 frames, but after starting AI, the AI ​​delay is 100 to 200ms and the frame rate of the application is The rate is just over 10 frames.
After these tests, I guess it is because the pose_landmarker_lite.task model is not suitable for low-performance devices such as TV boxes.
My business needs only require the 2D coordinates of 16 skeletal points of the human body.
Are lighter models available?

**Comment by kuaashish** [comment]
Hi @InitialFStudio,

Unfortunately, we do not officially support Unity and are unable to assist with this issue. If you are using a community-based example or library, we recommend raising the issue on the relevant repository or forum for further assistance. We apologize for the inconvenience but can not provide additional support on this matter.

Thank you!!
