### ISSUE TITLE
I can modify the recognized categories by modifying the calculator（TfLiteTensorsToDetectionsCalculator）

### ISSUE THREAD

**Issue by tisaud** [google-ai-edge/mediapipe#5611]
Due to hardware reasons, MediaPipe tracks too many objects at the same time causing the frame rate to drop, and it is hoped that the categories of recognition and tracking can be reduced by modifying it。

I wonder if it is possible to modify the value class of "object_detection_gpu.txt“: "TfLiteTensorsToDetectionsCalculator"，like ”num_classes“
node {
  calculator: "TfLiteTensorsToDetectionsCalculator"
  input_stream: "TENSORS_GPU:detection_tensors"
  input_side_packet: "ANCHORS:anchors"
  output_stream: "DETECTIONS:detections"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteTensorsToDetectionsCalculatorOptions] {
      num_classes: 91
      num_boxes: 2034
      num_coords: 4
      ignore_classes: 0
      sigmoid_score: true
      apply_exponential_on_box_size: true
      x_scale: 10.0
      y_scale: 10.0
      h_scale: 5.0
      w_scale: 5.0
      min_score_thresh: 0.6
    }
  }
}

**Comment by kuaashish** [comment]
Hi @tisaud,

We are revisiting older issues. Please let us know if you still need assistance with this issue or if it is no longer required.

Thank you!!
