### ISSUE TITLE
object detection on android with gpu will crash when set  setCategoryAllowlist

### ISSUE THREAD

**Issue by hugski** [google-ai-edge/mediapipe#5614]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

android 13

### Mobile device if the issue happens on mobile device

xiaomi pad 6 pro

### Programming Language and version

kotlin java

### MediaPipe version

com.google.mediapipe:tasks-vision:latest.release

### Solution

Object detection

### Describe the actual behavior

eg.  setCategoryAllowlist("person") will crash and error message is "Check failed: class_index_set_.values.size() == IsClassIndexAllowed(0) ? num_classes_ : num_classes_ - 1 (1 vs. 90) Only all classes  >= class 0  or  >= class 1"

### Describe the expected behaviour

setCategoryAllowlist("person") and the result only contain person categories

### Standalone code/steps you may have used to try to get what you need

```shell
val baseOptions = BaseOptions.builder()
                .setDelegate(Delegate.GPU)
                .setModelAssetPath("detect/efficientdet-lite0.tflite")
                .build()

            val options = ObjectDetector.ObjectDetectorOptions.builder()
                .setBaseOptions(baseOptions)
                .setCategoryAllowlist(mutableListOf("person"))
```

**Comment by kuaashish** [comment]
Hi @hugski,

Could you please try using List<String> instead of mutableListOf, as both should behave similarly, but we would like to test this approach just in case it resolves the issue?

Also, when using the CPU as the delegate, could you provide an update on the status?

Thank you!!

**Comment by hugski** [comment]
@kuaashish  
1. changed mutableListOf to List, and the same issuse happen and the app crash

```kotlin
val baseOptions = BaseOptions.builder()
                .setDelegate(Delegate.GPU)
                .setModelAssetPath("detect/efficientdet-lite0.tflite")
                .build()

val options = ObjectDetector.ObjectDetectorOptions.builder()
    .setBaseOptions(baseOptions)
    .setCategoryAllowlist(listOf("person"))
```
the error message is 

`setCategoryAllowlist("person") will crash and error message is "Check failed: class_index_set_.values.size() == IsClassIndexAllowed(0) ? num_classes_ : num_classes_ - 1 (1 vs. 90) Only all classes >= class 0 or >= class 1"`

2. When Delegate changed to CPU, the app behave normally
```kotlin
val baseOptions = BaseOptions.builder()
                .setDelegate(Delegate.CPU)
                .setModelAssetPath("detect/efficientdet-lite0.tflite")
                .build()

val options = ObjectDetector.ObjectDetectorOptions.builder()
    .setBaseOptions(baseOptions)
    .setCategoryAllowlist(listOf("person"))

**Comment by kuaashish** [comment]
Hi @hugski,

Apologies for the delayed response. Could you please update to Android 14, as it supports API level 34, which is required in MediaPipe version 0.10.15. You can find more details in our release notes [here](https://github.com/google-ai-edge/mediapipe/releases/tag/v0.10.15) under Android section 'Bump targetSdkVersion to 34 throughout MediaPipe.' 

Additionally, please try the latest version (0.10.15) and let us know if the issue persists.

Thank you!!

**Comment by CoderBt** [comment]
same bug

**Comment by PanagiotisTsinganos** [comment]
I have the same issue when testing in Android 14 device. The allow list works when using the CPU but it crashes the app when the GPU is used.

**Comment by tadghh** [comment]
@kuaashish please reopen this, the issue still exists
