### ISSUE TITLE
Model Maker Supportting for Image Segmentation

### ISSUE THREAD

**Issue by consistent1997** [google-ai-edge/mediapipe#5617]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python Version

3.8

### MediaPipe Model Maker version

latest

### Task name (e.g. Image classification, Gesture recognition etc.)

Image Segmentation

### Describe the actual behavior

Model Maker for Image Segmentation

### Describe the expected behaviour

No supportting

### Standalone code/steps you may have used to try to get what you need

```shell
I want to use Model Maker for Image Segmentation to retrain my own human image matting dataset, but I can't find the interface of this task. So I want to make sure whether the latest mediapipe support image segmentatation model maker recently or not. Hope your reply, sincerely. Thank you!
```

### Other info / Complete Logs

```shell
no
```

**Comment by kuaashish** [comment]
Hi @consistent1997,

Thank you for suggesting the addition of customization features using Model Maker in our Image Segmentation API. We are forwarding this request to our team, and while we may consider it based on future demand and discussions, we are unable to provide a timeline for its availability at this time.

**Comment by joezoug** [comment]
Hi @consistent1997,

To answer your question: no the current model maker does not support Image Segmentation. We don't have plans to add support for this task in the near future right now.

**Comment by consistent1997** [comment]
ok, I know, Thanks for all answers!
