### ISSUE TITLE
Running tasks-vision on Mac Chrome Web Worker crashes

### ISSUE THREAD

**Issue by joacopaz** [google-ai-edge/mediapipe#5631]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Mac Ventura

### Browser and version if the issue happens on browser

Chrome 128 (latest)

### Programming Language and version

JavaScript

### MediaPipe version

tasks-vision 0.10.6

### Solution

Tasks Vision

### Describe the actual behavior

When running on worker it crashes because document is undefined, Mac code path leads to a faulty check

### Describe the expected behaviour

Should not check for document if not available in global context

### Standalone code/steps you may have used to try to get what you need

```shell
navigator.userAgent.includes("Mac") && "ontouchend" in document

Following the stack trace leads to this check. Document does not exist on worker and this path should not happen.
```

**Comment by ayushgdev** [comment]
Hello @joacopaz 
Can you please try in the latest version v0.10.15 and check if the issue persists?
Also, a minimal example to reproduce the issue can be helpful for us in faster understanding and resolution.

**Comment by joacopaz** [comment]
Hey @ayushgdev it's the Image Segmenter task. I'll tesdt on 0.10.15 and get back to you! Thank you for the quick reply

**Comment by joacopaz** [comment]
@ayushgdev tested in 0.10.15 and the code has changed to `"ontouchend"in self.document` but document still does not exist in self. The file is `vision_bundle.cjs` and `vision_bundle.mjs`

**Comment by joacopaz** [comment]
I've posted PR #5636 for this case

**Comment by ayushgdev** [comment]
@schmidt-sebastian Can you please review the thread and related PR?

**Comment by joacopaz** [comment]
PR merged
