### ISSUE TITLE
Language Dedtection documents link is broken 

### ISSUE THREAD

**Issue by sajjadrahman56** [google-ai-edge/mediapipe#5632]
### Description of issue (what needs changing)

Update the 101 different language documentation link 

### Clear description

From studio : Identify the language of a text input. The pretrained model can detect 110 different languages, including English, French, Japanese etc. For more information on labels, performance, etc., see the documentation.

here if I click the document it shows a 404

### Correct links
document link
 https://mediapipe-studio.webapps.google.com/studio/demo/language_detector

**Comment by ayushgdev** [comment]
Hello @sajjadrahman56 
Thanks for bringing the issue to our attention. We are able to reproduce the issue and shall fix it.

**Comment by kuaashish** [comment]
Hi @sajjadrahman56,

We have raised an internal PR and are awaiting approval from our team. We will inform you once it will be merged.

Thank you!!

**Comment by kuaashish** [comment]
Hi @sajjadrahman56,

Thank you for reporting this. The internal PR has been merged, and the link has been fixed. You can now view it here: https://mediapipe-studio.webapps.google.com/studio/demo/language_detector. We are closing this issue and marking it as resolved now.

**Comment by sajjadrahman56** [comment]
Thank you @kuaashish for fixing this.
