### ISSUE TITLE
face_mesh    dll  error 

### ISSUE THREAD

**Issue by xcjcb001** [google-ai-edge/mediapipe#5642]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

windows 10

### MediaPipe Tasks SDK version

0.10.9

### Task name (e.g. Image classification, Gesture recognition etc.)

face_mesh  dll

### Programming Language and version (e.g. C++, Python, Java)

c++ 

### Describe the actual behavior

debugger  

### Describe the expected behaviour

can not read the config

### Standalone code/steps you may have used to try to get what you need

```shell
std::string calculator_graph_config_contents;
MP_RETURN_IF_ERROR(mediapipe::file::GetContents(model_path, &calculator_graph_config_contents));
std::cout << "mediapipe::file::GetContents success" << std::endl;

mediapipe::CalculatorGraphConfig config =
    mediapipe::ParseTextProtoOrDie<mediapipe::CalculatorGraphConfig>(
        calculator_graph_config_contents); 
MP_RETURN_IF_ERROR(m_Graph.Initialize(config))) :
```

### Other info / Complete Logs

```shell
MP_RETURN_IF_ERROR(m_Graph.Initialize(config))) :   Exception raised: Read access conflict.   the mediapipe::CalculatorGraphConfig config is null.    but std::string calculator_graph_config_contentsnot null. I don't know what the problem is and how to proceed anymore
```

**Comment by xcjcb001** [comment]
**absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashMapPolicy<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,mediapipe::tool::FieldDescriptor>,absl::lts_20230125::container_internal::StringHash,absl::lts_20230125::container_internal::StringEq,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,mediapipe::tool::FieldDescriptor> > >::common**(...)  retrun 0x28。

**Comment by kuaashish** [comment]
Hi @xcjcb001,

Could you please confirm if you still need assistance with this issue, or has it been resolved on your end?

Thank you!!
