### ISSUE TITLE
can i build custom task, on mediapipe ? 

### ISSUE THREAD

**Issue by RansomBroker** [google-ai-edge/mediapipe#5646]
### OS Platform and Distribution

linux ubuntu

### Programming Language and version

javascript

### MediaPipe version

0.10.5

### Android AAR (if android)

None

### Describe the problem

A bug happened!

how i can build mediapipe into web ?, what is purpose of web folder on mediapipe ? how i can run it ? there is lack of documentiation about it, i try to build mediapipe on web with custom, but i'm facing issues, and i saw task/web/vision, can i, but i dont see documentation about it, can you guide me ? can i build my custom solution ? , like combine between object detector and image segmentation or i have custom tflite model to load in it

**Comment by kuaashish** [comment]
Hi @RansomBroker,

Thank you for providing more details in the newly raised issue https://github.com/google-ai-edge/mediapipe/issues/5648. We are marking this issue as a duplicate and closing it. Please follow and track progress on the new issue.
