### ISSUE TITLE
The MediaPipe Tasks Vision 0.10.16 package doesn´t have the wasm folder in the jsDelivr CDN

### ISSUE THREAD

**Issue by olalinv** [google-ai-edge/mediapipe#5647]
When loading the link https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/ you can see that there is no ‘wasm’ folder. All previous versions of this package include it, even the RC version (0.10.16-rc.20240925).

Affected jsDelivr links:
- https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.16/wasm/vision_wasm_internal.js
- https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.16/wasm/vision_wasm_internal.wasm
- https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.16/wasm/vision_wasm_nosimd_internal.js
- https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.16/wasm/vision_wasm_nosimd_internal.wasm

Thanks

**Comment by kuaashish** [comment]
Hi @olalinv,

Thank you for reporting this. It appears to be a bug. We have verified that the corresponding WASM files are available in previous versions and the latest version (0.10.16), but they seem to be missing. We are investigating the issue with our team and will update you as soon as we have more information.

**Comment by schmidt-sebastian** [comment]
Sorry - the Vision and the GenAI package did not get published correctly. 0.10.17 fixes this.
