### ISSUE TITLE
Create custom task mediapipe

### ISSUE THREAD

**Issue by RansomBroker** [google-ai-edge/mediapipe#5648]
i want ask how i cam custom make web task on mediapipe, i don't understand how to build from the task/web/vission can someone give me guide about it

**Comment by kuaashish** [comment]
Hi @RansomBroker,

We believe you can make customizations using our MediaPipe Model Maker. However, not all functionality is available for Vision, Audio, Text, and Generative AI tasks. You can refer to the supported models for customization here https://ai.google.dev/edge/mediapipe/solutions/guide#available_solutions, which can be used across platforms like Python, JavaScript, iOS, C++, and Android. 

At this time, we do not have any documentation or found the community-based implementations for this. Please allow us some time to discuss with our team, and we will update you on how we can assist further.

Thank you!!

**Comment by RansomBroker** [comment]
so, i can't build custom task? like i want combine two task like segmentation and face landmark, into one pipeline on web

**Comment by schmidt-sebastian** [comment]
All the build rules we use to build the JS packages are available here: https://github.com/google-ai-edge/mediapipe/tree/master/mediapipe/tasks/web
You can add your own JS tasks following the existing examples.
Unfortunately, right now we do not offer a way to customize the Wasm blobs, so you will only be able to use features in your models and MediaPipe graphs that are already used by other vision tasks.
