### ISSUE TITLE
How to implement custom hand landmark on web

### ISSUE THREAD

**Issue by RansomBroker** [google-ai-edge/mediapipe#5653]
This template is for miscellaneous issues not covered by the other issue categories

For questions on how to work with MediaPipe, or support for problems that are not verified bugs in MediaPipe, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mediapipe) and [Slack](https://mediapipe.page.link/joinslack) communities.

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/google/mediapipe/security).

how i can implement custom hand landmark, like i have custom tflite, what should i use vission task? because i adding new landmark on hand

**Comment by kuaashish** [comment]
Hi @RansomBroker,

We are actively tracking the previously raised issue and the support you have requested. Please allow us some time, and we will provide an update shortly. In the meantime, kindly follow up on the issue we are already addressing. We are closing this issue as a duplicate of #5648.

Thank you!!
