### ISSUE TITLE
What is the best lite model for background removal?

### ISSUE THREAD

**Issue by fatiherdogan01** [google-ai-edge/mediapipe#5657]
Hi,

I'm using "selfie_multiclass_256x256" and "deeplab_v3" models for background removal. 
The "selfie multiclass 256x256" model works very well. But the "deeplabv3" model does not work well.

Does anyone have any suggestions for a lite model for mobile devices?

**Comment by edamlmmv** [comment]
Doesn't selfie_multiclass_256x256 work on mobile as well?
Personally I do not use deeplabv3, I preload MLKIT's model and once selfie_multiclass_256x256 is loaded I replace it.
(See volcomix's implementation: https://github.com/Volcomix/virtual-background)

**Comment by kuaashish** [comment]
Hi @fatiherdogan01,

We do not have a matrix comparison of the supported models. We suggest checking the overview page https://ai.google.dev/edge/mediapipe/solutions/vision/image_segmenter#models for model selection based on your image segmentation needs. You can also use a custom model in our API. Additionally, task benchmarks for all supported models on mobile device is available here https://ai.google.dev/edge/mediapipe/solutions/vision/image_segmenter#task-benchmarkse.

Thank you!!

**Comment by fatiherdogan01** [comment]
I'm now using this model https://github.com/xuebinqin/DIS and this is good.
