### ISSUE TITLE
Task Vision for yolo model

### ISSUE THREAD

**Issue by RansomBroker** [google-ai-edge/mediapipe#5659]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Linux Ubuntu

### MediaPipe Tasks SDK version

0.10.3

### Task name (e.g. Image classification, Gesture recognition etc.)

Vision

### Programming Language and version (e.g. C++, Python, Java)

javascript

### Describe the actual behavior

YOLO Model

### Describe the expected behaviour

Run YOLO Model on Task Vision

### Standalone code/steps you may have used to try to get what you need

```shell
there is example using yolo model on task-vision js solution ?
```

**Comment by kuaashish** [comment]
Hi @RansomBroker,

Currently, we do not have examples available using the YOLO model. All object detection models are trained on COCO datasets, as noted in our documentation [here](https://ai.google.dev/edge/mediapipe/solutions/vision/object_detector#models). Customization is possible through our MediaPipe Model Maker, but datasets should follow the COCO or Pascal format. If you believe this feature is essential, we recommend submitting a detailed [feature request](https://github.com/google-ai-edge/mediapipe/issues/new?assignees=&labels=type%3Afeature&projects=&template=14-feature-request-issue-template.yaml), outlining its community benefits. While we will consider it based on future demand and team discussions, we can not commit to a specific timeline at this point.

Thank you!!
