### ISSUE TITLE
Question - Does Google uses any of the publicly available model for Google Meet?

### ISSUE THREAD

**Issue by edamlmmv** [google-ai-edge/mediapipe#5660]
Hi,

I would like to know if Google uses any of the publicly available model for Google Meet?
By publicly available I mean those accessible on this page: https://ai.google.dev/edge/mediapipe/solutions/vision/image_segmenter#configurations_options

The reason why I am asking this is; my implementation of the image segmenter, which uses [SelfieMulticlass (256 x 256)](https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_multiclass_256x256/float32/latest/selfie_multiclass_256x256.tflite) is not as good as Google Meet. 

Therefore I would like to confirm my hypothesis. If Google Meet is using the SAME model then it means the post processing of my WebGL2 pipeline needs to be adjusted. Else if Google Meet is using a different model then it means my implementation of the image segmenter will never be as good as Google Meet unless the model is publicly available.

Thank you.

**Comment by kuaashish** [comment]
Hi @edamlmmv,

Unfortunately, no. Google Meet uses a different model, and we believe that part is also not publicly available. Apologies, but this is the only information we are able to provide.

Thank you!!

**Comment by kuaashish** [comment]
Hi @edamlmmv,

Could you please review the information [above](https://github.com/google-ai-edge/mediapipe/issues/5660#issuecomment-2392906578) and confirm if we can mark this issue as resolved and close the status?

Thank you!!
