### ISSUE TITLE
License of 3D model from the demo site.

### ISSUE THREAD

**Issue by nicoaodo** [google-ai-edge/mediapipe#5662]
Hi,
Can I use this 3D model of the Raccoon head for commercial purposes? https://storage.googleapis.com/mediapipe-tasks/face_landmarker/raccoon_head.glb
I found it in the source of the demo site https://mediapipe-studio.webapps.google.com/demo/face_landmarker
Thank you.

**Comment by kuaashish** [comment]
Hi @nicoaodo,

Yes, MediaPipe can be used for commercial purposes under the Apache 2.0 License. Please refer to the attached screenshot for reference and review the Apache 2.0 [terms and conditions](https://github.com/google-ai-edge/mediapipe/blob/master/LICENSE) for further details.

<img width="1390" alt="Screenshot 2024-10-03 at 12 09 43 PM" src="https://github.com/user-attachments/assets/17eead59-16e9-410d-9d1c-f6772cdc652e">


Thank you!!

**Comment by nicoaodo** [comment]
@kuaashish 
Thank you for your response! But I think there might be a slight misunderstanding here.

On this demo page [https://mediapipe-studio.webapps.google.com/demo/face_landmarker](https://mediapipe-studio.webapps.google.com/demo/face_landmarker), some assets are sourced from external links, specifically the 3D model `raccoon_head.glb`: [https://storage.googleapis.com/mediapipe-tasks/face_landmarker/raccoon_head.glb](https://storage.googleapis.com/mediapipe-tasks/face_landmarker/raccoon_head.glb).

Can I use that 3D model `raccoon_head.glb` for commercial purposes, or do you have any information about the author of it?

Thank you!!

**Comment by kuaashish** [comment]
Hi @nicoaodo,

We believe it can be used. Please refer to the above [comment](https://github.com/google-ai-edge/mediapipe/issues/5662#issuecomment-2390640016) and review the terms and conditions for further details.

Thank you!!
