### ISSUE TITLE
Update URL for python on pose landmarker demo page

### ISSUE THREAD

**Issue by koke1997** [google-ai-edge/mediapipe#5665]
### Description of issue (what needs changing)

url change

### Clear description

The old URL is not active, because this repo is renamed

### Correct links

https://github.com/google-ai-edge/mediapipe-samples/blob/main/examples/pose_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Pose_Landmarker.ipynb

### Parameters defined

yes

### Returns defined

yes

### Raises listed and defined

yes

**Comment by koke1997** [comment]
https://mediapipe-studio.webapps.google.com/demo/pose_landmarker

This is the page , and when you click on python sample code it will lead to 404.

Correct URL should be - https://github.com/google-ai-edge/mediapipe-samples/blob/main/examples/pose_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Pose_Landmarker.ipynb

**Comment by kuaashish** [comment]
Hi @koke1997,

Thank you for bringing this to our attention. We have raised an internal PR for the fix and are awaiting approval. We will inform you once it has been resolved.

**Comment by kuaashish** [comment]
Hi @koke1997,

We are closing this issue as resolved internally, as the internal PR has been merged and the example link is now working again. You can verify it here: https://mediapipe-studio.webapps.google.com/studio/demo/pose_landmarker.

Thank you!!
