### ISSUE TITLE
media pipe finger detection

### ISSUE THREAD

**Issue by breeradigitify** [google-ai-edge/mediapipe#5667]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### Solution

Hand Landmark

### Programming Language and version

Kotlin

### Describe the actual behavior

Media pipe doesnt detect fingers only, when no palm is in frame.

### Describe the expected behaviour

It should detect the fingers as it part of hand

### Standalone code/steps you may have used to try to get what you need

```shell
I integrated media pipe hand landmark solution. I want to get the fingers land mark as soon as it enters in camera, at least first segment of finger.
But it didnt detect untill palm enters in camera.  As documentation says it is combination of hand and palm detection model so desired behaviour isn't achievable with media pipe or am i missing something.
```

**Comment by AmineAouragh** [comment]
Hey, just so I can understand the issue, you mean your fingers can't be detected when your hand palm is not in frame? I think that's very normal since how are fingers supposed to be detected if the camera can't see them? Or did I miss something here? 

UPDATE: 
Do you mean when only a finger enters the frame, it cannot be detected until the camera can capture the whole hand?

**Comment by breeradigitify** [comment]
> Hey, just so I can understand the issue, you mean your fingers can't be detected when your hand palm is not in frame? I think that's very normal since how are fingers supposed to be detected if the camera can't see them? Or did I miss something here?
> 
> UPDATE: Do you mean when only a finger enters the frame, it cannot be detected until the camera can capture the whole hand?


Yes thats the case. my case is i want to get the result from land marks if only fingers are in camera frame.  I want to clear that is media pipe can help me in this or not? Is media dependent on palm?

**Comment by breeradigitify** [comment]
> Hey, just so I can understand the issue, you mean your fingers can't be detected when your hand palm is not in frame? I think that's very normal since how are fingers supposed to be detected if the camera can't see them? Or did I miss something here?
> 
> UPDATE: Do you mean when only a finger enters the frame, it cannot be detected until the camera can capture the whole hand?


Yes thats the case. my case is i want to get the result from land marks if only fingers are in camera frame.  I want to clear that is media pipe can help me in this or not? Is media dependent on palm?

**Comment by kuaashish** [comment]
Hi @breeradigitify,

We believe that detecting only fingers without a palm is beyond the scope of the MediaPipe hand landmarker Task API. If you have a specific use case requiring this functionality, we suggest exploring our Model Maker tool, though it is currently unavailable for hand landmarker Or you need to train your own model for your specific requirement.

Thank you!!

**Comment by breeradigitify** [comment]
> Hi @breeradigitify,
> 
> We believe that detecting only fingers without a palm is beyond the scope of the MediaPipe hand landmarker Task API. If you have a specific use case requiring this functionality, we suggest exploring our Model Maker tool, though it is currently unavailable for hand landmarker Or you need to train your own model for your specific requirement.
> 
> Thank you!!

OK thanks, I got the point that media pipe is not for this purpose. I suggest to please do work on it for future such cases
