### ISSUE TITLE
Inquiry on Demographics Coverage in MediaPipe Landmark Detection Models

### ISSUE THREAD

**Issue by marcnunez** [google-ai-edge/mediapipe#5668]
Hello,

 I am currently using the MediaPipe landmark detection models for a project that requires a comprehensive understanding of the model's performance across various demographic groups. To ensure fairness and accuracy in my application, I would like to know more about the demographic coverage considered during the training of the models.

Specifically, could someone provide insights into the following:

Which datasets were used to train the landmark detection models, and do they include information on ethnicity or other demographic attributes?
Were there specific efforts or techniques used to ensure diversity and reduce bias across different demographic groups?
Is there any publicly available documentation or research that details the demographic diversity and representation in the training data?

Thank you for your time and support!

Best regards,
Marc

**Comment by kuaashish** [comment]
Hi @marcnunez,

As @Riztazz mentioned, details about the model’s training environment and demographics can be found in the Groups section on page 3 of the model card, such as the BlazeFace Model Card (Short Range) for [here](https://storage.googleapis.com/mediapipe-assets/MediaPipe%20BlazeFace%20Model%20Card%20(Short%20Range).pdf). We also have two additional model cards available [here](https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker#models). Please refer to the model cards for all other relevant details.

Thank you!!

**Comment by kuaashish** [comment]
Hi @marcnunez,

Could you please review the information [above](https://github.com/google-ai-edge/mediapipe/issues/5668#issuecomment-2401418735)  and let us know if it answers your question?

Thank you!!
