### ISSUE TITLE
 Fine-tuning face detection and face landmark models

### ISSUE THREAD

**Issue by AbdullahOx** [google-ai-edge/mediapipe#5671]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Fedora Linux 40

### Python Version

3.12

### Task name (e.g. Image classification, Gesture recognition etc.)

Face detection and face landmark

### Describe the actual behavior

na

### Describe the expected behaviour

na

### Standalone code/steps you may have used to try to get what you need

```shell
Hi, 

I have an unpublished dataset that I am using for research. Both face detection and landmark models will be useful.

I have tested the face detection model on my dataset and obtained an AP@0.5 score of 0.89.

I would like to improve these results by fine-tuning the model. I haven't yet tested the face landmark model, but I assume I will need to fine-tune it as well.

Thank you.
```

**Comment by kuaashish** [comment]
Hi @AbdullahOx,

Thank you for suggesting the extension of the model maker to include face detection and face landmarking features. Currently, these features are not available, and we do not have any documentation or code examples to reference. However, we can mark this as a feature request and share it with our team. Implementation will depend on future demand and bandwidth, but we can not provide a timeline at this moment.
