### ISSUE TITLE
Invalid registered toolchain '@local_execution_config_python//:py_toolchain': Repository '@python' is not defined

### ISSUE THREAD

**Issue by amra-lemis** [google-ai-edge/mediapipe#5672]
### OS Platform and Distribution

Ubuntu 18.04

### Programming Language and version

-

### MediaPipe version

0.10.17

### Bazel version

6.1.1

### Android SDK and NDK versions (if android)

Android SDK: 30 Android NDK: 21

### Android AAR (if android)

None

### Describe the problem

We are trying to build the Mediapipe Framework for Android using Bazel by following this link: [https://ai.google.dev/edge/mediapipe/framework/getting_started/android]

But running into below error when running: 
`bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world`

Python version used: 
3.11.5

### Complete Logs

```shell
ERROR: /mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/BUILD:35:15: 
While resolving toolchains for target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu: 
invalid registered toolchain '@local_execution_config_python//:py_toolchain':
 error loading package '@local_execution_config_python//': 
Unable to find package for @python//:defs.bzl: 
The repository '@python' could not be resolved: Repository '@python' is not defined.
```

**Comment by kuaashish** [comment]
Hi @amra-lemis,

Please review the fix provided here [as](https://github.com/google-ai-edge/mediapipe/issues/5661#issuecomment-2405813909). It should resolve the issue. We have also received confirmation from the community. Let us know if the issue persists.

Thank you!!

**Comment by amra-lemis** [comment]
Hi @kuaashish,

We've applied the fix you've given, but we are facing the below issue now. Could you please check?

ERROR: 
```
~/external/XNNPACK/BUILD.bazel:784:36: Compiling external/XNNPACK/neonbf16_prod_microkernels.c failed: (Exit 1): clang failed: error executing command (from target @XNNPACK//:neonbf16_prod_microkernels) external/androidndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -no-canonical-prefixes '--target=aarch64-linux-android21' -fdiagnostics-color -Wa,--noexecstack -faddrsig -faligned-new ... (remaining 157 arguments skipped)
 
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
clang: error: the clang compiler does not support '-march=armv8.2-a+bf16'
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
FAILED: Build did NOT complete successfully
```

**Comment by kuaashish** [comment]
Hi @amra-lemis,

Could you confirm if you've successfully built the Hello World example? Additionally, please share the full build command you are using that resulted in the error now.

Thank you!!

**Comment by schmidt-sebastian** [comment]
Please update Clang to version 18 and set the following: 

```echo "build --define=xnn_enable_avxvnniint8=false" >> .bazelrc```

With Clang 20 (untested) you can build without this flag.

**Comment by amra-lemis** [comment]
Hi @kuaashish,

Yes, we were able to successfully build the Hello World example by following this link: `https://ai.google.dev/edge/mediapipe/framework/getting_started/install`

We are now facing issue when trying to build the HandTracking Android example app using the below bazel command:
`bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu`

As suggested by @schmidt-sebastian, we've update clang version to 18 and set the following flag:
`echo "build --define=xnn_enable_avxvnniint8=false" >> .bazelrc`

Yet we are facing issues. The following error message is thrown now on running the Bazel build command:
```
ERROR: /home/luser/.cache/bazel/_bazel_luser/1215dd19034d45756c66832c821a5ffb/external/XNNPACK/BUILD.bazel:784:36: Compiling external/XNNPACK/neonbf16_prod_microkernels.c failed: (Exit 1): 
clang failed: error executing command (from target @XNNPACK//:neonbf16_prod_microkernels) external/androidndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -no-canonical-prefixes '--target=aarch64-linux-android21' -fdiagnostics-color -Wa,--noexecstack -faddrsig -faligned-new ... (remaining 157 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
clang: error: the clang compiler does not support '-march=armv8.2-a+bf16'
```

**Comment by schmidt-sebastian** [comment]
Please see here: https://github.com/google/XNNPACK/issues/3618
