### ISSUE TITLE
Q: Is it possible to only use the palm tracking model of the Hand Landmarker?

### ISSUE THREAD

**Issue by JC3** [google-ai-edge/mediapipe#5675]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Ubuntu 22.04, macOS, Windows

### MediaPipe Tasks SDK version

0.10.15

### Task name (e.g. Image classification, Gesture recognition etc.)

Hand Landmarker

### Programming Language and version (e.g. C++, Python, Java)

Python

### Question

I am reading that the Hand Landmarker first uses a fast palm detector to locate the hand before running the full hand recognition model.

Is it possible (perhaps via clever confidence threshold settings?) to *only* use the palm detector and access the detected palm positions?

The reason I ask is we're using the Hand Landmarker to detect hands but we're running it on the CPU because no GPU is available (Intel NUC11). Therefore, it's got about 90-100ms of latency. However, we're only actually interested in the palm positions anyways, so I'm wondering if there's a way to just access the faster palm detector and use that instead to improve latency. We don't need the full 21-point hand model.

Thanks!

**Comment by kuaashish** [comment]
Hi @JC3,

Please allow us sometime to discuss this with our team, We will come back with update soon. 

Thank you!!

**Comment by kuaashish** [comment]
Hi @JC3,

Based on our team discussion, it is currently not possible to use only palm tracking with our API. However, it can be achieved by modifying the graph and customizing it, followed by rebuilding the task file. Please note, we do not have documentation or examples for these steps.

Thank you!!

**Comment by JC3** [comment]
Thanks, I will look into this as soon as I can and see how far I get.

**Comment by kuaashish** [comment]
Hi @JC3,

Could you please confirm if support is no longer required from our end? If so, we can mark the issue as resolved and close it.

Thank you!!
