### ISSUE TITLE
Face landmarker on iOS 

### ISSUE THREAD

**Issue by no-1ne** [google-ai-edge/mediapipe#5684]
Current docs have no information on how to get face landmarker running on ios, 
https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker

in the repo there is  some code , can you share update on iOS support, https://github.com/google-ai-edge/mediapipe/tree/master/mediapipe/tasks/ios/vision/face_landmarker

**Comment by kuaashish** [comment]
Hi @no-1ne,

Thank you for bringing this to our attention. We have informed our team about the issue, and the Face Landmarker documentation has now been updated. You can review the changes in this section: https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker/ios. Please let us know if we can close this issue and mark it resolved internally.
