### ISSUE TITLE
legacy_calculator_support.cc(21): error C2370: “current_”: 重定义

### ISSUE THREAD

**Issue by leezeng** [google-ai-edge/mediapipe#5691]
### OS Platform and Distribution

windows 10 

### Compiler version

vc2022

### Programming Language and version

C++ 

### Android AAR (if android)

None

### Describe the problem

A bug happened!

### Complete Logs

```shell
Can you help me?


legacy_calculator_support.cc
mediapipe/framework/legacy_calculator_support.cc(21): error C2370: “current_”: 重定义；不同的存储类
.\mediapipe/framework/legacy_calculator_support.h(65): note: 参见“current_”的声明
mediapipe/framework/legacy_calculator_support.cc(25): error C2370: “current_”: 重定义；不同的存储类
.\mediapipe/framework/legacy_calculator_support.h(65): note: 参见“current_”的声明
Target //mediapipe/examples/desktop/face_detection:face_detection_cpu failed to build
INFO: Elapsed time: 484.080s, Critical Path: 285.41s
```

**Comment by leezeng** [comment]
windows 10 mediapipe 0.10.14 
\mediapipe-0.10.14\mediapipe\framework\legacy_calculator_support.cc

修改前
#ifndef __APPLE__
    ABSL_CONST_INIT
#endif
修改后
#ifndef __APPLE__
    //ABSL_CONST_INIT
#endif 

可解决

**Comment by kuaashish** [comment]
Hi @leezeng,

Could you please provide the complete steps you're following from our documentation or standalone code? This will help us understand the issue better, and if needed, we will attempt to reproduce it on our end.

Thank you!!
