### ISSUE TITLE
Face Landmarker slower than face mesh (legacy solution)

### ISSUE THREAD

**Issue by RansomBroker** [google-ai-edge/mediapipe#5699]
face landmarker from task vision is slower like not responsive on the face, but  legacy solution is more responsive i use javascript

**Comment by kuaashish** [comment]
Hi @RansomBroker,

Thank you for bringing this to our attention. We are aware of the issue noted here: https://github.com/google-ai-edge/mediapipe/issues/5130. Unfortunately, there’s limited action we can take on the legacy face mesh. Our current focus is on continuously improving the new Face Landmarker Task API. We recommend tracking the referenced issue for any updates, and we suggest closing this issue for now as we work on enhancements in the new API.
