### ISSUE TITLE
mediapipe 0.10.3 is not supported on this platform，请问这是什么原因啊？我该怎么解决呢？安装mediapipe 0.10.315也是提示这个，我的系统是macOS14.7

### ISSUE THREAD

**Issue by shalafeimao** [google-ai-edge/mediapipe#5703]
This template is for miscellaneous issues not covered by the other issue categories

For questions on how to work with MediaPipe, or support for problems that are not verified bugs in MediaPipe, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mediapipe) and [Slack](https://mediapipe.page.link/joinslack) communities.

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/google/mediapipe/security).

**Comment by kuaashish** [comment]
Hi @shalafeimao,

We are having difficulty understanding the issue clearly. Could you please provide the full details in standard English so we can assist you more effectively?

Thank you!!

**Comment by shalafeimao** [comment]
I said that the dependency package of mediapipe was missing in the installation of stable diffusion controlnet, so I went to download this dependency and downloaded it successfully. But after downloading, when I went to check the dependency conflict, it was displayed on Mac that mediapipe 0.10.3 is not supported on this platform. I installed all the mediapipe versions and it was prompted "is not supported on this platform". I don't know what caused it. My macOS is 14.7.Can you help me?

**Comment by shalafeimao** [comment]
> Hi @shalafeimao,
> 
> We are having difficulty understanding the issue clearly. Could you please provide the full details in standard English so we can assist you more effectively?
> 
> Thank you!!

I said that the dependency package of mediapipe was missing in the installation of stable diffusion controlnet, so I went to download this dependency and downloaded it successfully. But after downloading, when I went to check the dependency conflict, it was displayed on Mac that mediapipe 0.10.3 is not supported on this platform. I installed all the mediapipe versions and it was prompted "is not supported on this platform". I don't know what caused it. My macOS is 14.7.Can you help me?

**Comment by kuaashish** [comment]
Hi @shalafeimao,

Could you please let us know the operating system and Python version you are using? Additionally, could you specify the exact steps you are following from our documentation (https://ai.google.dev/edge/mediapipe/solutions/guide) along with the complete error logs you are encountering? You may also use the provided [template](https://github.com/google-ai-edge/mediapipe/issues/new?assignees=&labels=type%3Abug&projects=&template=16-bug-issue-template.yaml) to share these details with us.

**Comment by shalafeimao** [comment]
> 嗨@shalafeimao，
> 
> 您能告诉我们您正在使用的操作系统和Python版本吗？此外，您能从我们的文档（https://ai.google.dev/edge/mediapipe/solutions/guide）中具体说明您遵循的确切步骤，以及您遇到的完整错误日志吗？您也可以使用提供的[模板](https://github.com/google-ai-edge/mediapipe/issues/new?assignees=&labels=type%3Abug&projects=&template=16-bug-issue-template.yaml)与我们分享这些详细信息。

My python is 3.10.15, my system is macOS14.7, MacM2

**Comment by kuaashish** [comment]
Hi @shalafeimao.

We are still unable to follow the steps. Could you please review the complete installation steps and share the error logs as well?
