### ISSUE TITLE
ARCore camera work with the mediapipe in android phone will hang ( develop platform is unity)

### ISSUE THREAD

**Issue by boywai** [google-ai-edge/mediapipe#5713]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 11, develop to android phone

### MediaPipe Tasks SDK version

V0.15.0

### Task name (e.g. Image classification, Gesture recognition etc.)

Hand landmark and Gesture recognition

### Programming Language and version (e.g. C++, Python, Java)

C#

### Describe the actual behavior

if i use AR Core camera( attach with the mediapipe plugin) to do the plane detection, will hang

### Describe the expected behaviour

the camera able to scan the plane to place the 3D model and then can detect the hand gesture to interact with the 3D model by the ARCore camera with the MediaPipe

### Standalone code/steps you may have used to try to get what you need

```shell
1. Setup the ARCore Scene and add the XR Origin(AR mobile)
2. import the mediapipe and attach the ARCore Camera on Canvas
3. build and run in android phone
4. scan the floor to plane will replicate the hang issues
```

**Comment by kuaashish** [comment]
Hi @boywai,

Unfortunately, we do not officially support Unity and are unable to assist with this issue. If you are using a community-based example or library, we recommend raising the issue on the relevant repository or forum for further assistance. We apologize for the inconvenience but can not provide additional support on this matter.

Thank you!!
