### ISSUE TITLE
When I call the close method, the browser process freezes

### ISSUE THREAD

**Issue by ChinDer** [google-ai-edge/mediapipe#5718]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

web

### Programming Language and version

0.10.0

### Solution

handLandmarker

### Describe the actual behavior

 the browser process freezes

### Describe the expected behaviour

can close

### Standalone code/steps you may have used to try to get what you need

```shell
in your example


const createHandLandmarker = async () => {
  const vision = await FilesetResolver.forVisionTasks(
    "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.0/wasm"
  );
  handLandmarker = await HandLandmarker.createFromOptions(vision, {
    baseOptions: {
      modelAssetPath: `https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task`,
      delegate: "GPU"
    },
    runningMode: runningMode,
    numHands: 2
  });

  window.Test = handLandmarker
  demosSection.classList.remove("invisible");
};


setTimeout(() => {handLandmarker.close()}, 100000)
```

### Other info / Complete Logs

```shell
the browser process freezes
```

**Comment by ChinDer** [comment]
i create a demo https://codepen.io/Chander-chen/pen/eYqPRGa
![image](https://github.com/user-attachments/assets/f4f6e649-8c37-4250-9ac6-8602ab133cb5)

**Comment by ChinDer** [comment]
![image](https://github.com/user-attachments/assets/048ae507-a282-42b9-875e-1651b0af3a8c)

**Comment by kuaashish** [comment]
Hi @ChinDer,

It appears you are using an older version, 0.10.0. Could you try the latest version [0.10.18](https://www.npmjs.com/package/@mediapipe/tasks-vision) and let us know if the issue persists? Also, please let us know which browser you are using.

Thank you!!
