### ISSUE TITLE
mediapipe/tasks-genai for web uses a Deprecated function "requestAdapterInfo" caused  failed to run with new Chrome Browser

### ISSUE THREAD

**Issue by kdshk** [google-ai-edge/mediapipe#5720]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 11, Chrome V130

### Browser and version if the issue happens on browser

Version 132.0.6807.0 (Official Build)

### Programming Language and version

javascript

### MediaPipe version

0.10.18

### Solution

mediapipe/tasks-genai

### Describe the actual behavior

exception when call LlmInference.createFromOptions TypeError: a.requestAdapterInfo is not a functio

### Describe the expected behaviour

should be success initialize the genAI task

### Standalone code/steps you may have used to try to get what you need

```shell
javascript throw exception when call createFromOptions with error information "TypeError: a.requestAdapterInfo is not a function"
await LlmInference.createFromOptions(genaiFileset, {
                baseOptions: {
                    modelAssetPath: this.modelPath
                },
                maxTokens: 32000,
                topK: 40,
                temperature: 0.8,
                randomSeed: 101,
                loraRanks: [4, 8, 16, 64]
            });
```

### Other info / Complete Logs

```shell
sidepanel-BtA2uG1z.js:10 Experimental Chromium WGSL subgroup support detected. Enabling this feature in the inference engine.
la @ sidepanel-BtA2uG1z.js:10Understand this warningAI
sidepanel-BtA2uG1z.js:18 TypeError: a.requestAdapterInfo is not a function
    at Sn.Z (sidepanel-BtA2uG1z.js:10:49854)
    at async He.createFromOptions (sidepanel-BtA2uG1z.js:11:6585)
    at async I8.initialize (sidepanel-BtA2uG1z.js:18:224)
    at async W8.initialize (sidepanel-BtA2uG1z.js:18:184835)
```

**Comment by kuaashish** [comment]
Hi @kdshk,

Could you please share the exact steps you are following from our documentation? This will help us understand the issue more clearly and assist you better.

Thank you!!

**Comment by kdshk** [comment]
> Hi @kdshk,
> 
> Could you please share the exact steps you are following from our documentation? This will help us understand the issue more clearly and assist you better.
> 
> Thank you!!

Hi I followed the sample here "https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference/web_js" and used "npm install @mediapipe/tasks-genai" to import gen ai library.  Referred the  sample code to initialize LlmInference, then the Chrome browser(132.0.6807.0). throw the error "TypeError: a.requestAdapterInfo is not a function". After visit "https://developer.mozilla.org/en-US/docs/Web/API/GPUAdapter/requestAdapterInfo" it seems requestAdapterInfo is "Deprecated" while @mediapipe/tasks-genai (0.10.18) is still using it. Simply user the new info object in GPUAdapter manually can have this issue patched. 

 const genai = await FilesetResolver.forGenAiTasks(
    // path/to/wasm/root
    "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-genai@latest/wasm"
);
llmInference = await LlmInference.createFromOptions(genai, {
    baseOptions: {
        modelAssetPath: '/assets/gemma-2b-it-gpu-int4.bin'
    },
    maxTokens: 1000,
    topK: 40,
    temperature: 0.8,
    randomSeed: 101
});

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

Could you please look into this issue? 

Thank you!!

**Comment by galdaka** [comment]
Same problem here!!

**Comment by Linchenn** [comment]
Are you using the latest npm package? the fix should have been checked in
