### ISSUE TITLE
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. mediapipe 0.10.18 requires protobuf<5,>=4.25.3, but you have protobuf 5.28.3 which is incompatible.

### ISSUE THREAD

**Issue by fish-lxh** [google-ai-edge/mediapipe#5721]
This template is for miscellaneous issues not covered by the other issue categories

For questions on how to work with MediaPipe, or support for problems that are not verified bugs in MediaPipe, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mediapipe) and [Slack](https://mediapipe.page.link/joinslack) communities.

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/google/mediapipe/security).

**Comment by kuaashish** [comment]
Hi @fish-lxh,

This update aligns with the community's needs for their specific use cases. We have updated the Protobuf [dependency](https://github.com/google/mediapipe/commit/7e4370113436a3ebce9fb3a158e9d25821f99312) to version >=4.25.3 and <5. Please ensure you install a supported Protobuf version to proceed with MediaPipe installation.

Thank you!!

**Comment by hellcoldby** [comment]
path: ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers,
find **mesh_graphormer.py**  and    **mediapipe_face.py**     search `protobuf`  about at line:17   
delet "upgrde" -----> line:17 --    run_script([sys.executable, '-s', '-m', 'pip', 'install', 'protobuf'])

or  comment out --- `#run_script([sys.executable, '-s', '-m', 'pip', 'install', 'protobuf']) `

**Comment by kuaashish** [comment]
Hi @fish-lxh,

Can you please go through the [above](https://github.com/google-ai-edge/mediapipe/issues/5721#issuecomment-2463760827) and let us know the status of the issue? 

Thank you!!

**Comment by Lo7ong** [comment]
Test to meet minimum dependency compatibility。
mediapipe==0.10.18（latest version）
protobuf==4.25.5
grpcio-status==1.62.3

**Comment by metal3d** [comment]
Can the authors make the project compatible with protobuf>=5?

It breaks on ComfyUI as others packages need protobuf too. We need to manually downgrade `grpcio-status` to make it work.

It'a pitty, mediapipe is very useful.
