### ISSUE TITLE
Can't install mediapipe in python 3.7.9 

### ISSUE THREAD

**Issue by dommerts35** [google-ai-edge/mediapipe#5733]
### OS Platform and Distribution

Windows 7

### Programming Language and version

Python 3.7.9

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

Any mediapipe version

### Android AAR (if android)

None

### Describe the problem

Hi. Im trying to install mediapipe to try a YT project, but mediapipe installation is not working at all. I have tried Python 3.8.10, 3.8 and 3.7.9, but nothing seems to work.

### Complete Logs

```shell
(.venv) PS C:\Users\USUARIO\OneDrive\Desktop\lenguaje_señas_2> pip install mediapipe
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
(.venv) PS C:\Users\USUARIO\OneDrive\Desktop\lenguaje_señas_2> py --version
Python 3.7.9
```

**Comment by dommerts35** [comment]
Okay, somehow I managed to get Mediapipe to be installed, but it doesnt work anyway.

Traceback (most recent call last):
  File "c:/Users/USUARIO/OneDrive/Desktop/lenguaje_señas_2/data.py", line 3, in <module>
    import seguimientoManos as sM
  File "c:\Users\USUARIO\OneDrive\Desktop\lenguaje_señas_2\seguimientoManos.py", line 3, in <module>
    import mediapipe as mp
  File "C:\Users\USUARIO\OneDrive\Desktop\lenguaje_señas_2\.venv\lib\site-packages\mediapipe\__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "C:\Users\USUARIO\OneDrive\Desktop\lenguaje_señas_2\.venv\lib\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import model_ckpt_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

**Comment by kuaashish** [comment]
Hi @dommerts35,

It seems you are using an unsupported Python version. The supported versions are now 3.9 to 3.12, as mentioned [here](https://ai.google.dev/edge/mediapipe/solutions/setup_python#supported_platforms_and_versions). Previously, versions 3.8 to 3.11 were supported, but this has recently been updated.

Thank you!!

**Comment by dommerts35** [comment]
Hi, thanks for responding. Yeah, so I updated it to the 3.12 versión, but Even then, it doesnt work.

**Comment by kuaashish** [comment]
Hi @dommerts35,

Thank you for your prompt response. It seems there might be an issue with the virtual environment. Could you try building Python without it and let us know if it works? If the issue persists, please share the complete error logs you are encountering.

**Comment by dommerts35** [comment]
Yeah, I used the CMD and the virtual environment. The env. had problemas, but the CMD managed to download the mediapipe library. So I put the library intro the env. Libs, and try using it.

**Comment by dommerts35** [comment]
I Will show You the logs, just a sec.

**Comment by dommerts35** [comment]
Traceback (most recent call last):
  File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python313\Lib\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import model_ckpt_util
  File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python313\Lib\mediapipe\__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "C:\Users\USUARIO\AppData\Local\Programs\Python\Python313\Lib\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import model_ckpt_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

**Comment by dommerts35** [comment]
I have installed Visual Studio 2022 and Tools in case i needed it, but it still has this problem.

**Comment by dommerts35** [comment]
PS C:\Users\USUARIO\OneDrive\Desktop\lenguaje_señas_3> py --version
Python 3.13.0

**Comment by dommerts35** [comment]
Im not using a env right now, in case that is important to know.

**Comment by dommerts35** [comment]
oh wait i just noticed the version is too new, sorry
i will try installing a 3.12 version right now

**Comment by dommerts35** [comment]
IT WORKED! Sorry for the inconviniences, i installed 3.12.6 and it finally worked. Thanks for pointing out the versions.
