### ISSUE TITLE
MediaPipe error in Chrome (requestAdapterInfo)

### ISSUE THREAD

**Issue by maudnals** [google-ai-edge/mediapipe#5739]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

MacOS Sonoma 14.7

### Browser and version if the issue happens on browser

Chrome 131.0.6778.69 

### Programming Language and version

JavaScript

### MediaPipe version

@mediapipe/tasks-genai": ^0.10.18

### Solution

MediaPipe LLM Inference API

### Describe the actual behavior

TypeError: n.requestAdapterInfo is not a function

### Describe the expected behaviour

The Gen AI task runs properly

### Standalone code/steps you may have used to try to get what you need

Refer to the bug reproduction: https://github.com/maudnals/mediapipe-request-adapter

### Other info / Complete Logs

```shell
* The issue can be observed in Chrome (both and Canary) and Firefox (including Nightly).
* Could the removal of `requestAdapterInfo` in Chrome (https://chromestatus.com/feature/5140787340509184) be a reason?  This wouldn't directly explain the issue in Firefox though.
* requestAdapterInfo is marked as deprecated: https://developer.mozilla.org/en-US/docs/Web/API/GPUAdapter/requestAdapterInfo

See full repro: 
https://github.com/maudnals/mediapipe-request-adapter
```

**Comment by kuaashish** [comment]
Hi @maudnals,

Could you please share the complete instructions you are following from our documentation to help us better understand the issue? Additionally, providing the standalone code and complete error logs you are using would be very helpful.

Thank you!!

**Comment by beaufortfrancois** [comment]
This error is fixed in version 0.10.19-rc.20241118. You can try it by updating your code with the following code

```js
 import {
  FilesetResolver,
  LlmInference,
} from 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-genai@0.10.19-rc.20241118';
```

**Comment by kuaashish** [comment]
Hi @beaufortfrancois,

Thank you for pointing out there, @maudnals, Can you please use nightly one as mentioned [above](https://github.com/google-ai-edge/mediapipe/issues/5739#issuecomment-2485089130) and let us know the status if you are now able to run or still facing the issue?

**Comment by maudnals** [comment]
@beaufortfrancois @kuaashish 
I just tried it, I confirm that the error is fixed in 0.10.19-rc.20241118.
Thank you!

@kuaashish Would you have an estimate for when 0.10.19 will ship on npm?

**Comment by maudnals** [comment]
Noted. Thanks!

**Comment by kuaashish** [comment]
Hi @maudnals,

A new version of MediaPipe, [0.10.20](https://www.npmjs.com/package/@mediapipe/tasks-vision), is now available. Please check it out. 

Thank you!!
