### ISSUE TITLE
mediapipe not GPU accelerated

### ISSUE THREAD

**Issue by jpitalopez** [google-ai-edge/mediapipe#5741]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Linnux Ubuntu

### MediaPipe Tasks SDK version

0.10.15

### Task name (e.g. Image classification, Gesture recognition etc.)

Face detection

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

Executes on CPU

### Describe the expected behaviour

Executes on CPU

### Standalone code/steps you may have used to try to get what you need

I just installed mediapipe with: $ pip install mediapie

**Comment by kuaashish** [comment]
Hi @jpitalopez,

Closing this issue as Duplicate of https://github.com/google-ai-edge/mediapipe/issues/5742, Please follow that issue for update. 

Thank you!!
