### ISSUE TITLE
Error in fail: interpreter_path must be an absolute path

### ISSUE THREAD

**Issue by ligaoqi2** [google-ai-edge/mediapipe#5746]
### OS Platform and Distribution

windows11

### Programming Language and version

c++

### Installed using virtualenv? pip? Conda?(if python)

pip

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

3.4.10

### Describe the problem

Error in fail: interpreter_path must be an absolute path

### Complete Logs

```shell
Build and run Hello world is OK, but build Handtrack,facemesh... will catch

ERROR: C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/local_execution_config_python/BUILD:16:11: in py_runtime rule @@local_execution_config_python//:py3_runtime:
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/python/py_runtime_rule.bzl", line 40, column 17, in _py_runtime_impl
Error in fail: interpreter_path must be an absolute path

here is my command:
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D://python//python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
```

**Comment by ligaoqi2** [comment]
The other problem appear during the build process

ERROR: C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/llvm-raw/utils/bazel/configure.bzl:60:13: An error occurred during the fetch of repository 'llvm-project':
   Traceback (most recent call last):
        File "C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/llvm-raw/utils/bazel/configure.bzl", line 150, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/llvm-raw/utils/bazel/configure.bzl", line 60, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'D:/python/python.exe C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/llvm-raw --overlay C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 256
stdout:

stderr:
Timed out
ERROR: no such package '@@llvm-project//mlir': Failed to execute overlay script: 'D:/python/python.exe C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/llvm-raw --overlay C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 256
stdout:

stderr:
Timed out
ERROR: C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/org_tensorflow/tensorflow/compiler/mlir/lite/experimental/remat/BUILD:24:11: @@org_tensorflow//tensorflow/compiler/mlir/lite/experimental/remat:metadata_util depends on @@org_tensorflow//tensorflow/compiler/mlir/lite:control_edges in repository @@org_tensorflow which failed to fetch. no such package '@@llvm-project//mlir': Failed to execute overlay script: 'D:/python/python.exe C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/llvm-raw --overlay C:/users/ligaoqi/_bazel_ligaoqi/kmrly2eg/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 256
stdout:

stderr:
Timed out
ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu' failed; build aborted: Analysis failed

any solution?

**Comment by willyweichen** [comment]
I think i have smae problem:

Python 3.10.14
BAZEL_VS=C:\Program Files\Microsoft Visual Studio\2022\Community
BAZEL_VC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC
BAZEL_VC_FULL_VERSION=14.42.34433
BAZEL_WINSDK_FULL_VERSION=10.0.22621.3233

C:\Mediapipe\mediapipe-0.10.15>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:/Users/YAO/anaconda3/python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
INFO: Repository llvm-project instantiated at:
  C:/mediapipe/mediapipe-0.10.15/WORKSPACE:589:14: in <toplevel>
  C:/users/yao/_bazel_yao/wptqrqd4/external/org_tensorflow/tensorflow/workspace2.bzl:942:21: in workspace
  C:/users/yao/_bazel_yao/wptqrqd4/external/org_tensorflow/tensorflow/workspace2.bzl:462:15: in _tf_repositories
  C:/users/yao/_bazel_yao/wptqrqd4/external/org_tensorflow/third_party/llvm/setup.bzl:19:19: in llvm_setup
Repository rule llvm_configure defined at:
  C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/configure.bzl:181:33: in <toplevel>
ERROR: C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/configure.bzl:60:13: An error occurred during the fetch of repository 'llvm-project':
   Traceback (most recent call last):
        File "C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/configure.bzl", line 150, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/configure.bzl", line 60, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'C:/Users/YAO/anaconda3/python.exe C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw --overlay C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 99, in <module>
    main(parse_arguments())
  File "C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 85, in main
    _symlink_abs(
  File "C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 69, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] �Τ�ݨS���o���S���v���C: 'C:\\users\\yao\\_bazel_yao\\wptqrqd4\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\yao\\_bazel_yao\\wptqrqd4\\external\\llvm-project\\.bazelignore'

ERROR: no such package '@@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/YAO/anaconda3/python.exe C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw --overlay C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 99, in <module>
    main(parse_arguments())
  File "C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 85, in main
    _symlink_abs(
  File "C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 69, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] �Τ�ݨS���o���S���v���C: 'C:\\users\\yao\\_bazel_yao\\wptqrqd4\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\yao\\_bazel_yao\\wptqrqd4\\external\\llvm-project\\.bazelignore'

ERROR: C:/users/yao/_bazel_yao/wptqrqd4/external/org_tensorflow/tensorflow/compiler/mlir/lite/experimental/remat/BUILD:24:11: @@org_tensorflow//tensorflow/compiler/mlir/lite/experimental/remat:metadata_util depends on @@org_tensorflow//tensorflow/compiler/mlir/lite:control_edges in repository @@org_tensorflow which failed to fetch. no such package '@@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/YAO/anaconda3/python.exe C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw --overlay C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 99, in <module>
    main(parse_arguments())
  File "C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 85, in main
    _symlink_abs(
  File "C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 69, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] �Τ�ݨS���o���S���v���C: 'C:\\users\\yao\\_bazel_yao\\wptqrqd4\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\yao\\_bazel_yao\\wptqrqd4\\external\\llvm-project\\.bazelignore'

ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.658s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
FAILED:
    Fetching repository @@com_google_mediapipe_hand_landmark_full_tflite; starting
    Fetching repository @@com_google_mediapipe_palm_detection_full_tflite; starting
    Fetching repository @@eigen_archive; starting
    Fetching repository @@flatbuffers; starting
    Fetching repository @@com_github_grpc_grpc; starting
    Fetching https://storage.googleapis.com/.../eigen-33d0937c6bdf5ec999939fb17f2a553183d14a74.tar.gz; 1.1 MiB (40.4%)
    Fetching https://storage.googleapis.com/.../palm_detection_full.tflite?generation=1662745358034050; 799.8 KiB (35.0%)
    Fetching https://storage.googleapis.com/mediapipe-assets/hand_landmark_full.tflite?generation=1661875760968579

**Comment by ligaoqi2** [comment]
> I think i have smae problem:
> 
> Python 3.10.14 BAZEL_VS=C:\Program Files\Microsoft Visual Studio\2022\Community BAZEL_VC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC BAZEL_VC_FULL_VERSION=14.42.34433 BAZEL_WINSDK_FULL_VERSION=10.0.22621.3233
> 
> C:\Mediapipe\mediapipe-0.10.15>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:/Users/YAO/anaconda3/python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu INFO: Repository llvm-project instantiated at: C:/mediapipe/mediapipe-0.10.15/WORKSPACE:589:14: in C:/users/yao/_bazel_yao/wptqrqd4/external/org_tensorflow/tensorflow/workspace2.bzl:942:21: in workspace C:/users/yao/_bazel_yao/wptqrqd4/external/org_tensorflow/tensorflow/workspace2.bzl:462:15: in _tf_repositories C:/users/yao/_bazel_yao/wptqrqd4/external/org_tensorflow/third_party/llvm/setup.bzl:19:19: in llvm_setup Repository rule llvm_configure defined at: C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/configure.bzl:181:33: in ERROR: C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/configure.bzl:60:13: An error occurred during the fetch of repository 'llvm-project': Traceback (most recent call last): File "C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/configure.bzl", line 150, column 25, in _llvm_configure_impl _overlay_directories(repository_ctx) File "C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/configure.bzl", line 60, column 13, in _overlay_directories fail(("Failed to execute overlay script: '{cmd}'\n" + Error in fail: Failed to execute overlay script: 'C:/Users/YAO/anaconda3/python.exe C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw --overlay C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/llvm-project-overlay --target .' Exited with code 1 stdout:
> 
> stderr: Traceback (most recent call last): File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 99, in main(parse_arguments()) File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 85, in main _symlink_abs( File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 69, in _symlink_abs os.symlink(os.path.abspath(from_path), os.path.abspath(to_path)) OSError: [WinError 1314] �Τ�ݨS���o���S���v���C: 'C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\llvm-project-overlay\.bazelignore' -> 'C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-project\.bazelignore'
> 
> ERROR: no such package '@@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/YAO/anaconda3/python.exe C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw --overlay C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/llvm-project-overlay --target .' Exited with code 1 stdout:
> 
> stderr: Traceback (most recent call last): File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 99, in main(parse_arguments()) File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 85, in main _symlink_abs( File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 69, in _symlink_abs os.symlink(os.path.abspath(from_path), os.path.abspath(to_path)) OSError: [WinError 1314] �Τ�ݨS���o���S���v���C: 'C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\llvm-project-overlay\.bazelignore' -> 'C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-project\.bazelignore'
> 
> ERROR: C:/users/yao/_bazel_yao/wptqrqd4/external/org_tensorflow/tensorflow/compiler/mlir/lite/experimental/remat/BUILD:24:11: @@org_tensorflow//tensorflow/compiler/mlir/lite/experimental/remat:metadata_util depends on @@org_tensorflow//tensorflow/compiler/mlir/lite:control_edges in repository @@org_tensorflow which failed to fetch. no such package '@@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/YAO/anaconda3/python.exe C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw --overlay C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/llvm-project-overlay --target .' Exited with code 1 stdout:
> 
> stderr: Traceback (most recent call last): File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 99, in main(parse_arguments()) File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 85, in main _symlink_abs( File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 69, in _symlink_abs os.symlink(os.path.abspath(from_path), os.path.abspath(to_path)) OSError: [WinError 1314] �Τ�ݨS���o���S���v���C: 'C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\llvm-project-overlay\.bazelignore' -> 'C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-project\.bazelignore'
> 
> ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu' failed; build aborted: Analysis failed INFO: Elapsed time: 0.658s, Critical Path: 0.01s INFO: 1 process: 1 internal. ERROR: Build did NOT complete successfully FAILED: Fetching repository @@com_google_mediapipe_hand_landmark_full_tflite; starting Fetching repository @@com_google_mediapipe_palm_detection_full_tflite; starting Fetching repository @@eigen_archive; starting Fetching repository @@flatbuffers; starting Fetching repository @@com_github_grpc_grpc; starting Fetching https://storage.googleapis.com/.../eigen-33d0937c6bdf5ec999939fb17f2a553183d14a74.tar.gz; 1.1 MiB (40.4%) Fetching https://storage.googleapis.com/.../palm_detection_full.tflite?generation=1662745358034050; 799.8 KiB (35.0%) Fetching https://storage.googleapis.com/mediapipe-assets/hand_landmark_full.tflite?generation=1661875760968579

I think you could build command as administrator, because creating symlink needs administrator privileges

**Comment by ligaoqi2** [comment]
> I think i have smae problem:
> 
> Python 3.10.14 BAZEL_VS=C:\Program Files\Microsoft Visual Studio\2022\Community BAZEL_VC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC BAZEL_VC_FULL_VERSION=14.42.34433 BAZEL_WINSDK_FULL_VERSION=10.0.22621.3233
> 
> C:\Mediapipe\mediapipe-0.10.15>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:/Users/YAO/anaconda3/python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu INFO: Repository llvm-project instantiated at: C:/mediapipe/mediapipe-0.10.15/WORKSPACE:589:14: in C:/users/yao/_bazel_yao/wptqrqd4/external/org_tensorflow/tensorflow/workspace2.bzl:942:21: in workspace C:/users/yao/_bazel_yao/wptqrqd4/external/org_tensorflow/tensorflow/workspace2.bzl:462:15: in _tf_repositories C:/users/yao/_bazel_yao/wptqrqd4/external/org_tensorflow/third_party/llvm/setup.bzl:19:19: in llvm_setup Repository rule llvm_configure defined at: C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/configure.bzl:181:33: in ERROR: C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/configure.bzl:60:13: An error occurred during the fetch of repository 'llvm-project': Traceback (most recent call last): File "C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/configure.bzl", line 150, column 25, in _llvm_configure_impl _overlay_directories(repository_ctx) File "C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/configure.bzl", line 60, column 13, in _overlay_directories fail(("Failed to execute overlay script: '{cmd}'\n" + Error in fail: Failed to execute overlay script: 'C:/Users/YAO/anaconda3/python.exe C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw --overlay C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/llvm-project-overlay --target .' Exited with code 1 stdout:
> 
> stderr: Traceback (most recent call last): File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 99, in main(parse_arguments()) File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 85, in main _symlink_abs( File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 69, in _symlink_abs os.symlink(os.path.abspath(from_path), os.path.abspath(to_path)) OSError: [WinError 1314] �Τ�ݨS���o���S���v���C: 'C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\llvm-project-overlay\.bazelignore' -> 'C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-project\.bazelignore'
> 
> ERROR: no such package '@@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/YAO/anaconda3/python.exe C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw --overlay C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/llvm-project-overlay --target .' Exited with code 1 stdout:
> 
> stderr: Traceback (most recent call last): File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 99, in main(parse_arguments()) File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 85, in main _symlink_abs( File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 69, in _symlink_abs os.symlink(os.path.abspath(from_path), os.path.abspath(to_path)) OSError: [WinError 1314] �Τ�ݨS���o���S���v���C: 'C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\llvm-project-overlay\.bazelignore' -> 'C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-project\.bazelignore'
> 
> ERROR: C:/users/yao/_bazel_yao/wptqrqd4/external/org_tensorflow/tensorflow/compiler/mlir/lite/experimental/remat/BUILD:24:11: @@org_tensorflow//tensorflow/compiler/mlir/lite/experimental/remat:metadata_util depends on @@org_tensorflow//tensorflow/compiler/mlir/lite:control_edges in repository @@org_tensorflow which failed to fetch. no such package '@@llvm-project//mlir': Failed to execute overlay script: 'C:/Users/YAO/anaconda3/python.exe C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw --overlay C:/users/yao/_bazel_yao/wptqrqd4/external/llvm-raw/utils/bazel/llvm-project-overlay --target .' Exited with code 1 stdout:
> 
> stderr: Traceback (most recent call last): File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 99, in main(parse_arguments()) File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 85, in main _symlink_abs( File "C:\users\yao_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\overlay_directories.py", line 69, in _symlink_abs os.symlink(os.path.abspath(from_path), os.path.abspath(to_path)) OSError: [WinError 1314] �Τ�ݨS���o���S���v���C: 'C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-raw\utils\bazel\llvm-project-overlay\.bazelignore' -> 'C:\users\yao\_bazel_yao\wptqrqd4\external\llvm-project\.bazelignore'
> 
> ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu' failed; build aborted: Analysis failed INFO: Elapsed time: 0.658s, Critical Path: 0.01s INFO: 1 process: 1 internal. ERROR: Build did NOT complete successfully FAILED: Fetching repository @@com_google_mediapipe_hand_landmark_full_tflite; starting Fetching repository @@com_google_mediapipe_palm_detection_full_tflite; starting Fetching repository @@eigen_archive; starting Fetching repository @@flatbuffers; starting Fetching repository @@com_github_grpc_grpc; starting Fetching https://storage.googleapis.com/.../eigen-33d0937c6bdf5ec999939fb17f2a553183d14a74.tar.gz; 1.1 MiB (40.4%) Fetching https://storage.googleapis.com/.../palm_detection_full.tflite?generation=1662745358034050; 799.8 KiB (35.0%) Fetching https://storage.googleapis.com/mediapipe-assets/hand_landmark_full.tflite?generation=1661875760968579

The problem is solved by building mediapipe 0.10.10, maybe there are some problems with latest version.

**Comment by ligaoqi2** [comment]
this is my building record. 
[Process](https://blog.csdn.net/IT_learner_lgq/article/details/143972198)

the result is:

<img width="212" alt="0911317fea394bc5a567fa5d3eeda145" src="https://github.com/user-attachments/assets/b30a99f7-1d6c-450f-b4fd-ed82dfc4b2ba">

**Comment by willyweichen** [comment]
@ligaoqi2, Thanks for the reply, btw, do you know is it matter to use visual studio 2019 and visual studio 2022 for building the project?

**Comment by ligaoqi2** [comment]
Actually, I think you can use any of them for the build. I just built it following the official recommendation for visual studio 2019 Buildtools. 

> @ligaoqi2, Thanks for the reply, btw, do you know is it matter to use visual studio 2019 and visual studio 2022 for building the project?
