### ISSUE TITLE
MacBook Pro (Retina, Mid 2012) - Catalina 10.15.7

### ISSUE THREAD

**Issue by pilipicus** [google-ai-edge/mediapipe#5752]
### OS Platform and Distribution

Mac Pro Catalina 10.15.7

### Programming Language and version

C++

### MediaPipe version

0.10.19

### XCode and Tulsi versions (if iOS)

Version 12.4 

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.10.0

### Describe the problem

The provided examples do not run

### Complete Logs

```shell
My configuration: 
Bazelisk version: 1.24.0
Mediapipe version: 0.10.19
opencv_version: 4.10.0
Xcode version: 1.24.0
clang version: Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix

I've followed the guide for MacOS: https://ai.google.dev/edge/mediapipe/framework/getting_started/install.md#installing_on_macos  and downloaded from git: https://github.com/google/mediapipe.git the examples.


The "HelloWorld" example works. Instead all the others don't! 

To run "HelloWorld" I do this:
$ export GLOG_logtostderr=1

# if you are running on Linux desktop with CPU only
$ bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/hello_world:hello_world

I0000 00:00:1732381130.229285 8588331 hello_world.cc:58] Hello World!
I0000 00:00:1732381130.229467 8588331 hello_world.cc:58] Hello World!
...


To run "hand_tracking", that doesn't work at the I do this:

bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu --verbose_failures --sandbox_debug

Th error that I receive is: 
clang: error: unknown argument: '-mavxvnni'
Error in child process '/usr/bin/xcrun'. 1
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
INFO: Elapsed time: 36.360s, Critical Path: 35.94s
INFO: 212 processes: 128 internal, 84 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by kalyan2789g** [comment]
Hi @pilipicus,

Could you please confirm the latest version of the OpenCv in your system? Currently Mediapipe supports OpenCv v4.

Thanks,
@kalyan2789g

**Comment by kuaashish** [comment]
Hi @pilipicus,

Could you please execute the following command to disable "avxvnni" as below and update Clang to version 18.0?

`echo "build --define=xnn_enable_avxvnni=false" >> .bazelrc`

Thank you!!

**Comment by pilipicus** [comment]
Hi @kalyan2789g,

I've installed the version **18.1** because the **18.0** seems not being available or I couldn't find it:

clang --version

clang version 18.1.0rc
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /usr/local/llvm-18.1.0/bin

After, I moved to the folder **mediapipe**, I run the command echo "build --define=xnn_enable_avxvnni=false" >> .bazelrc and I run again the command bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu --verbose_failures --sandbox_debug


The error that I receive Is still the same:
error: unknown argument: '-mavx512fp16'
Error in child process '/usr/bin/xcrun'. 1
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build

Here the screenshot of the error:
![error (1)](https://github.com/user-attachments/assets/a059749f-8201-4d59-bb3b-937925ad3271)

**Comment by kuaashish** [comment]
Hi @pilipicus,

This appears to be a different error. Could you try applying a similar approach(Clang 18.1 fine) for that flag using the following command?

`echo "build --define=xnn_enable_avx512fp16=false" >> .bazelrc
`

**Comment by pilipicus** [comment]
Hi @kalyan2789g,

I've tried your command line and the error that I get is the following one:

![er_2](https://github.com/user-attachments/assets/a45666f5-8d66-4ecd-97ab-edeb04164906)

**Comment by kuaashish** [comment]
@pilipicus,

Please follow the instructions below to disable all flags. Unfortunately, we do not have an older macOS version to reproduce the issue and help with disabling the flags.

clang: error: the clang compiler does not support '-mavxvnniint8’'

- Step 1: Search for the flag in the XNNPack repo:
   https://github.com/search?q=repo%3Agoogle%2FXNNPACK++mavxvnniint8&type=code

- Step 2: Go to result and ding condition name:

  https://github.com/google/XNNPACK/blob/fc3c00d97d135650b6b9e268c9ddd141f053dcb5/build_params.bzl#L568
     Name is avxvnniint8_enabled

- Step 3: Search for avxvnniint8_enabled

   https://github.com/search?q=repo%3Agoogle%2FXNNPACK%20avxvnniint8_enabled&type=code

- Go to result in BUILD.bazel:

    https://github.com/google/XNNPACK/blob/fc3c00d97d135650b6b9e268c9ddd141f053dcb5/BUILD.bazel#L1797

    Find condition name and search in this file: xnn_enable_avxvnniint8_explicit_true

- Go to config name: 

   https://github.com/google/XNNPACK/blob/fc3c00d97d135650b6b9e268c9ddd141f053dcb5/BUILD.bazel#L1313

   config_setting(
     name = "xnn_enable_avxvnniint8_explicit_true",
     define_values = {"xnn_enable_avxvnniint8": "true"},
    )

This is the flag. So you can disable this by passing –define=xnn_enable_avxvnniint8=false by same command.
