### ISSUE TITLE
Usage of `@mediapipe/selfie_segmentation` package on npm is not clear

### ISSUE THREAD

**Issue by aviv-skillset** [google-ai-edge/mediapipe#5755]
Haven't found any docs regarding this, everwhere it seems like the cdn of jsdelivr is the only option but I'm here to suggest this docs update. I think that this snippet is required in the npm readme which is stale https://www.npmjs.com/package/@mediapipe/selfie_segmentation?activeTab=readme

```ts
import { SelfieSegmentation } from "@mediapipe/selfie_segmentation";

function locateFile(file: string) {
// here is all the juice, simply importing from node modules
  const fileLocation = `${import.meta.resolve(
    "../node_modules/@mediapipe/selfie_segmentation"
  )}/${file}`;
  return fileLocation;
}
const selfieSegmentation = new SelfieSegmentation({ locateFile });

selfieSegmentation.setOptions({ modelSelection: 1 });

```
without `locateFile` the package causes errors of compiled js

**Comment by kuaashish** [comment]
Hi @aviv-skillset,

The solution or package you are currently using is part of our legacy solution, which have been upgraded and integrated into the Image Segmentor. You can find the updated information in our [documentation](https://ai.google.dev/edge/mediapipe/solutions/guide#legacy).

Please note that support for all legacy solutions has been discontinued. We recommend using our new Image Segmentor Task API. You can access the [overview page](https://ai.google.dev/edge/mediapipe/solutions/vision/image_segmenter), the [implementation guide for Web](https://ai.google.dev/edge/mediapipe/solutions/vision/image_segmenter/web_js), and the corresponding [npm package here](https://www.npmjs.com/package/@mediapipe/tasks-vision).

We encourage you to try the new solution. If you encounter any issues or have similar concerns, please let us know, we will be happy to assist. Unfortunately, further support for legacy solutions is no longer available.

Thank you!!
