### ISSUE TITLE
TypeError: Descriptors cannot be created directly.

### ISSUE THREAD

**Issue by Sahil-pixel** [google-ai-edge/mediapipe#5758]
Ubuntu 22.04
Python 3.10
media pipe 0.10.18
protobuf-4.25.3
crash after 
```
import mediapipe as mp

```
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by kuaashish** [comment]
Hi @Sahil-pixel,

Please clarify the exact type of support you need. To expedite troubleshooting, please provide detailed error logs and a reproducible code example.

Thank you!!
