### ISSUE TITLE
Would it be possible to produce a document describing the names of the functions in each header file?

### ISSUE THREAD

**Issue by jhlibra** [google-ai-edge/mediapipe#5759]
### Clear description

When compiling the desktop, there is no way to click into the python version to see the details of the header files, you can only go through the header files one by one, and it is difficult to tell which function of which header file is used.

**Comment by kuaashish** [comment]
Hi @jhlibra,

Please clarify the exact type of support you need. To expedite troubleshooting, please provide detailed error logs and a reproducible code example.

Thank you!!
