### ISSUE TITLE
The canonical_face_model.obj file is outdated

### ISSUE THREAD

**Issue by Tiaotiao1130** [google-ai-edge/mediapipe#5760]
### MediaPipe Solution (you are using)

0.10.14

### Programming language

C#

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

Could you update the "mediapipe/modules/face_geometry/data/canonical_face_model.obj" file to match the latest version of MediaPipe, which includes 468 face mesh Vertices that seem to be incompatible with the Vertices, Triangles, and UV coordinates in the existing obj model? Thank you!

### Will this change the current API? How?

no

### Who will benefit with this feature?

Anyone who uses the face mesh standard model

### Please specify the use cases for this feature

https://github.com/homuler/MediaPipeUnityPlugin

**Comment by kuaashish** [comment]
Hi @Tiaotiao1130,

Could you please clarify the meaning of the 'face mesh standard model'? We believe you are referring to the legacy Face Geometry rather than the newer Face Landmarker. Unfortunately, we are unable to update any files related to legacy solutions, as we have ended support for them. Our current focus is on enhancing the new Task API, adding new features, and improving its functionality. 

We recommend exploring the newer Task API and implementing the plugin in Unity, as we do not officially support Unity. Based on our roadmap, it is unlikely that Unity support will be added in the future. We apologise for any inconvenience this may cause.

Thank you!!

**Comment by Tiaotiao1130** [comment]
Thanks for your reply. I used machine translation, so the expression may not be accurate.

I use https://github.com/homuler/MediaPipeUnityPlugin, and the MediaPipe version of the plugin is 0.10.14.

So what I mean is that in the 0.10.14 version of MediaPipe, the 468 feature points obtained by face landmarker do not match the canonical_face_model.obj model in the mediapipe/modules/face_geometry/data/directory.

Because I used the canonical_face_model.obj model in Unity3D, and used the 468 feature points obtained in MediaPipe to update the obj model vertices to display the face mesh. However, due to the mismatch between the feature points and the 3D model, the face mesh cannot be displayed correctly.

So I hope that if your team has free time, can you update a latest standard model obj according to the feature point order of the latest version of face landmarker.

It doesn't matter. If your team has stopped updating and supporting the obj standard model, I will seek help from other channels. I understand that your team has other more important work to do.

Thank you again for your reply

**Comment by Tiaotiao1130** [comment]
I have made a standard fbx model through other channels, and now the problem has been solved. If your team needs it, I can provide you with this standard model
![1](https://github.com/user-attachments/assets/dbbbc144-bac7-4fc1-bc42-ed0668883957)
![2](https://github.com/user-attachments/assets/c09f1501-4657-415d-9f2d-4c08ebb4220e)

**Comment by kuaashish** [comment]
Hi @Tiaotiao1130,

Thank you for your confirmation. We will inform our team. To benefit the community, please share the model plugin and related codebase that will be helpful for whoever looking for a Unity implementation. Additionally, we recommend closing the issue to mark it as resolved internally.
