### ISSUE TITLE
Help on how to dynamically set the model paths hand_landmark_full.tflite and palm_detection_full.tflite in the hand_landmark case

### ISSUE THREAD

**Issue by redsuning** [google-ai-edge/mediapipe#5766]
I'm currently trying to compile hand_tracking case via C++ on a Jetson Xavier device and generate a .so file for qt packaging. But the current default compilation method is to pin the model paths for hand_landmark_full.tflite and palm_detection_full.tflite in both hand_landmark_model_loader.pbtxt and palm_detection_model_loader.pbtxt files. If you need to modify the two TFLITE model paths, you need to recompile them. Is there any way to add the paths of the two models to the hand_tracking_desktop_live_gpu_pbtxt entered when the program is running, and then implement the model path that only needs to be modified hand_tracking_desktop_live_gpu_pbtxt this input file can be modified without recompiling.

**Comment by kuaashish** [comment]
Hi @redsuning,

Apologies, but we currently do not support the Jetson Xavier device. The only supported edge device is the Raspberry Pi, as outlined in our documentation [here](https://ai.google.dev/edge/mediapipe/solutions/setup_python#supported_platforms_and_versions). However, you can find a similar implementation for Jetson Nano [here](https://github.com/PINTO0309/mediapipe-bin?tab=readme-ov-file), and a C++ implementation [here](https://zenn.dev/pinto0309/scraps/71368ef3d74438).

We hope this will help.

Thank you!!

**Comment by redsuning** [comment]
No, my problem and the use of the device have nothing to do with it., you can also think of it as a C++ build under ubuntu. In fact, I have already deployed the entire hand_tracking case. My main question is how to modify hand_tracking_desktop_live_gpu_pbtxt file so that hand_tracking program supports entering model paths for hand_landmark_full.tflite and palm_detection_full.tflite at runtime?

**Comment by kalyan2789g** [comment]
Hi @redsuning,
We do not currently support the pbtxt format. To ensure compatibility and avoid the need for recompilation, we recommend using the serialized protobuf format. This format allows for direct integration of the file into your application.
Thanks,
@kalyan2789g
