### ISSUE TITLE
fix.

### ISSUE THREAD

**Issue by adblock25** [google-ai-edge/mediapipe#5779]
fix.
add in script autorun - tmux new-session -d

_Originally posted by @id8547854 in https://github.com/termux/termux-boot/issues/235#issuecomment-2439176022_

**Comment by adblock25** [comment]
-https://termux.github.io/general/2022/02/15/termux-apps-vulnerability-disclosures.html

**Comment by kuaashish** [comment]
Hi @adblock25,

We are closing this issue as it appears to be unrelated to this repository. We kindly request that you raise the issue in the relevant repository for further assistance. Please let us know if our understanding is incorrect.

Thank you!!
