### ISSUE TITLE
v0.10.20 tag is identical to v0.10.18

### ISSUE THREAD

**Issue by cchadowitz** [google-ai-edge/mediapipe#5784]
If you look at https://github.com/google-ai-edge/mediapipe/tags, both v0.10.18 and v0.10.20 reference the same commit https://github.com/google-ai-edge/mediapipe/commit/76e52c759f87e6e71f531dd785cd892ba163a454

**Comment by kuaashish** [comment]
Hi @cchadowitz,

Thank you for bringing this to our attention. We are aware of the issue and are actively working on a fix. We will notify you once it has been resolved.

**Comment by kuaashish** [comment]
Hi @cchadowitz,

This issue has been fixed and we are now closing this. You can verify the resolution by checking the different commit tag here: https://github.com/google-ai-edge/mediapipe/tags.

Thank you!!
