### ISSUE TITLE
Can't install mediapipe. Python Version 3.12.7

### ISSUE THREAD

**Issue by samuelwhiskeyjohnson** [google-ai-edge/mediapipe#5799]
### OS Platform and Distribution

Windows 10

### Programming Language and version

Python 3.12.7

### Installed using virtualenv? pip? Conda?(if python)

pip

### Android AAR (if android)

None

### Describe the problem

Can't install mediapipe using `pip install mediapipe` Python Version 3.12.7

### Complete Logs

```shell
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe

[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
```

**Comment by samuelwhiskeyjohnson** [comment]
Python 3.12.7 should be supported https://ai.google.dev/edge/mediapipe/solutions/setup_python#supported_platforms_and_versions
But I don't know why it's not working

**Comment by kuaashish** [comment]
Hi @samuelwhiskeyjohnson,

Can you check again. Upon review, we successfully installed MediaPipe 0.10.20 with Python 3.12.7, as shown in the attached screenshot.
<img width="786" alt="Screenshot 2024-12-30 at 12 40 42 PM" src="https://github.com/user-attachments/assets/3dd801fd-8b78-4f18-871b-19fbfd64100a" />

..

<img width="954" alt="Screenshot 2024-12-30 at 12 39 20 PM" src="https://github.com/user-attachments/assets/2c5c3b0e-0578-444d-996f-f9ecb6a326ea" />



Could you please provide the full version of Windows you are using and confirm whether it is a 32-bit or 64-bit system? This information will help us assist you more effectively.

Thank you!!

**Comment by samuelwhiskeyjohnson** [comment]
Sorry the issue wasn't related to media pipe.
Normally I have venv activated automatically in pycharm with python 3.12. But ever since I installed conda, conda takes the priority over venv which uses python 3.13 creating the error.
Fixed by preventing conda from activating automatically.
`conda config --set auto_activate_base false`
